// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import 'package:family_veda/models/health_record.dart';
import 'package:family_veda/providers/active_member_provider.dart';
import 'package:family_veda/providers/records_provider.dart';
import 'package:family_veda/services/api/mobile_api.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

class _FakeMobileApi implements MobileApi {
  final requestedMemberIds = <String>[];

  @override
  Future<List<HealthRecord>> getRecords(String memberId) async {
    requestedMemberIds.add(memberId);
    return [
      HealthRecord(
        id: 'record-$memberId',
        memberId: memberId,
        type: 'Lab report',
        title: 'Synthetic record',
        recordedAt: DateTime.utc(2026, 8, 4),
      ),
    ];
  }

  @override
  Future<void> addRecord({required String memberId, required String recordType, required String title, String? summary, required DateTime occurredOn}) async { }

  @override
  Future<void> addVital({required String memberId, required String vitalType, required double value, required String unit, required DateTime measuredAt}) async { }

  @override
  Future<void> uploadLabReport({required String memberId, required String path}) async { }
}

void main() {
  test('active member switch invalidates member-scoped records', () async {
    final api = _FakeMobileApi();
    final container = ProviderContainer(
      overrides: [mobileApiProvider.overrideWithValue(api)],
    );
    addTearDown(container.dispose);

    container.read(activeMemberProvider.notifier).state = 'member-a';
    final first = await container.read(memberRecordsProvider.future);

    container.read(activeMemberProvider.notifier).state = 'member-b';
    final second = await container.read(memberRecordsProvider.future);

    expect(first.single.memberId, 'member-a');
    expect(second.single.memberId, 'member-b');
    expect(api.requestedMemberIds, ['member-a', 'member-b']);
  });
}
