// Owner: S3 · Triage & Agent Orchestration — Karunathilaka K.D.J.C (IT24100551)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import { DoctorDashboardPanel } from '../doctor/DoctorDashboardPanel'
import { AdminDashboardPanel } from '../admin/AdminDashboardPanel'
// ===== S4 Feature: Family Head / Adult Member dashboard (docs/Three_Portal_Feature_Spec.md) =====
import { FamilyDashboardPanel } from '../family/FamilyDashboardPanel'
import { useAppSelector } from '../../store/hooks'

export function DashboardPage() {
  const user = useAppSelector((state) => state.auth.user)
  const isDoctor = user?.role === 'DOCTOR'
  const isAdmin = user?.role === 'ADMIN'

  if (isDoctor) {
    return <DoctorDashboardPanel />
  }

  if (isAdmin) {
    return <AdminDashboardPanel />
  }

  return <FamilyUserDashboard />
}

// Family Head and Adult Member share one API-backed dashboard (GET /dashboard/family), laid out per the
// three-portal mockups. Symptom submission lives on /triage; agent traces stay doctor-side (blueprint §Triage UI).
function FamilyUserDashboard() {
  return <FamilyDashboardPanel />
}
