// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// [S1] Identity, Family & Consent.
// [S1] Identity, Family & Consent.
import 'package:family_veda/providers/auth_provider.dart';
import 'package:family_veda/theme/app_theme.dart';
import 'package:family_veda/widgets/shared/brand_mark.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

class DemoCredential {
  const DemoCredential({
    required this.role,
    required this.icon,
    required this.userType,
    required this.email,
    required this.password,
    required this.pages,
  });

  final String role;
  final String icon;
  final String userType;
  final String email;
  final String password;
  final List<String> pages;
}

const _demoCredentials = <DemoCredential>[
  DemoCredential(
    role: 'Family Head',
    icon: '👨‍👩‍👧',
    userType: 'FamilyUser (Head)',
    email: 'demo-head@example.invalid',
    password: 'Demo@123456!!',
    pages: ['/dashboard', '/records', '/family', '/audit'],
  ),
  DemoCredential(
    role: 'Adult Member',
    icon: '👤',
    userType: 'FamilyUser (AdultMember)',
    email: 'demo-member@example.invalid',
    password: 'Demo@123456!!',
    pages: ['/dashboard', '/records'],
  ),
  DemoCredential(
    role: 'Verified Doctor',
    icon: '🩺',
    userType: 'Doctor (Verified)',
    email: 'demo-doctor@example.invalid',
    password: 'Demo@123456!!',
    pages: ['/dashboard', '/cases', '/approvals'],
  ),
  DemoCredential(
    role: 'Pending Doctor',
    icon: '⏳',
    userType: 'Doctor (Pending review)',
    email: 'demo-pending@example.invalid',
    password: 'Demo@123456!!',
    pages: ['/doctor-status'],
  ),
  DemoCredential(
    role: 'Clinic Admin',
    icon: '🛡️',
    userType: 'Admin',
    email: 'demo-admin@example.invalid',
    password: 'Demo@123456!!',
    pages: ['/dashboard', '/audit', '/doctor-verification'],
  ),
];

class LoginScreen extends ConsumerStatefulWidget {
  const LoginScreen({super.key});

  @override
  ConsumerState<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends ConsumerState<LoginScreen> {
  final _formKey = GlobalKey<FormState>();
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  String? _activeRole;
  bool _obscurePassword = true;
  bool _showDemoDetails = false;

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  void _fillCredentials(DemoCredential demo) {
    setState(() {
      _emailController.text = demo.email;
      _passwordController.text = demo.password;
      _activeRole = demo.role;
    });
  }

  Future<void> _submit() async {
    final formState = _formKey.currentState;
    if (formState == null || !formState.validate()) return;
    final success = await ref
        .read(authProvider.notifier)
        .login(
          email: _emailController.text.trim(),
          password: _passwordController.text,
        );
    if (success && mounted) context.go('/home');
  }

  Future<void> _retrySignOut() async {
    await ref.read(authProvider.notifier).logout();
  }

  Widget _buildThemeToggle(BuildContext context) {
    final themeMode = ref.watch(themeModeProvider);
    final isDark = themeMode == ThemeMode.dark;

    return Container(
      padding: const EdgeInsets.all(3),
      decoration: BoxDecoration(
        color: isDark ? AppColors.surfaceDark : AppColors.surface,
        borderRadius: BorderRadius.circular(999),
        border: Border.all(
          color: isDark ? AppColors.borderDark : AppColors.border,
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 3,
            offset: const Offset(0, 1),
          ),
        ],
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          _ThemeToggleButton(
            active: !isDark,
            icon: '☀️',
            label: 'Light',
            onTap: () {
              ref.read(themeModeProvider.notifier).state = ThemeMode.light;
            },
          ),
          _ThemeToggleButton(
            active: isDark,
            icon: '🌙',
            label: 'Dark',
            onTap: () {
              ref.read(themeModeProvider.notifier).state = ThemeMode.dark;
            },
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final auth = ref.watch(authProvider);
    final loading = auth.status == AuthStatus.loading;
    final cleanupRequired = auth.status == AuthStatus.cleanupRequired;
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: Colors.transparent,
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          child: Column(
            children: [
              // Top Bar Theme Switcher
              Align(
                alignment: Alignment.topRight,
                child: _buildThemeToggle(context),
              ),
              const SizedBox(height: 12),

              // Centered Elevated Card
              Center(
                child: ConstrainedBox(
                  constraints: const BoxConstraints(maxWidth: 440),
                  child: Container(
                    decoration: BoxDecoration(
                      color: isDark ? AppColors.surfaceDark : AppColors.surface,
                      borderRadius: BorderRadius.circular(22),
                      border: Border.all(
                        color: isDark ? AppColors.borderDark : AppColors.border,
                      ),
                      boxShadow: [
                        BoxShadow(
                          color: (isDark ? Colors.black : const Color(0xFF0F3C32))
                              .withValues(alpha: isDark ? 0.35 : 0.07),
                          blurRadius: 24,
                          offset: const Offset(0, 8),
                        ),
                      ],
                    ),
                    padding: const EdgeInsets.fromLTRB(22, 26, 22, 26),
                    child: Form(
                      key: _formKey,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          // Brand Header
                          Center(
                            child: Column(
                              children: [
                                const BrandLogo(
                                  size: 58,
                                  semanticLabel: 'Family Veda',
                                ),
                                const SizedBox(height: 10),
                                Text(
                                  'Family Veda',
                                  style: TextStyle(
                                    fontSize: 23,
                                    fontWeight: FontWeight.w800,
                                    letterSpacing: -0.4,
                                    color: isDark
                                        ? AppColors.textHeadingDark
                                        : AppColors.textHeading,
                                  ),
                                ),
                                const SizedBox(height: 2),
                                Text(
                                  'CLINICAL WORKSPACE',
                                  style: TextStyle(
                                    fontSize: 11,
                                    fontWeight: FontWeight.w700,
                                    letterSpacing: 1.2,
                                    color: isDark
                                        ? AppColors.primaryDark
                                        : AppColors.primary,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(height: 20),

                          // Section Headings
                          Text(
                            'WORKSPACE ACCESS',
                            style: TextStyle(
                              fontSize: 10.5,
                              fontWeight: FontWeight.w700,
                              letterSpacing: 0.8,
                              color: isDark ? AppColors.faintDark : AppColors.faint,
                            ),
                          ),
                          const SizedBox(height: 3),
                          Text(
                            'Sign in',
                            style: TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.w700,
                              color: isDark
                                  ? AppColors.textHeadingDark
                                  : AppColors.textHeading,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            'Enter your credentials or choose a demo role:',
                            style: TextStyle(
                              fontSize: 13,
                              color: isDark ? AppColors.mutedDark : AppColors.muted,
                            ),
                          ),
                          const SizedBox(height: 14),

                          // Quick Fill Demo Role Dropdown
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 12,
                              vertical: 8,
                            ),
                            decoration: BoxDecoration(
                              color: isDark
                                  ? AppColors.surfaceSubtleDark
                                  : AppColors.surfaceSubtle,
                              border: Border.all(
                                color: isDark
                                    ? AppColors.borderSubtleDark
                                    : AppColors.borderSubtle,
                              ),
                              borderRadius: BorderRadius.circular(12),
                            ),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  '⚡ QUICK FILL DEMO ROLE',
                                  style: TextStyle(
                                    fontSize: 10.5,
                                    fontWeight: FontWeight.w700,
                                    letterSpacing: 0.5,
                                    color: isDark
                                        ? AppColors.primaryDark
                                        : AppColors.primary,
                                  ),
                                ),
                                const SizedBox(height: 2),
                                DropdownButtonHideUnderline(
                                  child: DropdownButton<String>(
                                    value: _activeRole,
                                    hint: Text(
                                      'Select a demo role to test...',
                                      style: TextStyle(
                                        fontSize: 13,
                                        color: isDark
                                            ? AppColors.mutedDark
                                            : AppColors.muted,
                                      ),
                                    ),
                                    isExpanded: true,
                                    icon: Icon(
                                      Icons.keyboard_arrow_down_rounded,
                                      color: isDark
                                          ? AppColors.primaryDark
                                          : AppColors.primary,
                                    ),
                                    dropdownColor: isDark
                                        ? AppColors.surfaceDark
                                        : AppColors.surface,
                                    items: _demoCredentials.map((demo) {
                                      return DropdownMenuItem<String>(
                                        value: demo.role,
                                        child: Text(
                                          '${demo.icon} ${demo.role} — ${demo.userType}',
                                          style: TextStyle(
                                            fontSize: 12.5,
                                            fontWeight: FontWeight.w500,
                                            color: isDark
                                                ? AppColors.textDark
                                                : AppColors.text,
                                          ),
                                          overflow: TextOverflow.ellipsis,
                                        ),
                                      );
                                    }).toList(),
                                    onChanged: (role) {
                                      if (role == null) return;
                                      final demo = _demoCredentials.firstWhere(
                                        (d) => d.role == role,
                                      );
                                      _fillCredentials(demo);
                                    },
                                  ),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(height: 16),

                          // Email Field
                          Text(
                            'Email address',
                            style: TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.w600,
                              color: isDark ? AppColors.textDark : AppColors.text,
                            ),
                          ),
                          const SizedBox(height: 5),
                          TextFormField(
                            key: const Key('email_field'),
                            controller: _emailController,
                            keyboardType: TextInputType.emailAddress,
                            autofillHints: const [AutofillHints.email],
                            enabled: !cleanupRequired,
                            onChanged: (_) {
                              if (_activeRole != null) {
                                setState(() => _activeRole = null);
                              }
                            },
                            decoration: InputDecoration(
                              hintText: 'name@example.invalid',
                              contentPadding: const EdgeInsets.symmetric(
                                horizontal: 12,
                                vertical: 12,
                              ),
                              prefixIcon: Icon(
                                Icons.mail_outline_rounded,
                                size: 18,
                                color: isDark
                                    ? AppColors.mutedDark
                                    : AppColors.muted,
                              ),
                            ),
                            validator: (value) {
                              final email = value?.trim() ?? '';
                              return email.contains('@')
                                  ? null
                                  : 'Enter a valid email address';
                            },
                          ),
                          const SizedBox(height: 14),

                          // Password Field
                          Text(
                            'Password',
                            style: TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.w600,
                              color: isDark ? AppColors.textDark : AppColors.text,
                            ),
                          ),
                          const SizedBox(height: 5),
                          TextFormField(
                            key: const Key('password_field'),
                            controller: _passwordController,
                            obscureText: _obscurePassword,
                            autofillHints: const [AutofillHints.password],
                            enabled: !cleanupRequired,
                            onChanged: (_) {
                              if (_activeRole != null) {
                                setState(() => _activeRole = null);
                              }
                            },
                            decoration: InputDecoration(
                              hintText: 'Enter password',
                              contentPadding: const EdgeInsets.symmetric(
                                horizontal: 12,
                                vertical: 12,
                              ),
                              prefixIcon: Icon(
                                Icons.lock_outline_rounded,
                                size: 18,
                                color: isDark
                                    ? AppColors.mutedDark
                                    : AppColors.muted,
                              ),
                              suffixIcon: IconButton(
                                icon: Icon(
                                  _obscurePassword
                                      ? Icons.visibility_off_outlined
                                      : Icons.visibility_outlined,
                                  size: 18,
                                  color: isDark
                                      ? AppColors.mutedDark
                                      : AppColors.muted,
                                ),
                                onPressed: () {
                                  setState(
                                    () => _obscurePassword = !_obscurePassword,
                                  );
                                },
                              ),
                            ),
                            validator: (value) => (value?.length ?? 0) < 8
                                ? 'Password must be at least 8 characters'
                                : null,
                          ),

                          // Error Banner
                          if (auth.errorMessage != null) ...[
                            const SizedBox(height: 14),
                            Container(
                              padding: const EdgeInsets.symmetric(
                                horizontal: 12,
                                vertical: 9,
                              ),
                              decoration: BoxDecoration(
                                color: isDark
                                    ? const Color(0x33B3261E)
                                    : const Color(0xFFFDE8E8),
                                border: Border.all(
                                  color: isDark
                                      ? AppColors.dangerDark
                                      : const Color(0xFFF8B4B4),
                                ),
                                borderRadius: BorderRadius.circular(10),
                              ),
                              child: Row(
                                children: [
                                  Icon(
                                    Icons.error_outline_rounded,
                                    size: 18,
                                    color: isDark
                                        ? AppColors.dangerDark
                                        : AppColors.danger,
                                  ),
                                  const SizedBox(width: 8),
                                  Expanded(
                                    child: Text(
                                      auth.errorMessage!,
                                      style: TextStyle(
                                        fontSize: 12.5,
                                        fontWeight: FontWeight.w500,
                                        color: isDark
                                            ? AppColors.dangerDark
                                            : AppColors.danger,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                          const SizedBox(height: 18),

                          // Primary Submit Button
                          ElevatedButton(
                            key: const Key('login_button'),
                            onPressed: loading
                                ? null
                                : cleanupRequired
                                ? _retrySignOut
                                : _submit,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: isDark
                                  ? AppColors.primaryDark
                                  : AppColors.primary,
                              foregroundColor: isDark
                                  ? AppColors.onAccentDark
                                  : Colors.white,
                              minimumSize: const Size(double.infinity, 46),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: loading
                                ? const SizedBox.square(
                                    dimension: 18,
                                    child: CircularProgressIndicator(
                                      strokeWidth: 2,
                                      color: Colors.white,
                                    ),
                                  )
                                : Text(
                                    cleanupRequired
                                        ? 'Retry sign out'
                                        : 'Continue securely',
                                    style: const TextStyle(
                                      fontSize: 14.5,
                                      fontWeight: FontWeight.w700,
                                    ),
                                  ),
                          ),

                          // Collapsible Demo Credentials Accordion
                          const SizedBox(height: 14),
                          InkWell(
                            onTap: () {
                              setState(() {
                                _showDemoDetails = !_showDemoDetails;
                              });
                            },
                            borderRadius: BorderRadius.circular(8),
                            child: Padding(
                              padding: const EdgeInsets.symmetric(vertical: 4),
                              child: Row(
                                children: [
                                  Icon(
                                    _showDemoDetails
                                        ? Icons.keyboard_arrow_down_rounded
                                        : Icons.keyboard_arrow_right_rounded,
                                    size: 18,
                                    color: isDark
                                        ? AppColors.primaryDark
                                        : AppColors.primary,
                                  ),
                                  const SizedBox(width: 4),
                                  Expanded(
                                    child: Text(
                                      'View demo credentials & permitted pages',
                                      style: TextStyle(
                                        fontSize: 12.5,
                                        fontWeight: FontWeight.w600,
                                        color: isDark
                                            ? AppColors.primaryDark
                                            : AppColors.primary,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                          if (_showDemoDetails) ...[
                            const SizedBox(height: 8),
                            Container(
                              decoration: BoxDecoration(
                                color: isDark
                                    ? AppColors.surfaceSubtleDark
                                    : AppColors.surfaceSubtle,
                                border: Border.all(
                                  color: isDark
                                      ? AppColors.borderSubtleDark
                                      : AppColors.borderSubtle,
                                ),
                                borderRadius: BorderRadius.circular(10),
                              ),
                              child: ClipRRect(
                                borderRadius: BorderRadius.circular(10),
                                child: Column(
                                  children: _demoCredentials.map((demo) {
                                    final isSelected =
                                        _activeRole == demo.role;
                                    return InkWell(
                                      onTap: () => _fillCredentials(demo),
                                      child: Container(
                                        padding: const EdgeInsets.symmetric(
                                          horizontal: 10,
                                          vertical: 8,
                                        ),
                                        decoration: BoxDecoration(
                                          color: isSelected
                                              ? (isDark
                                                  ? AppColors
                                                      .primarySubtleDark
                                                  : AppColors.primarySubtle)
                                              : Colors.transparent,
                                          border: Border(
                                            bottom: BorderSide(
                                              color: isDark
                                                  ? AppColors
                                                      .borderSubtleDark
                                                  : AppColors.borderSubtle,
                                              width: 0.5,
                                            ),
                                          ),
                                        ),
                                        child: Row(
                                          children: [
                                            Text(
                                              demo.icon,
                                              style: const TextStyle(
                                                fontSize: 16,
                                              ),
                                            ),
                                            const SizedBox(width: 8),
                                            Expanded(
                                              child: Column(
                                                crossAxisAlignment:
                                                    CrossAxisAlignment.start,
                                                children: [
                                                  Text(
                                                    demo.role,
                                                    style: TextStyle(
                                                      fontSize: 12.5,
                                                      fontWeight:
                                                          FontWeight.w700,
                                                      color: isDark
                                                          ? AppColors
                                                              .textHeadingDark
                                                          : AppColors
                                                              .textHeading,
                                                    ),
                                                  ),
                                                  Text(
                                                    demo.email,
                                                    style: TextStyle(
                                                      fontSize: 10.5,
                                                      color: isDark
                                                          ? AppColors
                                                              .mutedDark
                                                          : AppColors.muted,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            Container(
                                              padding:
                                                  const EdgeInsets.symmetric(
                                                    horizontal: 6,
                                                    vertical: 2,
                                                  ),
                                              decoration: BoxDecoration(
                                                color: (isDark
                                                        ? AppColors
                                                            .borderDark
                                                        : AppColors.border)
                                                    .withValues(alpha: 0.4),
                                                borderRadius:
                                                    BorderRadius.circular(
                                                      4,
                                                    ),
                                              ),
                                              child: Text(
                                                demo.password,
                                                style: TextStyle(
                                                  fontSize: 9.5,
                                                  color: isDark
                                                      ? AppColors.textDark
                                                      : AppColors.text,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    );
                                  }).toList(),
                                ),
                              ),
                            ),
                          ],

                          // Footer Links & Notes
                          const SizedBox(height: 14),
                          Center(
                            child: RichText(
                              text: TextSpan(
                                style: TextStyle(
                                  fontSize: 12,
                                  color: isDark
                                      ? AppColors.mutedDark
                                      : AppColors.muted,
                                ),
                                children: [
                                  const TextSpan(
                                    text: 'Need a family account? ',
                                  ),
                                  TextSpan(
                                    text: 'Register',
                                    style: TextStyle(
                                      fontWeight: FontWeight.w700,
                                      color: isDark
                                          ? AppColors.primaryDark
                                          : AppColors.primary,
                                    ),
                                  ),
                                  const TextSpan(text: '.'),
                                ],
                              ),
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            'Demo uses synthetic identities only. No real patient data is stored.',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 10.5,
                              color: isDark
                                  ? AppColors.faintDark
                                  : AppColors.faint,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _ThemeToggleButton extends StatelessWidget {
  const _ThemeToggleButton({
    required this.active,
    required this.icon,
    required this.label,
    required this.onTap,
  });

  final bool active;
  final String icon;
  final String label;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(999),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 140),
        padding: const EdgeInsets.symmetric(horizontal: 11, vertical: 4),
        decoration: BoxDecoration(
          color: active
              ? (isDark
                  ? AppColors.primarySubtleDark
                  : AppColors.primarySubtle)
              : Colors.transparent,
          borderRadius: BorderRadius.circular(999),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(icon, style: const TextStyle(fontSize: 12)),
            const SizedBox(width: 4),
            Text(
              label,
              style: TextStyle(
                fontSize: 11.5,
                fontWeight: active ? FontWeight.w700 : FontWeight.w500,
                color: active
                    ? (isDark ? AppColors.primaryDark : AppColors.primary)
                    : (isDark ? AppColors.mutedDark : AppColors.muted),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
