// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using System.Security.Cryptography;
using System.Text;
using FamilyVeda.Application.Clinical;
using FamilyVeda.Application.Common;
using FamilyVeda.Application.Triage;
using FamilyVeda.Domain.Access;
using FamilyVeda.Domain.Clinical;
using FamilyVeda.Domain.Common;
using FamilyVeda.Domain.Safety;
using FamilyVeda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace FamilyVeda.Infrastructure.Clinical;

public sealed class ClinicalService(
    AppDbContext dbContext,
    ICurrentUser currentUser,
    FamilyVeda.Application.Triage.INotificationService notificationService,
    Microsoft.Extensions.Configuration.IConfiguration configuration) : IClinicalService
{

    public async Task<DoctorDto> RegisterDoctorAsync(RegisterDoctorRequest request, CancellationToken cancellationToken)
    {
        if (currentUser.UserType != UserType.Doctor)
        {
            throw new ForbiddenException();
        }

        if (await dbContext.Doctors.AnyAsync(x => x.UserId == currentUser.UserId, cancellationToken))
        {
            throw new ConflictException("Doctor profile already exists.");
        }

        var normalized = NormalizeRegistration(request.RegistrationNumber);
        var configuredHashKey = configuration["Registration:HashKey"] ?? configuration["Jwt:Key"]
            ?? throw new InvalidOperationException("Registration:HashKey or Jwt:Key is required.");
        var purposeKey = SHA256.HashData(Encoding.UTF8.GetBytes($"FamilyVeda.DoctorRegistration.v1:{configuredHashKey}"));
        var hash = Convert.ToHexString(HMACSHA256.HashData(purposeKey, Encoding.UTF8.GetBytes(normalized)));
        if (await dbContext.Doctors.AnyAsync(x => x.RegistrationNumberHash == hash, cancellationToken))
        {
            throw new ConflictException("Registration number is already registered.");
        }

        var doctor = new Doctor
        {
            UserId = currentUser.UserId,
            RegistrationNumberHash = hash,
            RegistrationNumberLastFour = normalized[^Math.Min(4, normalized.Length)..],
            Specialty = request.Specialty?.Trim()
        };
        dbContext.Doctors.Add(doctor);
        await dbContext.SaveChangesAsync(cancellationToken);
        return MapDoctor(doctor);
    }

    public async Task<DoctorDto> GetMyDoctorAsync(CancellationToken cancellationToken)
    {
        var doctor = await dbContext.Doctors.AsNoTracking().SingleOrDefaultAsync(x => x.UserId == currentUser.UserId, cancellationToken) ?? throw new NotFoundException();
        return MapDoctor(doctor);
    }

    public async Task<PagedResult<DoctorDto>> GetPendingDoctorsAsync(int page, int pageSize, CancellationToken cancellationToken)
    {
        RequireAdmin();
        (page, pageSize) = NormalizePage(page, pageSize);
        var query = dbContext.Doctors.AsNoTracking().Where(x => x.VerificationStatus == VerificationStatus.Pending).OrderBy(x => x.CreatedAt);
        var total = await query.CountAsync(cancellationToken);
        var items = await query.Skip((page - 1) * pageSize).Take(pageSize)
            .Select(x => new DoctorDto(x.Id, x.UserId, x.RegistrationNumberLastFour, x.VerificationStatus, x.Specialty))
            .ToListAsync(cancellationToken);
        return new PagedResult<DoctorDto>(items, page, pageSize, total);
    }

    public async Task<DoctorDto> ChangeVerificationAsync(Guid doctorId, VerifyDoctorRequest request, CancellationToken cancellationToken)
    {
        RequireAdmin();
        var doctor = await dbContext.Doctors.SingleOrDefaultAsync(x => x.Id == doctorId, cancellationToken) ?? throw new NotFoundException();
        var previous = doctor.VerificationStatus;
        doctor.VerificationStatus = request.Status;
        dbContext.DoctorVerificationLogs.Add(new DoctorVerificationLog
        {
            DoctorId = doctor.Id,
            AdminUserId = currentUser.UserId,
            FromStatus = previous,
            ToStatus = request.Status,
            Reason = request.Reason?.Trim()
        });
        await WriteAuditAsync("DOCTOR_VERIFICATION_CHANGED", "Doctor", doctor.Id, "SUCCESS", cancellationToken);
        await dbContext.SaveChangesAsync(cancellationToken);
        return MapDoctor(doctor);
    }

    public async Task<PagedResult<TriageCaseDto>> GetMyCasesAsync(int page, int pageSize, CancellationToken cancellationToken)
    {
        var doctor = await RequireVerifiedDoctorAsync(cancellationToken);
        (page, pageSize) = NormalizePage(page, pageSize);
        var now = DateTimeOffset.UtcNow;
        var query = dbContext.CaseAccessGrants.AsNoTracking()
            .Where(x => x.DoctorId == doctor.Id && x.RevokedAt == null && x.ExpiresAt > now)
            .Select(x => x.TriageCase!)
            .OrderByDescending(x => x.Priority).ThenBy(x => x.CreatedAt);
        var total = await query.CountAsync(cancellationToken);
        var items = await query.Skip((page - 1) * pageSize).Take(pageSize)
            .Select(x => new TriageCaseDto(x.Id, x.EpisodeId, x.MemberId, x.Status, x.Priority, x.CreatedAt))
            .ToListAsync(cancellationToken);
        return new PagedResult<TriageCaseDto>(items, page, pageSize, total);
    }

    public async Task<PagedResult<AvailableCaseDto>> GetAvailableCasesAsync(int page, int pageSize, CancellationToken cancellationToken)
    {
        await RequireVerifiedDoctorAsync(cancellationToken);
        (page, pageSize) = NormalizePage(page, pageSize);
        var now = DateTimeOffset.UtcNow;
        var slaCutoff = now.AddHours(-configuration.GetValue("Sla:DoctorResponseHours", 6));
        var query = dbContext.TriageCases.AsNoTracking().Where(x =>
            (x.Status == TriageStatus.PendingDoctorReview || x.Status == TriageStatus.LowConfidence || x.Status == TriageStatus.Claimed || x.Status == TriageStatus.Escalated) &&
            (!x.AccessGrants.Any(g => g.RevokedAt == null && g.ExpiresAt > now) ||
             x.AccessGrants.Any(g => g.RevokedAt == null && g.ExpiresAt > now && g.CreatedAt <= slaCutoff)));
        var total = await query.CountAsync(cancellationToken);
        var items = await query.OrderByDescending(x => x.Priority).ThenBy(x => x.CreatedAt).Skip((page - 1) * pageSize).Take(pageSize)
            .Select(x => new AvailableCaseDto(x.Id, x.Priority, x.CreatedAt)).ToListAsync(cancellationToken);
        dbContext.AuditLogs.Add(new AuditLog
        {
            ActorUserId = currentUser.UserId,
            EventType = "CASE_POOL_READ",
            ResourceType = "CasePool",
            Outcome = "SUCCESS",
            MetadataJson = "{}"
        });
        await dbContext.SaveChangesAsync(cancellationToken);
        return new PagedResult<AvailableCaseDto>(items, page, pageSize, total);
    }

    public async Task<ApprovalDto> ClaimCaseAsync(Guid caseId, CancellationToken cancellationToken)
    {
        var doctor = await RequireVerifiedDoctorAsync(cancellationToken);
        var triageCase = await dbContext.TriageCases.SingleOrDefaultAsync(
            x => x.Id == caseId && (x.Status == TriageStatus.PendingDoctorReview || x.Status == TriageStatus.LowConfidence || x.Status == TriageStatus.Claimed || x.Status == TriageStatus.Escalated),
            cancellationToken) ?? throw new NotFoundException();
        var now = DateTimeOffset.UtcNow;
        var slaCutoff = now.AddHours(-configuration.GetValue("Sla:DoctorResponseHours", 6));
        var existingUnrevokedGrants = await dbContext.CaseAccessGrants
            .Where(x => x.TriageCaseId == caseId && x.RevokedAt == null)
            .ToListAsync(cancellationToken);
        if (existingUnrevokedGrants.Any(x => x.ExpiresAt > now && x.CreatedAt > slaCutoff))
        {
            throw new ConflictException("Case is already claimed.");
        }
        foreach (var grant in existingUnrevokedGrants) grant.RevokedAt = now;

        dbContext.CaseAccessGrants.Add(new CaseAccessGrant
        {
            TriageCaseId = caseId,
            DoctorId = doctor.Id,
            ExpiresAt = now.AddHours(configuration.GetValue("Grants:ExpiryHours", 48)),
            Reason = "CASE_CLAIM"
        });
        if (triageCase.Status != TriageStatus.Escalated) triageCase.Status = TriageStatus.Claimed;
        var approval = new Approval
        {
            TriageCaseId = caseId,
            DoctorId = doctor.Id,
            Action = ApprovalAction.RequestInformation,
            DoctorNotes = triageCase.Status == TriageStatus.Escalated ? "Emergency referral acknowledged." : "Case claimed for review.",
            DecidedAt = now
        };
        dbContext.Approvals.Add(approval);
        await WriteAuditAsync("CASE_CLAIMED", "TriageCase", caseId, "SUCCESS", cancellationToken, triageCase.MemberId);
        try
        {
            await dbContext.SaveChangesAsync(cancellationToken);
        }
        catch (DbUpdateException)
        {
            dbContext.ChangeTracker.Clear();
            throw new ConflictException("Case was claimed by another doctor.");
        }
        return MapApproval(approval);
    }

    public async Task<ApprovalDto> DecideCaseAsync(Guid caseId, ApprovalRequest request, CancellationToken cancellationToken)
    {
        var doctor = await RequireVerifiedDoctorAsync(cancellationToken);
        var triageCase = await dbContext.TriageCases.SingleOrDefaultAsync(x => x.Id == caseId, cancellationToken) ?? throw new NotFoundException();
        if (triageCase.Status is not (TriageStatus.PendingDoctorReview or TriageStatus.LowConfidence or TriageStatus.Claimed))
        {
            throw new ConflictException("Case already has a terminal decision.");
        }
        var grant = await dbContext.CaseAccessGrants.AsNoTracking()
            .Where(x => x.TriageCaseId == caseId && x.DoctorId == doctor.Id)
            .OrderByDescending(x => x.ExpiresAt)
            .FirstOrDefaultAsync(cancellationToken);
        if (grant is null || !CaseGrantPolicy.HasAccess(grant.ExpiresAt, grant.RevokedAt, DateTimeOffset.UtcNow))
        {
            throw new NotFoundException();
        }

        var approving = request.Action is ApprovalAction.Approve or ApprovalAction.ReviseAndApprove;
        if (approving && string.IsNullOrWhiteSpace(request.FinalAdvisory))
        {
            throw new ValidationException(new Dictionary<string, string[]> { ["finalAdvisory"] = ["Doctor-approved guidance is required."] });
        }

        if (approving)
        {
            if (!SafetyValidationService.IsApprovedPatientGuidance(request.FinalAdvisory!))
            {
                throw new ValidationException(new Dictionary<string, string[]> { ["finalAdvisory"] = ["Select an approved non-diagnostic guidance statement."] });
            }
        }

        triageCase.Status = request.Action switch
        {
            ApprovalAction.Approve => TriageStatus.Approved,
            ApprovalAction.ReviseAndApprove => TriageStatus.ApprovedRevised,
            ApprovalAction.Reject => TriageStatus.Rejected,
            ApprovalAction.Escalate => TriageStatus.Escalated,
            _ => TriageStatus.PendingDoctorReview
        };
        var approval = new Approval
        {
            TriageCaseId = caseId,
            DoctorId = doctor.Id,
            Action = request.Action,
            DoctorNotes = request.DoctorNotes?.Trim(),
            FinalAdvisory = approving ? request.FinalAdvisory!.Trim() : null,
            DecidedAt = DateTimeOffset.UtcNow
        };
        dbContext.Approvals.Add(approval);
        if (triageCase.Status is TriageStatus.Approved or TriageStatus.ApprovedRevised or TriageStatus.Rejected or TriageStatus.Escalated)
        {
            var activeGrants = await dbContext.CaseAccessGrants
                .Where(x => x.TriageCaseId == caseId && x.RevokedAt == null)
                .ToListAsync(cancellationToken);
            foreach (var activeGrant in activeGrants) activeGrant.RevokedAt = approval.DecidedAt;
        }
        await WriteAuditAsync("CASE_DECISION", "TriageCase", caseId, "SUCCESS", cancellationToken, triageCase.MemberId);
        try
        {
            await dbContext.SaveChangesAsync(cancellationToken);
        }
        catch (DbUpdateConcurrencyException)
        {
            dbContext.ChangeTracker.Clear();
            throw new ConflictException("Case was decided by another doctor.");
        }
        await notificationService.SendCaseStatusAsync(caseId, triageCase.Status, cancellationToken);
        return MapApproval(approval);
    }

    public async Task<PagedResult<AuditDto>> GetAuditAsync(Guid? subjectMemberId, int page, int pageSize, CancellationToken cancellationToken)
    {
        (page, pageSize) = NormalizePage(page, pageSize);
        var query = dbContext.AuditLogs.AsNoTracking();
        if (currentUser.UserType == UserType.Admin)
        {
            if (subjectMemberId is not null)
            {
                query = query.Where(x => x.SubjectMemberId == subjectMemberId);
            }
        }
        else if (currentUser.UserType == UserType.FamilyUser)
        {
            var adultCutoff = DateOnly.FromDateTime(DateTime.UtcNow).AddYears(-18);
            var allowedMembers = dbContext.Members.Where(x => x.UserId == currentUser.UserId ||
                (x.Family!.CreatedByUserId == currentUser.UserId && x.DateOfBirth > adultCutoff))
                .Select(x => x.Id);
            query = query.Where(x => x.SubjectMemberId != null && allowedMembers.Contains(x.SubjectMemberId.Value));
            if (subjectMemberId is not null)
            {
                query = query.Where(x => x.SubjectMemberId == subjectMemberId);
            }
        }
        else
        {
            throw new ForbiddenException();
        }

        var total = await query.CountAsync(cancellationToken);
        var items = await query.OrderByDescending(x => x.CreatedAt).Skip((page - 1) * pageSize).Take(pageSize)
            .Select(x => new AuditDto(x.Id, x.EventType, x.ResourceType, x.ResourceId, x.Outcome, x.CreatedAt))
            .ToListAsync(cancellationToken);
        return new PagedResult<AuditDto>(items, page, pageSize, total);
    }

    private async Task<Doctor> RequireVerifiedDoctorAsync(CancellationToken cancellationToken) =>
        currentUser.UserType == UserType.Doctor
            ? await dbContext.Doctors.SingleOrDefaultAsync(x => x.UserId == currentUser.UserId && x.VerificationStatus == VerificationStatus.Verified, cancellationToken)
                ?? throw new ForbiddenException()
            : throw new ForbiddenException();

    private void RequireAdmin()
    {
        if (currentUser.UserType != UserType.Admin)
        {
            throw new ForbiddenException();
        }
    }

    private async Task WriteAuditAsync(string eventType, string resourceType, Guid resourceId, string outcome, CancellationToken cancellationToken, Guid? subjectMemberId = null)
    {
        dbContext.AuditLogs.Add(new AuditLog
        {
            ActorUserId = currentUser.UserId,
            SubjectMemberId = subjectMemberId,
            EventType = eventType,
            ResourceType = resourceType,
            ResourceId = resourceId,
            Outcome = outcome
        });
        await Task.CompletedTask;
    }

    private static string NormalizeRegistration(string value)
    {
        var normalized = new string(value.Where(char.IsLetterOrDigit).Select(char.ToUpperInvariant).ToArray());
        if (normalized.Length < 4 || normalized.Length > 30)
        {
            throw new ValidationException(new Dictionary<string, string[]> { ["registrationNumber"] = ["Registration number format is invalid."] });
        }
        return normalized;
    }

    private static DoctorDto MapDoctor(Doctor x) => new(x.Id, x.UserId, x.RegistrationNumberLastFour, x.VerificationStatus, x.Specialty);
    private static ApprovalDto MapApproval(Approval x) => new(x.Id, x.TriageCaseId, x.DoctorId, x.Action, x.DecidedAt);
    private static (int Page, int PageSize) NormalizePage(int page, int pageSize) => (Math.Max(page, 1), Math.Clamp(pageSize, 1, 100));
}
