// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import { useCallback, useEffect, useState } from 'react'

import { EmptyState, ErrorState, LoadingState } from '../../components/shared/ViewState'
import { Pagination } from '../../components/shared/Pagination'
import { StatusBadge } from '../../components/shared/StatusBadge'
import { apiClient, type AuditDto, type PagedResult } from '../../services/apiClient'

export function AuditPage() {
  const [events, setEvents] = useState<AuditDto[]>([])
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading')
  const [page, setPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)
  const loadAudit = useCallback(async () => {
    setStatus('loading')
    try {
      const { data } = await apiClient.get<PagedResult<AuditDto>>('/audit', { params: { page, pageSize: 20 } })
      setEvents(data.items); setTotalPages(Math.max(1, data.totalPages)); setStatus('ready')
    } catch { setStatus('error') }
  }, [page])
  useEffect(() => { void loadAudit() }, [loadAudit])

  return <div className="page-stack">
    <header className="page-header"><div><p className="eyebrow">Consent and access history</p><h1>Audit activity</h1><p>Clinical content is excluded; this view shows access metadata only.</p></div></header>
    <section className="panel">
      {status === 'loading' ? <LoadingState label="Loading audit activity" /> : status === 'error' ? <ErrorState message="Audit activity could not be loaded." onRetry={() => void loadAudit()} /> : events.length === 0 ? <EmptyState title="No audit activity" message="No permitted audit events are available." /> : <div className="table-scroll"><table><caption className="sr-only">Audit activity</caption><thead><tr><th>Event</th><th>Resource</th><th>Time</th><th>Outcome</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td>{event.eventType.replaceAll('_', ' ')}</td><td>{event.resourceType}</td><td>{new Date(event.createdAt).toLocaleString()}</td><td><StatusBadge status={event.outcome} /></td></tr>)}</tbody></table></div>}
      <Pagination currentPage={page} totalPages={totalPages} onPageChange={setPage} />
    </section>
  </div>
}
