// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import { useCallback, useEffect, useState } from 'react'

import { EmptyState, ErrorState, LoadingState } from '../../components/shared/ViewState'
import { Pagination } from '../../components/shared/Pagination'
import { StatusBadge } from '../../components/shared/StatusBadge'
import { apiClient, type AuditDto, type PagedResult } from '../../services/apiClient'

export function AuditPage() {
  const [events, setEvents] = useState<AuditDto[]>([])
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading')
  const [page, setPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)
  const [agentOnly, setAgentOnly] = useState(false)
  const loadAudit = useCallback(async () => {
    setStatus('loading')
    try {
      const { data } = await apiClient.get<PagedResult<AuditDto>>('/audit', { params: { page, pageSize: 20 } })
      setEvents(data.items); setTotalPages(Math.max(1, data.totalPages)); setStatus('ready')
    } catch { setStatus('error') }
  }, [page])
  useEffect(() => { void loadAudit() }, [loadAudit])
  // S1 · tool-permission layer: TOOL_* events are written by the backend dispatcher when an agent
  // requests a tool outside its allow-list. Filter applies to the loaded page.
  const visible = agentOnly ? events.filter((event) => event.eventType.startsWith('TOOL_')) : events
  const deniedCount = events.filter((event) => event.eventType === 'TOOL_DENIED').length

  return <div className="page-stack">
    <header className="page-header"><div><p className="eyebrow">Consent and access history</p><h1>Audit activity</h1><p>Clinical content is excluded; this view shows access metadata only.</p></div></header>
    <section className="panel">
      <label className="field"><span><input type="checkbox" checked={agentOnly} onChange={(event) => setAgentOnly(event.target.checked)} /> Show only agent tool-permission events</span></label>
      {deniedCount > 0 && <p role="status"><span className="status-badge status-badge--danger">{deniedCount} denied agent tool call{deniedCount === 1 ? '' : 's'}</span> on this page. The dispatcher blocked tools outside the agent allow-list.</p>}
      {status === 'loading' ? <LoadingState label="Loading audit activity" /> : status === 'error' ? <ErrorState message="Audit activity could not be loaded." onRetry={() => void loadAudit()} /> : visible.length === 0 ? <EmptyState title="No audit activity" message={agentOnly ? 'No agent tool-permission events on this page.' : 'No permitted audit events are available.'} /> : <div className="table-scroll"><table><caption className="sr-only">Audit activity</caption><thead><tr><th>Event</th><th>Resource</th><th>Time</th><th>Outcome</th></tr></thead><tbody>{visible.map((event) => <tr key={event.id}><td>{event.eventType.replaceAll('_', ' ')}{event.eventType.startsWith('TOOL_') && <> <span className="status-badge status-badge--agent">Agent</span></>}</td><td>{event.resourceType}</td><td>{new Date(event.createdAt).toLocaleString()}</td><td><StatusBadge status={event.outcome} /></td></tr>)}</tbody></table></div>}
      <Pagination currentPage={page} totalPages={totalPages} onPageChange={setPage} />
    </section>
  </div>
}
