// Owner: S2 · Health Records & Extraction — Fernando K.R.N (IT24101875)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using FamilyVeda.Application.Common;
using FamilyVeda.Application.Records;
using FamilyVeda.Domain.Common;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;

namespace FamilyVeda.Api.Controllers;

[Route("api/v1")]
[Authorize(Policy = "FamilyUser")]
public sealed class RecordsController(IRecordService recordService, ILabExtractionService extractionService) : ApiControllerBase
{
    [HttpGet("members/{memberId:guid}/records")]
    public async Task<ActionResult<PagedResult<HealthRecordDto>>> GetRecords(Guid memberId, int page = 1, int pageSize = 20, string? search = null, RecordType? type = null, string sort = "newest", CancellationToken cancellationToken = default) =>
        Ok(await recordService.GetRecordsAsync(memberId, page, pageSize, search, type, sort, cancellationToken));

    [HttpPost("members/{memberId:guid}/records")]
    public async Task<ActionResult<HealthRecordDto>> CreateRecord(Guid memberId, UpsertHealthRecordRequest request, IValidator<UpsertHealthRecordRequest> validator, CancellationToken cancellationToken)
    {
        await ValidateAsync(validator, request, cancellationToken);
        var record = await recordService.CreateRecordAsync(memberId, request, cancellationToken);
        return Created($"/api/v1/records/{record.Id}", record);
    }

    [HttpPut("records/{recordId:guid}")]
    public async Task<ActionResult<HealthRecordDto>> UpdateRecord(Guid recordId, UpsertHealthRecordRequest request, IValidator<UpsertHealthRecordRequest> validator, CancellationToken cancellationToken)
    {
        await ValidateAsync(validator, request, cancellationToken);
        return Ok(await recordService.UpdateRecordAsync(recordId, request, cancellationToken));
    }

    [HttpDelete("records/{recordId:guid}")]
    public async Task<ActionResult<object>> DeleteRecord(Guid recordId, CancellationToken cancellationToken)
    {
        await recordService.DeleteRecordAsync(recordId, cancellationToken);
        return NoContent();
    }

    [HttpPatch("records/{recordId:guid}/sharing")]
    public async Task<ActionResult<HealthRecordDto>> SetRecordSharing(Guid recordId, UpdateSharingRequest request, CancellationToken cancellationToken) =>
        Ok(await recordService.SetRecordSharingAsync(recordId, request.SharedWithFamilyHead, cancellationToken));

    [HttpDelete("lab-reports/{reportId:guid}")]
    public async Task<ActionResult<object>> DeleteLabReport(Guid reportId, CancellationToken cancellationToken)
    {
        await recordService.DeleteLabReportAsync(reportId, cancellationToken);
        return NoContent();
    }

    [HttpGet("members/{memberId:guid}/lab-reports/deleted")]
    public async Task<ActionResult<IReadOnlyList<DeletedLabReportDto>>> GetDeletedLabReports(Guid memberId, CancellationToken cancellationToken) =>
        Ok(await recordService.GetDeletedLabReportsAsync(memberId, cancellationToken));

    [HttpPost("lab-reports/{reportId:guid}/restore")]
    public async Task<ActionResult<LabReportDto>> RestoreLabReport(Guid reportId, CancellationToken cancellationToken) =>
        Ok(await recordService.RestoreLabReportAsync(reportId, cancellationToken));

    [HttpDelete("lab-reports/{reportId:guid}/permanent")]
    public async Task<ActionResult<object>> PermanentlyDeleteLabReport(Guid reportId, CancellationToken cancellationToken)
    {
        await recordService.PermanentlyDeleteLabReportAsync(reportId, cancellationToken);
        return NoContent();
    }

    [HttpPatch("lab-reports/{reportId:guid}/sharing")]
    public async Task<ActionResult<LabReportDto>> SetLabReportSharing(Guid reportId, UpdateSharingRequest request, CancellationToken cancellationToken) =>
        Ok(await recordService.SetLabReportSharingAsync(reportId, request.SharedWithFamilyHead, cancellationToken));

    [HttpGet("members/{memberId:guid}/vitals")]
    public async Task<ActionResult<IReadOnlyList<VitalDto>>> GetVitals(Guid memberId, CancellationToken cancellationToken) =>
        Ok(await recordService.GetVitalsAsync(memberId, cancellationToken));

    [HttpPost("members/{memberId:guid}/vitals")]
    public async Task<ActionResult<VitalDto>> AddVital(Guid memberId, CreateVitalRequest request, IValidator<CreateVitalRequest> validator, CancellationToken cancellationToken)
    {
        await ValidateAsync(validator, request, cancellationToken);
        var vital = await recordService.AddVitalAsync(memberId, request, cancellationToken);
        return Created($"/api/v1/members/{memberId}/vitals/{vital.Id}", vital);
    }

    [HttpGet("members/{memberId:guid}/vitals/trends")]
    public async Task<ActionResult<IReadOnlyList<VitalTrendDto>>> GetVitalTrends(Guid memberId, CancellationToken cancellationToken) =>
        Ok(await recordService.GetVitalTrendsAsync(memberId, cancellationToken));

    [HttpGet("members/{memberId:guid}/lab-reports")]
    public async Task<ActionResult<IReadOnlyList<LabReportDto>>> GetLabReports(Guid memberId, CancellationToken cancellationToken) =>
        Ok(await recordService.GetLabReportsAsync(memberId, cancellationToken));

    [HttpGet("lab-reports/{reportId:guid}")]
    public async Task<ActionResult<LabReportDetailDto>> GetLabReport(Guid reportId, CancellationToken cancellationToken) =>
        Ok(await recordService.GetLabReportDetailAsync(reportId, cancellationToken));

    [HttpGet("lab-reports/{reportId:guid}/file")]
    [Produces("image/png", "image/jpeg", "application/pdf")]
    public async Task<IActionResult> GetLabReportFile(Guid reportId, CancellationToken cancellationToken)
    {
        var file = await recordService.GetLabReportFileAsync(reportId, cancellationToken);
        Response.Headers.CacheControl = "private, no-store";
        Response.Headers["X-Content-Type-Options"] = "nosniff";
        // Uploaded documents are untrusted: never let one run script or reach the API origin if opened directly.
        Response.Headers.ContentSecurityPolicy = "sandbox; default-src 'none'";
        return File(file.Content, file.ContentType);
    }

    [HttpPut("lab-reports/{reportId:guid}/review")]
    public async Task<ActionResult<LabReportDetailDto>> ConfirmLabReport(Guid reportId, ConfirmLabReportRequest request, CancellationToken cancellationToken) =>
        Ok(await recordService.ConfirmLabReportAsync(reportId, request, cancellationToken));

    [HttpPost("members/{memberId:guid}/lab-reports")]
    [Consumes("multipart/form-data")]
    [RequestFormLimits(MultipartBodyLengthLimit = 10_485_760)]
    public async Task<ActionResult<LabReportDto>> UploadLabReport(Guid memberId, [FromForm] LabReportUploadForm form, CancellationToken cancellationToken)
    {
        await using var stream = form.File.OpenReadStream();
        var report = await recordService.UploadLabReportAsync(memberId, form.File.FileName, form.File.ContentType, form.File.Length, stream, form.CollectedAt, cancellationToken);
        return Created($"/api/v1/lab-reports/{report.Id}", report);
    }

    [HttpPost("lab-reports/{reportId:guid}/extract")]
    [EnableRateLimiting("Ocr")]
    // 202: the read is queued and runs in the background; clients poll GET lab-reports/{id} until it leaves Processing.
    public async Task<ActionResult<LabExtractionResultDto>> ExtractLabReport(Guid reportId, CancellationToken cancellationToken) =>
        Accepted($"/api/v1/lab-reports/{reportId}", await extractionService.ExtractAsync(reportId, cancellationToken));

    [HttpGet("members/{memberId:guid}/hereditary-flags")]
    public async Task<ActionResult<IReadOnlyList<HereditaryFlagDto>>> GetHereditaryFlags(Guid memberId, CancellationToken cancellationToken) =>
        Ok(await recordService.GetHereditaryFlagsAsync(memberId, cancellationToken));
}

public sealed class LabReportUploadForm
{
    public required IFormFile File { get; init; }
    public DateTimeOffset? CollectedAt { get; init; }
}
