// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// [S1] Durable, non-secret logout intent storage.
import 'dart:ffi';
import 'dart:io';

import 'package:ffi/ffi.dart';
import 'package:path_provider/path_provider.dart';

typedef _OpenNative = Int32 Function(Pointer<Utf8>, Int32);
typedef _OpenDart = int Function(Pointer<Utf8>, int);
typedef _FileDescriptorNative = Int32 Function(Int32);
typedef _FileDescriptorDart = int Function(int);

abstract interface class LogoutCleanupMarkerStore {
  Future<bool> isPending();
  Future<void> markPending();
  Future<void> clear();
}

class FileLogoutCleanupMarkerStore implements LogoutCleanupMarkerStore {
  FileLogoutCleanupMarkerStore({
    Future<Directory> Function()? directoryProvider,
  }) : _directoryProvider = directoryProvider ?? getApplicationSupportDirectory;

  static const _fileName = '.family_veda_logout_cleanup_pending';
  static final DynamicLibrary _libc = DynamicLibrary.process();
  static final _OpenDart _open = _libc.lookupFunction<_OpenNative, _OpenDart>(
    'open',
  );
  static final _FileDescriptorDart _fsync = _libc
      .lookupFunction<_FileDescriptorNative, _FileDescriptorDart>('fsync');
  static final _FileDescriptorDart _close = _libc
      .lookupFunction<_FileDescriptorNative, _FileDescriptorDart>('close');
  final Future<Directory> Function() _directoryProvider;

  Future<File> _file() async {
    final directory = await _directoryProvider();
    if (!await directory.exists()) await directory.create(recursive: true);
    return File('${directory.path}/$_fileName');
  }

  Future<List<File>> _temporaryFiles(Directory directory) async {
    final prefix = '${directory.path}/$_fileName.';
    return directory
        .list(followLinks: false)
        .where(
          (entity) =>
              entity is File &&
              entity.path.startsWith(prefix) &&
              entity.path.endsWith('.tmp'),
        )
        .cast<File>()
        .toList();
  }

  @override
  Future<bool> isPending() async {
    final marker = await _file();
    if (await marker.exists()) return true;
    return (await _temporaryFiles(marker.parent)).isNotEmpty;
  }

  @override
  Future<void> markPending() async {
    final marker = await _file();
    if (await marker.exists()) return;
    final temporary = File('${marker.path}.$pid.tmp');
    await temporary.writeAsBytes(const [1], flush: true);
    await temporary.rename(marker.path);
    await marker.writeAsBytes(const [], mode: FileMode.append, flush: true);
    _syncDirectory(marker.parent);
  }

  @override
  Future<void> clear() async {
    final marker = await _file();
    var deleted = false;
    if (await marker.exists()) {
      await marker.delete();
      deleted = true;
    }
    for (final temporary in await _temporaryFiles(marker.parent)) {
      await temporary.delete();
      deleted = true;
    }
    if (deleted) _syncDirectory(marker.parent);
    if (await isPending()) {
      throw FileSystemException('Logout cleanup marker was not removed.');
    }
  }

  static void _syncDirectory(Directory directory) {
    final path = directory.path.toNativeUtf8();
    final descriptor = _open(path, 0);
    calloc.free(path);
    if (descriptor < 0) {
      throw FileSystemException(
        'Could not open logout marker directory for sync.',
        directory.path,
      );
    }
    try {
      if (_fsync(descriptor) != 0) {
        throw FileSystemException(
          'Could not sync logout marker directory.',
          directory.path,
        );
      }
    } finally {
      _close(descriptor);
    }
  }
}
