// Owner: S3 · Triage & Agent Orchestration — Karunathilaka K.D.J.C (IT24100551)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import type { AgentTraceDto } from '../../services/apiClient'
import { pipelineStages, terminalStatuses } from './pipelineStages'

type StageState = 'done' | 'failed' | 'running' | 'waiting'

function stageState(trace: AgentTraceDto | undefined, index: number, traces: AgentTraceDto[], caseStatus: string): StageState {
  if (trace) {
    if (trace.status === 'Completed') return 'done'
    if (trace.status === 'Started') return 'running'
    return 'failed' // Failed, ToolDenied, SafeFailure
  }
  if (terminalStatuses.includes(caseStatus)) return 'waiting'
  const completed = pipelineStages.findIndex((stage) => !traces.some((item) => item.agent === stage.agent))
  return completed === index ? 'running' : 'waiting'
}

const stateLabel: Record<StageState, string> = { done: 'Completed', failed: 'Stopped', running: 'Running', waiting: 'Not run' }
const stateTone: Record<StageState, string> = { done: 'success', failed: 'danger', running: 'primary', waiting: 'muted' }

type AgentPipelineProps = {
  traces: AgentTraceDto[]
  caseStatus: string
}

export function AgentPipeline({ traces, caseStatus }: AgentPipelineProps) {
  return (
    <ol className="agent-pipeline" aria-label="Agent pipeline progress">
      {pipelineStages.map((stage, index) => {
        const trace = traces.find((item) => item.agent === stage.agent)
        const state = stageState(trace, index, traces, caseStatus)
        return (
          <li key={stage.agent} className={`agent-pipeline__step agent-pipeline__step--${state}`}>
            <div className="agent-pipeline__head">
              <strong>{index + 1}. {stage.label} agent</strong>
              <span className={`status-badge status-badge--${stateTone[state]}`}>{stateLabel[state]}</span>
            </div>
            <p className="muted">{stage.purpose}</p>
            {trace && (
              <dl className="agent-pipeline__meta">
                <div><dt>Tools allowed</dt><dd>{trace.toolsAllowed.join(', ') || 'None'}</dd></div>
                <div><dt>Tools denied</dt><dd>{trace.toolsDenied.length ? trace.toolsDenied.join(', ') : 'None'}</dd></div>
                <div><dt>Schema valid</dt><dd>{trace.outputSchemaValid ? 'Yes' : 'No'}</dd></div>
                <div><dt>Confidence</dt><dd>{Math.round(trace.confidence * 100)}%</dd></div>
                <div><dt>Latency</dt><dd>{trace.latencyMilliseconds} ms</dd></div>
              </dl>
            )}
          </li>
        )
      })}
      <li className={`agent-pipeline__step agent-pipeline__step--${caseStatus === 'PendingDoctorReview' || caseStatus === 'Claimed' ? 'running' : caseStatus.startsWith('Approved') ? 'done' : 'waiting'}`}>
        <div className="agent-pipeline__head">
          <strong>6. Doctor approval gate</strong>
          <span className="status-badge status-badge--primary">{caseStatus.replace(/([a-z])([A-Z])/g, '$1 $2')}</span>
        </div>
        <p className="muted">A licensed doctor must approve before anything is visible to the patient.</p>
      </li>
    </ol>
  )
}
