// Owner: S3 · Triage & Agent Orchestration — Karunathilaka K.D.J.C (IT24100551)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import '@testing-library/jest-dom/vitest'

import { render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'

const mocks = vi.hoisted(() => ({ get: vi.fn(), post: vi.fn() }))
vi.mock('../../services/apiClient', () => ({ apiClient: mocks }))

import { TriagePage } from './TriagePage'

const family = { id: 'fam-1', name: 'Synthetic', members: [{ id: 'm-1', familyId: 'fam-1', displayName: 'Synthetic Member', dateOfBirth: '1990-01-01', role: 'Head' }] }
const trace = (agent: string, status = 'Completed') => ({ stepNumber: 1, agent, status, toolsRequested: [], toolsAllowed: ['read_member_profile'], toolsDenied: [], confidence: 0.8, latencyMilliseconds: 120, outputSchemaValid: true })

function routeGet(statusDto: object, traces: object[], guidance?: object) {
  mocks.get.mockImplementation((url: string) => {
    if (url === '/families/me') return Promise.resolve({ data: family })
    if (url.endsWith('/triage-cases')) return Promise.resolve({ data: { items: [{ id: 'case-1', episodeId: 'e', memberId: 'm-1', status: 'PendingDoctorReview', priority: 'Routine', createdAt: '2026-09-01T00:00:00Z' }] } })
    if (url.endsWith('/status')) return Promise.resolve({ data: statusDto })
    if (url.endsWith('/traces')) return Promise.resolve({ data: traces })
    if (url.endsWith('/approved-guidance')) return guidance ? Promise.resolve({ data: guidance }) : Promise.reject(new Error('not approved'))
    return Promise.reject(new Error(`unexpected ${url}`))
  })
}

describe('TriagePage', () => {
  beforeEach(() => { mocks.get.mockReset(); mocks.post.mockReset() })

  it('shows each agent step and never requests guidance before approval', async () => {
    routeGet({ id: 'case-1', status: 'PendingDoctorReview', priority: 'Routine' }, ['Coordinator', 'Context', 'Analysis', 'FamilialRisk', 'SafetyValidation'].map((agent) => trace(agent)))
    render(<MemoryRouter><TriagePage /></MemoryRouter>)

    expect(await screen.findByText('5. Safety validation agent')).toBeInTheDocument()
    expect(screen.getAllByText('Completed')).toHaveLength(5)
    expect(mocks.get).not.toHaveBeenCalledWith('/triage-cases/case-1/approved-guidance')
  })

  it('shows a referral instead of AI output when the case failed safe', async () => {
    routeGet({ id: 'case-1', status: 'FailedSafe', priority: 'Routine', failureCode: 'LLM_TIMEOUT' }, [trace('Coordinator'), trace('Context', 'SafeFailure')])
    render(<MemoryRouter><TriagePage /></MemoryRouter>)

    expect(await screen.findByRole('alert')).toHaveTextContent('Please seek in-person care')
    expect(screen.getByText('Stopped')).toBeInTheDocument()
  })

  it('shows only doctor-approved guidance once approved', async () => {
    routeGet({ id: 'case-1', status: 'Approved', priority: 'Routine' }, [trace('Coordinator')], { caseId: 'case-1', status: 'Approved', finalAdvisory: 'Please arrange an in-person clinical review.', approvedAt: '2026-09-02T00:00:00Z', disclaimer: 'Not a diagnosis.' })
    render(<MemoryRouter><TriagePage /></MemoryRouter>)

    expect(await screen.findByText('Doctor-approved guidance')).toBeInTheDocument()
    expect(screen.getByText('Please arrange an in-person clinical review.')).toBeInTheDocument()
  })
})
