// Owner: S3 · Triage & Agent Orchestration — Karunathilaka K.D.J.C (IT24100551)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using FamilyVeda.Application.Agents;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace FamilyVeda.Infrastructure.Agents;

/// <summary>
/// Tries hosted providers in order and falls through to the next one on failure
/// or rate limit, so a single provider hitting its free-tier quota does not stop
/// the agentic pipeline. Order: Gemini (primary, if configured) -> Groq
/// (openai-compatible, if configured) -> local Ollama (always available,
/// last resort). A provider with no API key configured is skipped without
/// making a network call.
/// </summary>
public sealed class LlmFallbackClient(
    GeminiClient gemini,
    ChatCompletionsLlmClient groq,
    OllamaClient ollama,
    IOptions<GeminiOptions> geminiOptions,
    IOptions<LlmOptions> groqOptions,
    ILogger<LlmFallbackClient> logger) : IOllamaClient
{
    public async Task<OllamaResult<T>> GenerateStructuredAsync<T>(string systemPrompt, object input, CancellationToken cancellationToken) where T : class
    {
        var attempts = new List<(string Name, IOllamaClient Client, bool Configured)>
        {
            ("Gemini", gemini, !string.IsNullOrWhiteSpace(geminiOptions.Value.ApiKey)),
            ("Groq", groq, !string.IsNullOrWhiteSpace(groqOptions.Value.ApiKey)),
            ("Ollama", ollama, true),
        };

        Exception? lastError = null;
        foreach (var (name, client, configured) in attempts)
        {
            if (!configured)
            {
                logger.LogInformation("LLM provider {Provider} skipped: no API key configured.", name);
                continue;
            }

            try
            {
                var result = await client.GenerateStructuredAsync<T>(systemPrompt, input, cancellationToken);
                if (name != attempts[0].Name)
                    logger.LogWarning("LLM provider {Provider} served this request after an earlier provider failed.", name);
                return result;
            }
            catch (Exception exception)
            {
                logger.LogWarning(exception, "LLM provider {Provider} failed; falling back to the next configured provider.", name);
                lastError = exception;
            }
        }

        throw new InvalidOperationException("All configured LLM providers failed or are unconfigured.", lastError);
    }
}
