// Owner: S3 · Triage & Agent Orchestration — Karunathilaka K.D.J.C (IT24100551)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// [S3] Triage & Agent Orchestration.
class AppNotification {
  const AppNotification({
    required this.id,
    required this.createdAt,
    required this.isRead,
    this.caseId,
    this.caseStatus,
    // [S4] Three-portal feature fields — NotificationDto per
    // docs/Three_Portal_Feature_Spec.md: {type, title, body, linkPath, readAt}.
    this.type,
    this.title,
    this.body,
    this.linkPath,
  });

  factory AppNotification.fromJson(Map<String, dynamic> json) =>
      AppNotification(
        id: json['id'] as String,
        createdAt: DateTime.parse(json['createdAt'] as String),
        // Triage audit entries have no read state; only portal notifications
        // can be marked read through /notifications/{id}/read.
        isRead: json['type'] == null ? true : json['readAt'] != null,
        caseId: json['caseId'] as String?,
        caseStatus: (json['caseStatus'] ?? json['status']) as String?,
        type: json['type'] as String?,
        title: json['title'] as String?,
        body: json['body'] as String?,
        linkPath: json['linkPath'] as String?,
      );

  final String id;
  final DateTime createdAt;
  final bool isRead;
  final String? caseId;
  final String? caseStatus;
  final String? type;
  final String? title;
  final String? body;
  final String? linkPath;
}
