// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// [S4] Three-portal family features — appointments.
import 'package:family_veda/models/doctor_summary.dart';

enum AppointmentStatus {
  requested,
  confirmed,
  completed,
  cancelled,
  noShow,
  unknown;

  static AppointmentStatus fromApi(String? value) => switch (value) {
    'Requested' => AppointmentStatus.requested,
    'Confirmed' => AppointmentStatus.confirmed,
    'Completed' => AppointmentStatus.completed,
    'Cancelled' => AppointmentStatus.cancelled,
    'NoShow' => AppointmentStatus.noShow,
    _ => AppointmentStatus.unknown,
  };

  String get friendlyLabel => switch (this) {
    AppointmentStatus.requested => 'Awaiting doctor',
    AppointmentStatus.confirmed => 'Confirmed',
    AppointmentStatus.completed => 'Completed',
    AppointmentStatus.cancelled => 'Cancelled',
    AppointmentStatus.noShow => 'Missed appointment',
    AppointmentStatus.unknown => 'Status unavailable',
  };

  bool get isCancellable =>
      this == AppointmentStatus.requested || this == AppointmentStatus.confirmed;
}

class Appointment {
  const Appointment({
    required this.id,
    required this.memberId,
    required this.memberDisplayName,
    required this.startsAt,
    required this.durationMinutes,
    required this.reason,
    required this.status,
    this.familyName,
    this.doctor,
    this.doctorNote,
  });

  factory Appointment.fromJson(Map<String, dynamic> json) => Appointment(
    id: json['id'] as String,
    memberId: json['memberId'] as String,
    memberDisplayName: (json['memberDisplayName'] as String?) ?? 'Family member',
    familyName: json['familyName'] as String?,
    doctor: json['doctor'] == null
        ? null
        : DoctorSummary.fromJson(json['doctor'] as Map<String, dynamic>),
    startsAt: DateTime.parse(json['startsAt'] as String).toLocal(),
    durationMinutes: (json['durationMinutes'] as num?)?.toInt() ?? 30,
    reason: (json['reason'] as String?) ?? '',
    status: AppointmentStatus.fromApi(json['status'] as String?),
    doctorNote: json['doctorNote'] as String?,
  );

  final String id;
  final String memberId;
  final String memberDisplayName;
  final String? familyName;
  final DoctorSummary? doctor;
  final DateTime startsAt;
  final int durationMinutes;
  final String reason;
  final AppointmentStatus status;
  final String? doctorNote;
}
