// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import { describe, expect, it } from 'vitest'

import { structuredEntries } from './approvalReview'

describe('structuredEntries', () => {
  it('unwraps agent outputs that were stored as JSON-encoded strings', () => {
    const raw = JSON.stringify({
      forDoctorReviewOnly: true,
      context: '{"summary":"Synthetic demonstration context"}',
      analysis: '{"summary":"Symptoms recorded for doctor review. No diagnosis is made."}',
      familialRisk: '{"screeningIndication":"none"}',
    })

    expect(structuredEntries(raw)).toEqual([
      { label: 'Context', values: ['Summary: Synthetic demonstration context'] },
      { label: 'Analysis', values: ['Summary: Symptoms recorded for doctor review. No diagnosis is made.'] },
      { label: 'Familial Risk', values: ['Screening Indication: none'] },
    ])
  })

  it('renders nested objects the same way when they are not string-encoded', () => {
    const raw = JSON.stringify({ context: { summary: 'Synthetic demonstration context' }, familialRisk: null })

    expect(structuredEntries(raw)).toEqual([
      { label: 'Context', values: ['Summary: Synthetic demonstration context'] },
      { label: 'Familial Risk', values: ['—'] },
    ])
  })

  it('keeps plain text that only looks like JSON', () => {
    expect(structuredEntries(JSON.stringify({ note: '{not json' }))).toEqual([
      { label: 'Note', values: ['{not json'] },
    ])
  })

  it('falls back to a summary row for non-JSON input', () => {
    expect(structuredEntries('free text')).toEqual([{ label: 'Summary', values: ['free text'] }])
  })
})
