// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// Decision gate UI (Rules 2 and 3). The doctor picks pre-approved guidance wording;
// free-text never becomes patient-visible. Enforcement stays in the backend gate.
import { useEffect } from 'react'

import { IconCheck } from './ApprovalIcons'

const IconMessage = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{marginRight: '6px', flexShrink: 0}}>
    <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/>
  </svg>
)

const IconEscalate = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{marginRight: '6px', flexShrink: 0}}>
    <polygon points="12 2 22 22 2 22"/><path d="M12 8v8"/><path d="M12 16h.01"/>
  </svg>
)

const BtnIconCheck = () => <span style={{marginRight: '6px', display: 'flex'}}><IconCheck /></span>
const BtnIconEdit = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{marginRight: '6px', flexShrink: 0}}>
    <path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"/>
  </svg>
)
const BtnIconX = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{marginRight: '6px', flexShrink: 0}}>
    <path d="M18 6 6 18"/><path d="m6 6 12 12"/>
  </svg>
)

import { approvedGuidance, decisionLabels, type DecisionAction } from './approvalReview'

type PanelProps = {
  advisory: string
  notes: string
  disabled: boolean
  message: string
  onAdvisory: (value: string) => void
  onNotes: (value: string) => void
  onDecide: (action: DecisionAction) => void
}

const actionOrder: Array<{ action: DecisionAction; tone: string; icon: React.ReactNode }> = [
  { action: 'approve', tone: 'btn-approve', icon: <BtnIconCheck /> },
  { action: 'revise', tone: 'btn-revise', icon: <BtnIconEdit /> },
  { action: 'request-info', tone: 'btn-request', icon: <IconMessage /> },
  { action: 'escalate', tone: 'btn-escalate', icon: <IconEscalate /> },
  { action: 'reject', tone: 'btn-reject', icon: <BtnIconX /> },
]

export function ApprovalDecisionPanel(props: PanelProps) {
  const { advisory, notes, disabled, message, onAdvisory, onNotes, onDecide } = props
  return (
    <article className="care-panel approval-decision premium-decision-panel" aria-labelledby="decision-heading">
      <p className="care-eyebrow">Decision gate · human approval</p>
      <h2 id="decision-heading">Doctor review and final guidance</h2>
      <p className="care-caption">
        Choose exactly what may become visible to the patient. The AI draft is never approved automatically.
      </p>
      <div className="care-form">
        <label className="field">
          <span>Final Patient Guidance <span style={{color: '#eab308'}}>*</span></span>
          <select value={advisory} aria-label="Final Patient Guidance" onChange={(event) => onAdvisory(event.target.value)} disabled={disabled}>
            <option value="">Select approved guidance</option>
            {approvedGuidance.map((guidance) => (
              <option key={guidance} value={guidance}>
                {guidance}
              </option>
            ))}
          </select>
        </label>
        <p className="care-caption approval-hint" style={{color: '#94a3b8'}}>
          Doctor-authored or explicitly reviewed text only. No diagnosis, prescriptions or doses in this prototype.
        </p>
        <label className="field">
          <span>Internal Clinical Notes</span>
          <textarea
            rows={3}
            value={notes}
            onChange={(event) => onNotes(event.target.value)}
            maxLength={1000}
            placeholder="Record your decision rationale or why more information is needed..."
            disabled={disabled}
          />
        </label>
        <p className="care-caption approval-hint">
          Doctor-only. Never shown to the patient. {notes.length}/1000
        </p>
      </div>
      {message && (
        <p role="status" className="care-note care-note--warning">
          {message}
        </p>
      )}
      <div className="approval-actions">
        {actionOrder.map(({ action, tone, icon }) => (
          <button
            key={action}
            type="button"
            className={`premium-btn ${tone}`}
            disabled={disabled}
            onClick={() => onDecide(action)}
          >
            {icon}
            {decisionLabels[action]}
          </button>
        ))}
      </div>
      <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '24px', paddingTop: '12px', borderTop: '1px solid #1e293b'}}>
        <p className="care-caption" style={{margin: 0, color: '#94a3b8'}}>Every decision is recorded in the audit log.</p>
        <button type="button" onClick={() => { onAdvisory(''); onNotes(''); }} disabled={disabled} style={{background: 'transparent', border: 'none', color: '#3b82f6', fontSize: '0.85rem', fontWeight: 700, cursor: 'pointer'}}>Clear draft fields</button>
      </div>
    </article>
  )
}

type ConfirmProps = {
  action: DecisionAction
  caseRef: string
  advisory: string
  notes: string
  failedChecks: number
  saving: boolean
  onCancel: () => void
  onConfirm: () => void
}

export function ApprovalConfirmDialog(props: ConfirmProps) {
  const { action, caseRef, advisory, notes, failedChecks, saving, onCancel, onConfirm } = props
  const approving = action === 'approve' || action === 'revise'

  // Once the audited POST is in flight the dialog must stay open until it settles.
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !saving) onCancel()
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [onCancel, saving])

  return (
    <div className="approval-overlay" onClick={(event) => event.target === event.currentTarget && !saving && onCancel()}>
      <div className="approval-dialog" role="dialog" aria-modal="true" aria-labelledby="approval-dialog-title">
        <p className="care-eyebrow">Confirm decision</p>
        <h2 id="approval-dialog-title">
          {decisionLabels[action]} · request {caseRef}
        </h2>
        <p className="care-caption">This action is audited and cannot be undone from this screen.</p>
        {approving && failedChecks > 0 && (
          <p className="care-note care-note--warning">
            {failedChecks} deterministic safety check{failedChecks === 1 ? '' : 's'} did not pass. Consider
            Request Information, Reject or Escalate instead.
          </p>
        )}
        <dl className="approval-facts approval-dialog__preview">
          {approving && (
            <div>
              <dt>Guidance the patient will see</dt>
              <dd>{advisory}</dd>
            </div>
          )}
          <div>
            <dt>Internal notes</dt>
            <dd>{notes.trim() || 'None recorded'}</dd>
          </div>
        </dl>
        <div className="approval-dialog__actions">
          <button type="button" className="button button--secondary" onClick={onCancel} disabled={saving}>
            Cancel
          </button>
          <button
            type="button"
            className={`button ${action === 'reject' ? 'button--danger' : 'button--primary'}`}
            onClick={onConfirm}
            disabled={saving}
            autoFocus
          >
            {saving ? 'Saving…' : 'Confirm decision'}
          </button>
        </div>
      </div>
    </div>
  )
}
