// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// Pure presentation helpers for the doctor approval desk. Nothing here interprets
// clinical content — it only labels, filters and formats what the backend returned.
import type { CaseReviewDto, TriageCaseDto } from '../../services/apiClient'
import { buildSafetyChecks } from './safetyRules'

export type QueueFilter = 'all' | 'priority' | 'routine' | 'low'
export type DecisionAction = 'approve' | 'revise' | 'request-info' | 'reject' | 'escalate'
export type EvidenceEntry = { label: string; values: string[] }

export const approvedGuidance = [
  'Please arrange an in-person clinical review.',
  'Please discuss appropriate screening with a licensed clinician.',
  'Continue monitoring symptoms and seek in-person care if they worsen.',
]

export const reviewableStatuses = new Set(['PendingDoctorReview', 'LowConfidence', 'Claimed'])

export const decisionLabels: Record<DecisionAction, string> = {
  approve: 'Approve',
  revise: 'Revise and Approve',
  'request-info': 'Request Information',
  escalate: 'Escalate',
  reject: 'Reject',
}

/** What a saved decision did and where the case now lives. Mirrors the backend status transitions. */
export function decisionOutcome(action: DecisionAction, caseRef: string): { text: string; to?: string; toLabel?: string } {
  const completed = { to: '/cases?tab=completed', toLabel: 'View in Completed' }
  switch (action) {
    case 'approve':
      return { text: `Decision saved: case ${caseRef} approved. The guidance you selected is now visible to the patient. The case moved to Triage Cases › Completed.`, ...completed }
    case 'revise':
      return { text: `Decision saved: case ${caseRef} approved with your revision. The guidance you selected is now visible to the patient. The case moved to Triage Cases › Completed.`, ...completed }
    case 'reject':
      return { text: `Decision saved: case ${caseRef} rejected. No guidance was released to the patient. The case moved to Triage Cases › Completed.`, ...completed }
    case 'escalate':
      return { text: `Decision saved: case ${caseRef} escalated to urgent in-person care. No AI output was released. The case is now under Triage Cases › Emergency.`, to: '/cases?tab=emergency', toLabel: 'View in Emergency' }
    case 'request-info':
      return { text: `Decision saved: information requested for case ${caseRef}. Nothing was released to the patient. The case stays in this review queue.` }
  }
}

export function statusLabel(status: string) {
  return status.replace(/([a-z])([A-Z])/g, '$1 $2')
}

function fieldLabel(key: string) {
  const spaced = statusLabel(key).replaceAll('_', ' ')
  return spaced.charAt(0).toUpperCase() + spaced.slice(1)
}

export function safeDate(value?: string) {
  const date = value ? new Date(value) : null
  return date && !Number.isNaN(date.valueOf()) ? date : null
}

export function queueDate(value?: string) {
  const date = safeDate(value)
  return date ? date.toLocaleDateString(undefined, { day: 'numeric', month: 'short' }) : 'Date unavailable'
}

export function queueDateTime(value?: string) {
  const date = safeDate(value)
  return date
    ? date.toLocaleString(undefined, { day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' })
    : 'Date unavailable'
}

type CaseRefSource = { id: string; caseNumber?: number }

/** The database case number as 0001; falls back to the id prefix when an older API omits it. */
export function shortRef(item: CaseRefSource) {
  return item.caseNumber && item.caseNumber > 0 ? String(item.caseNumber).padStart(4, '0') : item.id.slice(0, 8)
}

/** Two-letter avatar text: the patient's initials when the grant releases a name, else the case number. */
export function caseInitials(item: CaseRefSource & { memberDisplayName?: string | null }) {
  const words = (item.memberDisplayName ?? '').trim().split(/\s+/).filter(Boolean)
  if (words.length === 0) return shortRef(item).slice(-2).toUpperCase()
  return (words[0][0] + (words.length > 1 ? words[words.length - 1][0] : '')).toUpperCase()
}

export function isPriority(item: { priority: string }) {
  return item.priority === 'Priority' || item.priority === 'Emergency'
}

export function queueBucket(item: TriageCaseDto): Exclude<QueueFilter, 'all'> {
  if (item.status === 'LowConfidence') return 'low'
  return isPriority(item) ? 'priority' : 'routine'
}

export function filterQueue(cases: TriageCaseDto[], filter: QueueFilter, search: string) {
  const term = search.trim().toLowerCase()
  return cases.filter((item) => {
    if (filter !== 'all' && queueBucket(item) !== filter) return false
    if (!term) return true
    return `${item.id} ${shortRef(item)} ${item.memberDisplayName ?? ''} ${item.familyName ?? ''} ${statusLabel(item.status)} ${item.priority}`.toLowerCase().includes(term)
  })
}

const hiddenFields = new Set(['fordoctorreviewonly', 'confidence'])
const readableLabels: Record<string, string> = {
  summary: 'Summary of supplied information', memberprofile: 'Recorded patient context',
  recentvitals: 'Previously recorded vitals', episodes: 'Recorded symptom episodes',
  conditions: 'Recorded conditions', deviations: 'Findings for review',
  stablepatterns: 'Recorded stable patterns', consentedsignals: 'Consented family-history information',
  unknownparties: 'Missing family-history information', screeningindication: 'Screening review note',
}

/** Decode nested serialized agent outputs without interpreting their clinical meaning. */
export function structuredEntries(raw?: string | null): EvidenceEntry[] {
  const entries: EvidenceEntry[] = []
  function visit(value: unknown, label: string, depth: number) {
    if (depth > 8) {
      entries.push({ label, values: ['This structured output could not be displayed. Check the technical trace.'] })
      return
    }
    if (typeof value === 'string') {
      const text = value.trim()
      if (!text) return
      if (/^[{["]/.test(text)) {
        try { visit(JSON.parse(text), label, depth + 1) }
        catch { entries.push({ label, values: ['This structured output could not be displayed. Check the technical trace.'] }) }
      } else entries.push({ label, values: [text] })
    } else if (Array.isArray(value)) {
      value.forEach((item) => visit(item, label, depth + 1))
    } else if (value && typeof value === 'object') {
      Object.entries(value).forEach(([key, nested]) => {
        const normalized = key.replaceAll('_', '').toLowerCase()
        if (hiddenFields.has(normalized)) return
        const nextLabel = readableLabels[normalized] ?? fieldLabel(key)
        if (normalized === 'screeningindication' && typeof nested === 'string' && nested.trim().toLowerCase() === 'none') {
          entries.push({ label: nextLabel, values: ['No additional consented screening indication was reported.'] })
        } else visit(nested, nextLabel, depth + 1)
      })
    } else if (typeof value === 'number') entries.push({ label, values: [String(value)] })
    else if (typeof value === 'boolean') entries.push({ label, values: [value ? 'Yes' : 'No'] })
  }
  if (raw) visit(raw, 'Summary of supplied information', 0)
  return entries.reduce<EvidenceEntry[]>((result, entry) => {
    const existing = result.find((item) => item.label === entry.label)
    if (existing) existing.values.push(...entry.values)
    else result.push(entry)
    return result
  }, [])
}

/** Deterministic, non-clinical reasons this request is sitting in the doctor's queue. */
export function reviewReasons(review: CaseReviewDto): string[] {
  const failed = buildSafetyChecks(review.traces).filter((check) => !check.passed).length
  const reasons: string[] = []
  const episode = review.submittedEpisode
  if (episode?.memberId === review.memberId && episode.symptoms.length > 0) {
    const duration = Number.isInteger(episode.durationDays) && episode.durationDays >= 0
      ? ` Reported duration: ${episode.durationDays} ${episode.durationDays === 1 ? 'day' : 'days'}.`
      : ''
    reasons.push(`Submitted symptoms: ${episode.symptoms.map((symptom) => statusLabel(symptom).replaceAll('_', ' ')).join(', ')}.${duration} This submitted episode requires clinician review.`)
  }
  // Display existing observations as attributed draft evidence; never infer a diagnosis.
  try {
    const analysis: unknown = JSON.parse(review.analysisJson ?? 'null')
    if (analysis && typeof analysis === 'object' && !Array.isArray(analysis)) {
      const fields = Object.entries(analysis)
      const deviations = fields.find(([key]) => key.toLowerCase() === 'deviations')?.[1]
      if (Array.isArray(deviations)) {
        deviations.filter((value): value is string => typeof value === 'string' && value.trim().length > 0)
          .slice(0, 5).forEach((finding) => reasons.push(`AI draft finding for clinician review: ${finding}`))
      }
    }
  } catch {
    // Malformed output remains available in the doctor-only technical trace.
  }
  if (reasons.length === 0)
    reasons.push('Specific review findings are unavailable; review the submitted information during clinical assessment.')
  if (review.status === 'LowConfidence')
    reasons.push('Agent confidence fell below the configured threshold, so the draft may be unreliable.')
  if (isPriority(review)) reasons.push(`Triage priority for this request is ${review.priority}.`)
  if (failed > 0)
    reasons.push(`${failed} deterministic safety check${failed === 1 ? '' : 's'} did not pass.`)
  if (!review.draftAdvisoryJson) reasons.push('No AI draft advisory is available for this request.')
  reasons.push('AI output cannot reach the patient until a doctor records a decision.')
  return reasons
}

/** Matches a trace by agent name fragment, ignoring case and separators (e.g. "FamilialRisk"). */
export function findTrace(traces: CaseReviewDto['traces'], fragment: string) {
  return traces.find((trace) => trace.agent.replace(/[^a-z]/gi, '').toLowerCase().includes(fragment))
}

/** Pretty-prints agent output for reading; text that is not JSON is shown unchanged. */
export function formatJson(raw: string) {
  try {
    return JSON.stringify(JSON.parse(raw), null, 2)
  } catch {
    return raw
  }
}
