// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import 'dart:async';

import 'package:family_veda/main.dart';
import 'package:family_veda/providers/active_member_provider.dart';
import 'package:family_veda/providers/auth_provider.dart';
import 'package:family_veda/providers/core_providers.dart';
import 'package:family_veda/providers/members_provider.dart';
import 'package:family_veda/providers/push_registration_provider.dart';
import 'package:family_veda/services/api/auth_api.dart';
import 'package:family_veda/services/storage/member_preference_store.dart';
import 'package:family_veda/services/storage/secure_token_store.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

class _DelayedMemberPreferenceStore implements MemberPreferenceStore {
  final reads = <String, Completer<String?>>{};

  @override
  Future<void> clearActiveMemberId({required String userId}) async {}

  @override
  Future<String?> readActiveMemberId({required String userId}) =>
      reads.putIfAbsent(userId, Completer<String?>.new).future;

  @override
  Future<void> writeActiveMemberId({
    required String userId,
    required String memberId,
  }) async {}
}

class _MemoryTokenStore implements TokenStore {
  final expirations = StreamController<void>.broadcast();
  bool cleanupPending = false;

  @override
  Future<void> clear() async {}

  @override
  Future<void> clearCleanupPending() async => cleanupPending = false;

  @override
  Future<void> expireSession() async {
    cleanupPending = false;
    expirations.add(null);
  }

  @override
  Future<bool> isCleanupPending() async => cleanupPending;

  @override
  Future<void> markCleanupPending() async => cleanupPending = true;

  @override
  Future<String?> readAccessToken() async => null;

  @override
  Future<String?> readRefreshToken() async => null;

  @override
  Stream<void> get sessionExpirations => expirations.stream;

  @override
  Future<void> writeTokens({
    required String accessToken,
    required String refreshToken,
  }) async {}
}

class _SwitchingAuthApi implements AuthApi {
  String userId = 'synthetic-user-a';

  @override
  Future<AuthTokens> login({
    required String email,
    required String password,
  }) async => AuthTokens(
    userId: userId,
    accessToken: 'synthetic-access',
    refreshToken: 'synthetic-refresh',
  );

  @override
  Future<void> logout() async {}

  @override
  Future<AuthTokens> refresh(String refreshToken) => throw UnimplementedError();
}

void main() {
  testWidgets('late account restore cannot overwrite current member scope', (
    tester,
  ) async {
    final tokenStore = _MemoryTokenStore();
    final authApi = _SwitchingAuthApi();
    final memberStore = _DelayedMemberPreferenceStore();
    addTearDown(tokenStore.expirations.close);

    await tester.pumpWidget(
      ProviderScope(
        overrides: [
          tokenStoreProvider.overrideWithValue(tokenStore),
          authApiProvider.overrideWithValue(authApi),
          memberPreferenceStoreProvider.overrideWithValue(memberStore),
          membersProvider.overrideWith((ref) async => const []),
          pushRegistrationProvider.overrideWith((ref) async => false),
        ],
        child: const FamilyVedaApp(),
      ),
    );
    await tester.pump();
    final container = ProviderScope.containerOf(
      tester.element(find.byType(FamilyVedaApp)),
    );

    await container
        .read(authProvider.notifier)
        .login(email: 'user-a@example.test', password: 'password');
    await tester.pump();
    expect(memberStore.reads, contains('synthetic-user-a'));

    await container.read(authProvider.notifier).logout();
    authApi.userId = 'synthetic-user-b';
    await container
        .read(authProvider.notifier)
        .login(email: 'user-b@example.test', password: 'password');
    await tester.pump();
    memberStore.reads['synthetic-user-b']!.complete(null);
    await tester.pump();

    memberStore.reads['synthetic-user-a']!.complete('member-user-a');
    await tester.pump();

    expect(container.read(authProvider).userId, 'synthetic-user-b');
    expect(container.read(activeMemberProvider), isNull);
  });
}
