// Owner: S3 · Triage & Agent Orchestration — Karunathilaka K.D.J.C (IT24100551)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// Marks any AI-derived item so it never blends into doctor-approved or user-entered content
// (Clinical Rules 1 and 2).
type AiBadgeProps = {
  label?: string
  title?: string
}

export function AiBadge({ label = 'AI-assisted', title = 'AI-assisted output. Requires doctor or manual review before use.' }: AiBadgeProps) {
  return (
    <span className="status-badge status-badge--agent" title={title} aria-label={`${label}: ${title}`}>
      {label}
    </span>
  )
}
