// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using FamilyVeda.Application.Common;
using FamilyVeda.Application.Portal;
using FamilyVeda.Domain.Clinical;
using FamilyVeda.Domain.Identity;
using FamilyVeda.Domain.Portal;
using FamilyVeda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace FamilyVeda.Infrastructure.Portal;

public sealed class AppointmentService(AppDbContext dbContext, ICurrentUser currentUser) : IAppointmentService
{
    public async Task<AppointmentDto> BookAsync(CreateAppointmentRequest request, CancellationToken cancellationToken)
    {
        var member = await dbContext.Members.SingleOrDefaultAsync(x => x.Id == request.MemberId, cancellationToken) ?? throw new NotFoundException();
        var isSelf = member.UserId == currentUser.UserId;
        var isMinor = member.DateOfBirth.AddYears(18) > DateOnly.FromDateTime(DateTime.UtcNow);
        var isHead = await dbContext.Families.AnyAsync(x => x.Id == member.FamilyId && x.CreatedByUserId == currentUser.UserId, cancellationToken);
        var allowed = isSelf || (isHead && isMinor);
        if (!allowed)
        {
            throw new NotFoundException();
        }

        if (string.IsNullOrWhiteSpace(request.Reason) || request.Reason.Trim().Length > 200)
        {
            throw new Application.Common.ValidationException(new Dictionary<string, string[]> { ["reason"] = ["Reason is required and cannot exceed 200 characters."] });
        }

        if (request.StartsAt <= DateTimeOffset.UtcNow)
        {
            throw new Application.Common.ValidationException(new Dictionary<string, string[]> { ["startsAt"] = ["Appointment time must be in the future."] });
        }

        var duration = request.DurationMinutes ?? 30;
        if (duration is < 15 or > 120)
        {
            throw new Application.Common.ValidationException(new Dictionary<string, string[]> { ["durationMinutes"] = ["Duration must be between 15 and 120 minutes."] });
        }

        var assignment = await dbContext.FamilyDoctorAssignments.AsNoTracking()
            .FirstOrDefaultAsync(x => x.FamilyId == member.FamilyId && x.IsPrimary && x.EndedAt == null, cancellationToken)
            ?? throw new ConflictException("This family does not have a primary doctor yet.");

        var endsAt = request.StartsAt.AddMinutes(duration);
        var overlapping = await dbContext.Appointments.AnyAsync(x =>
            x.DoctorId == assignment.DoctorId &&
            (x.Status == AppointmentStatus.Requested || x.Status == AppointmentStatus.Confirmed) &&
            x.StartsAt < endsAt &&
            request.StartsAt < x.StartsAt.AddMinutes(x.DurationMinutes), cancellationToken);
        if (overlapping)
        {
            throw new ConflictException("The doctor already has an appointment overlapping this time.");
        }

        var appointment = new Appointment
        {
            MemberId = member.Id,
            DoctorId = assignment.DoctorId,
            BookedByUserId = currentUser.UserId,
            StartsAt = request.StartsAt,
            DurationMinutes = duration,
            Reason = request.Reason.Trim()
        };
        dbContext.Appointments.Add(appointment);
        AddAudit("APPOINTMENT_REQUESTED", appointment.Id);
        var doctorUserId = await dbContext.Doctors.Where(x => x.Id == assignment.DoctorId).Select(x => x.UserId).SingleAsync(cancellationToken);
        AddNotification(doctorUserId, "APPOINTMENT_REQUESTED", "New appointment request", "A new appointment has been requested.", "/doctor/appointments");
        await dbContext.SaveChangesAsync(cancellationToken);
        return await MapAsync(appointment, cancellationToken);
    }

    public async Task<IReadOnlyList<AppointmentDto>> GetMineAsync(CancellationToken cancellationToken)
    {
        var myMemberIds = await dbContext.Members.Where(x => x.UserId == currentUser.UserId).Select(x => x.Id).ToListAsync(cancellationToken);
        var head = await dbContext.Families.FirstOrDefaultAsync(x => x.CreatedByUserId == currentUser.UserId, cancellationToken);
        var memberIds = new List<Guid>(myMemberIds);
        if (head is not null)
        {
            var adultCutoff = DateOnly.FromDateTime(DateTime.UtcNow).AddYears(-18);
            var minorIds = await dbContext.Members.Where(x => x.FamilyId == head.Id && x.DateOfBirth > adultCutoff).Select(x => x.Id).ToListAsync(cancellationToken);
            memberIds.AddRange(minorIds);
        }

        var appointments = await dbContext.Appointments.AsNoTracking()
            .Where(x => memberIds.Contains(x.MemberId))
            .OrderByDescending(x => x.StartsAt)
            .ToListAsync(cancellationToken);
        var results = new List<AppointmentDto>();
        foreach (var appointment in appointments)
        {
            results.Add(await MapAsync(appointment, cancellationToken));
        }
        return results;
    }

    public async Task<AppointmentDto> CancelAsync(Guid id, CancellationToken cancellationToken)
    {
        var appointment = await dbContext.Appointments.SingleOrDefaultAsync(x => x.Id == id, cancellationToken) ?? throw new NotFoundException();
        var member = await dbContext.Members.SingleAsync(x => x.Id == appointment.MemberId, cancellationToken);
        var allowed = appointment.BookedByUserId == currentUser.UserId || member.UserId == currentUser.UserId;
        if (!allowed)
        {
            throw new NotFoundException();
        }
        if (appointment.Status is not (AppointmentStatus.Requested or AppointmentStatus.Confirmed))
        {
            throw new ConflictException($"Appointment cannot be cancelled from status {appointment.Status}.");
        }

        appointment.Status = AppointmentStatus.Cancelled;
        AddAudit("APPOINTMENT_STATUS_CHANGED", appointment.Id);
        await dbContext.SaveChangesAsync(cancellationToken);
        return await MapAsync(appointment, cancellationToken);
    }

    public async Task<IReadOnlyList<AppointmentDto>> GetForDoctorAsync(DateTimeOffset? from, DateTimeOffset? to, CancellationToken cancellationToken)
    {
        var doctor = await RequireDoctorAsync(cancellationToken);
        var query = dbContext.Appointments.AsNoTracking().Where(x => x.DoctorId == doctor.Id);
        if (from is not null) query = query.Where(x => x.StartsAt >= from);
        if (to is not null) query = query.Where(x => x.StartsAt <= to);
        var appointments = await query.OrderBy(x => x.StartsAt).ToListAsync(cancellationToken);
        var results = new List<AppointmentDto>();
        foreach (var appointment in appointments)
        {
            results.Add(await MapAsync(appointment, cancellationToken));
        }
        return results;
    }

    public Task<AppointmentDto> ConfirmAsync(Guid id, AppointmentActionRequest request, CancellationToken cancellationToken) =>
        TransitionAsync(id, AppointmentStatus.Requested, AppointmentStatus.Confirmed, request, cancellationToken);

    public Task<AppointmentDto> CompleteAsync(Guid id, AppointmentActionRequest request, CancellationToken cancellationToken) =>
        TransitionAsync(id, AppointmentStatus.Confirmed, AppointmentStatus.Completed, request, cancellationToken);

    public Task<AppointmentDto> NoShowAsync(Guid id, AppointmentActionRequest request, CancellationToken cancellationToken) =>
        TransitionAsync(id, AppointmentStatus.Confirmed, AppointmentStatus.NoShow, request, cancellationToken);

    public async Task<AppointmentDto> DoctorCancelAsync(Guid id, AppointmentActionRequest request, CancellationToken cancellationToken)
    {
        var doctor = await RequireDoctorAsync(cancellationToken);
        var appointment = await dbContext.Appointments.SingleOrDefaultAsync(x => x.Id == id && x.DoctorId == doctor.Id, cancellationToken) ?? throw new NotFoundException();
        if (appointment.Status is not (AppointmentStatus.Requested or AppointmentStatus.Confirmed))
        {
            throw new ConflictException($"Appointment cannot be cancelled from status {appointment.Status}.");
        }
        appointment.Status = AppointmentStatus.Cancelled;
        if (!string.IsNullOrWhiteSpace(request.Note)) appointment.DoctorNote = request.Note.Trim();
        AddAudit("APPOINTMENT_STATUS_CHANGED", appointment.Id);
        await dbContext.SaveChangesAsync(cancellationToken);
        return await MapAsync(appointment, cancellationToken);
    }

    private async Task<AppointmentDto> TransitionAsync(Guid id, AppointmentStatus from, AppointmentStatus to, AppointmentActionRequest request, CancellationToken cancellationToken)
    {
        var doctor = await RequireDoctorAsync(cancellationToken);
        var appointment = await dbContext.Appointments.SingleOrDefaultAsync(x => x.Id == id && x.DoctorId == doctor.Id, cancellationToken) ?? throw new NotFoundException();
        if (appointment.Status != from)
        {
            throw new ConflictException($"Appointment cannot transition from {appointment.Status} to {to}.");
        }
        appointment.Status = to;
        if (!string.IsNullOrWhiteSpace(request.Note)) appointment.DoctorNote = request.Note.Trim();
        AddAudit("APPOINTMENT_STATUS_CHANGED", appointment.Id);
        await dbContext.SaveChangesAsync(cancellationToken);
        return await MapAsync(appointment, cancellationToken);
    }

    private async Task<Doctor> RequireDoctorAsync(CancellationToken cancellationToken) =>
        await dbContext.Doctors.SingleOrDefaultAsync(x => x.UserId == currentUser.UserId && x.VerificationStatus == Domain.Common.VerificationStatus.Verified, cancellationToken)
            ?? throw new ForbiddenException();

    private async Task<AppointmentDto> MapAsync(Appointment appointment, CancellationToken cancellationToken)
    {
        var member = await dbContext.Members.AsNoTracking().SingleAsync(x => x.Id == appointment.MemberId, cancellationToken);
        var family = await dbContext.Families.AsNoTracking().SingleAsync(x => x.Id == member.FamilyId, cancellationToken);
        var doctor = await dbContext.Doctors.AsNoTracking().Include(x => x.User).SingleAsync(x => x.Id == appointment.DoctorId, cancellationToken);
        var doctorDto = new DoctorSummaryDto(doctor.Id, doctor.User?.DisplayName ?? "Unknown", doctor.Specialty, doctor.HospitalClinic, doctor.District, doctor.City, doctor.Languages);
        return new AppointmentDto(appointment.Id, appointment.MemberId, member.DisplayName, family.Name, doctorDto,
            appointment.StartsAt, appointment.DurationMinutes, appointment.Reason, appointment.Status, appointment.DoctorNote, appointment.CreatedAt);
    }

    private void AddAudit(string eventType, Guid resourceId) => dbContext.AuditLogs.Add(new AuditLog
    {
        ActorUserId = currentUser.UserId,
        EventType = eventType,
        ResourceType = "Appointment",
        ResourceId = resourceId,
        Outcome = "SUCCESS",
        MetadataJson = "{}"
    });

    private void AddNotification(Guid userId, string type, string title, string body, string? linkPath) =>
        dbContext.PortalNotifications.Add(new PortalNotification { UserId = userId, Type = type, Title = title, Body = body, LinkPath = linkPath });
}
