// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using FamilyVeda.Application.Common;
using FamilyVeda.Application.Portal;
using FamilyVeda.Domain.Clinical;
using FamilyVeda.Domain.Common;
using FamilyVeda.Domain.Portal;
using FamilyVeda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace FamilyVeda.Infrastructure.Portal;

public sealed class FamilyDoctorService(AppDbContext dbContext, ICurrentUser currentUser) : IFamilyDoctorService
{
    public async Task<IReadOnlyList<DoctorSummaryDto>> GetDirectoryAsync(string? search, string? district, CancellationToken cancellationToken)
    {
        var query = dbContext.Doctors.AsNoTracking().Where(x => x.VerificationStatus == VerificationStatus.Verified);
        if (!string.IsNullOrWhiteSpace(search))
        {
            var term = search.Trim();
            query = query.Where(x => x.User != null && EF.Functions.ILike(x.User.DisplayName, $"%{term}%"));
        }
        if (!string.IsNullOrWhiteSpace(district))
        {
            var term = district.Trim();
            query = query.Where(x => x.District != null && EF.Functions.ILike(x.District, $"%{term}%"));
        }

        var doctors = await query.Include(x => x.User).OrderBy(x => x.User!.DisplayName).ToListAsync(cancellationToken);
        return doctors.Select(Map).ToList();
    }

    public async Task<DoctorSummaryDto?> GetCurrentAsync(Guid familyId, CancellationToken cancellationToken)
    {
        await RequireMemberAsync(familyId, cancellationToken);
        var assignment = await dbContext.FamilyDoctorAssignments.AsNoTracking()
            .Include(x => x.Doctor).ThenInclude(x => x!.User)
            .Where(x => x.FamilyId == familyId && x.IsPrimary && x.EndedAt == null)
            .FirstOrDefaultAsync(cancellationToken);
        return assignment?.Doctor is null ? null : Map(assignment.Doctor);
    }

    public async Task<DoctorRequestDto> RequestAsync(Guid familyId, CreateDoctorRequest request, CancellationToken cancellationToken)
    {
        await RequireHeadAsync(familyId, cancellationToken);
        var doctor = await dbContext.Doctors.SingleOrDefaultAsync(x => x.Id == request.DoctorId && x.VerificationStatus == VerificationStatus.Verified, cancellationToken)
            ?? throw new NotFoundException();
        if (await dbContext.FamilyDoctorRequests.AnyAsync(x => x.FamilyId == familyId && x.Status == PortalRequestStatus.Pending, cancellationToken))
        {
            throw new ConflictException("A pending doctor request already exists for this family.");
        }

        var doctorRequest = new FamilyDoctorRequest
        {
            FamilyId = familyId,
            DoctorId = doctor.Id,
            RequestedByUserId = currentUser.UserId,
            Message = request.Message?.Trim()
        };
        dbContext.FamilyDoctorRequests.Add(doctorRequest);
        AddAudit("FAMILY_DOCTOR_REQUESTED", doctorRequest.Id);
        AddNotification(doctor.UserId, "FAMILY_DOCTOR_REQUESTED", "New family request", "A family has requested you as their family doctor.", "/doctor/requests");
        await dbContext.SaveChangesAsync(cancellationToken);
        return await MapRequestAsync(doctorRequest, cancellationToken);
    }

    public async Task<IReadOnlyList<DoctorRequestDto>> GetMyRequestsAsync(CancellationToken cancellationToken)
    {
        var doctor = await RequireDoctorAsync(cancellationToken);
        var requests = await dbContext.FamilyDoctorRequests.AsNoTracking()
            .Where(x => x.DoctorId == doctor.Id && x.Status == PortalRequestStatus.Pending)
            .OrderByDescending(x => x.CreatedAt)
            .ToListAsync(cancellationToken);
        var results = new List<DoctorRequestDto>();
        foreach (var request in requests)
        {
            results.Add(await MapRequestAsync(request, cancellationToken));
        }
        return results;
    }

    public async Task<DoctorRequestDto> AcceptAsync(Guid id, CancellationToken cancellationToken)
    {
        var doctor = await RequireDoctorAsync(cancellationToken);
        var request = await dbContext.FamilyDoctorRequests.SingleOrDefaultAsync(x => x.Id == id && x.DoctorId == doctor.Id, cancellationToken)
            ?? throw new NotFoundException();
        if (request.Status != PortalRequestStatus.Pending)
        {
            throw new ConflictException("This request has already been resolved.");
        }

        var current = await dbContext.FamilyDoctorAssignments
            .Where(x => x.FamilyId == request.FamilyId && x.IsPrimary && x.EndedAt == null)
            .ToListAsync(cancellationToken);
        foreach (var assignment in current)
        {
            assignment.EndedAt = DateTimeOffset.UtcNow;
        }

        dbContext.FamilyDoctorAssignments.Add(new FamilyDoctorAssignment { FamilyId = request.FamilyId, DoctorId = doctor.Id, IsPrimary = true });
        request.Status = PortalRequestStatus.Accepted;
        request.RespondedAt = DateTimeOffset.UtcNow;
        AddAudit("FAMILY_DOCTOR_ACCEPTED", request.Id);
        var family = await dbContext.Families.AsNoTracking().SingleAsync(x => x.Id == request.FamilyId, cancellationToken);
        AddNotification(family.CreatedByUserId, "FAMILY_DOCTOR_ACCEPTED", "Family doctor confirmed", "Your family doctor request was accepted.", "/family/doctor");
        await dbContext.SaveChangesAsync(cancellationToken);
        return await MapRequestAsync(request, cancellationToken);
    }

    public async Task<DoctorRequestDto> DeclineAsync(Guid id, CancellationToken cancellationToken)
    {
        var doctor = await RequireDoctorAsync(cancellationToken);
        var request = await dbContext.FamilyDoctorRequests.SingleOrDefaultAsync(x => x.Id == id && x.DoctorId == doctor.Id, cancellationToken)
            ?? throw new NotFoundException();
        if (request.Status != PortalRequestStatus.Pending)
        {
            throw new ConflictException("This request has already been resolved.");
        }

        request.Status = PortalRequestStatus.Declined;
        request.RespondedAt = DateTimeOffset.UtcNow;
        AddAudit("FAMILY_DOCTOR_DECLINED", request.Id);
        var family = await dbContext.Families.AsNoTracking().SingleAsync(x => x.Id == request.FamilyId, cancellationToken);
        AddNotification(family.CreatedByUserId, "FAMILY_DOCTOR_DECLINED", "Family doctor request declined", "The doctor declined your family doctor request.", "/family/doctor");
        await dbContext.SaveChangesAsync(cancellationToken);
        return await MapRequestAsync(request, cancellationToken);
    }

    private async Task RequireHeadAsync(Guid familyId, CancellationToken cancellationToken)
    {
        if (!await dbContext.Families.AnyAsync(x => x.Id == familyId && x.CreatedByUserId == currentUser.UserId, cancellationToken))
        {
            throw new NotFoundException();
        }
    }

    private async Task RequireMemberAsync(Guid familyId, CancellationToken cancellationToken)
    {
        if (!await dbContext.Families.AnyAsync(x => x.Id == familyId && (x.CreatedByUserId == currentUser.UserId || x.Members.Any(m => m.UserId == currentUser.UserId)), cancellationToken))
        {
            throw new NotFoundException();
        }
    }

    private async Task<Doctor> RequireDoctorAsync(CancellationToken cancellationToken) =>
        await dbContext.Doctors.SingleOrDefaultAsync(x => x.UserId == currentUser.UserId && x.VerificationStatus == VerificationStatus.Verified, cancellationToken)
            ?? throw new ForbiddenException();

    private async Task<DoctorRequestDto> MapRequestAsync(FamilyDoctorRequest request, CancellationToken cancellationToken)
    {
        var family = await dbContext.Families.AsNoTracking().Include(x => x.Members).SingleAsync(x => x.Id == request.FamilyId, cancellationToken);
        var doctor = await dbContext.Doctors.AsNoTracking().Include(x => x.User).SingleAsync(x => x.Id == request.DoctorId, cancellationToken);
        return new DoctorRequestDto(request.Id, request.FamilyId, family.Name, family.Members.Count, Map(doctor), request.Message, request.Status, request.CreatedAt);
    }

    private static DoctorSummaryDto Map(Doctor doctor) =>
        new(doctor.Id, doctor.User?.DisplayName ?? "Unknown", doctor.Specialty, doctor.HospitalClinic, doctor.District, doctor.City, doctor.Languages);

    private void AddAudit(string eventType, Guid resourceId) => dbContext.AuditLogs.Add(new AuditLog
    {
        ActorUserId = currentUser.UserId,
        EventType = eventType,
        ResourceType = "FamilyDoctorRequest",
        ResourceId = resourceId,
        Outcome = "SUCCESS",
        MetadataJson = "{}"
    });

    private void AddNotification(Guid userId, string type, string title, string body, string? linkPath) =>
        dbContext.PortalNotifications.Add(new PortalNotification { UserId = userId, Type = type, Title = title, Body = body, LinkPath = linkPath });
}
