// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import { useCallback, useEffect, useMemo, useState } from 'react'

import { EmptyState, ErrorState, LoadingState } from '../../components/shared/ViewState'
import { StatusBadge } from '../../components/shared/StatusBadge'
import { apiClient, type FamilyHeadDto, type PagedResult } from '../../services/apiClient'

type FilterStatus = 'ALL' | 'PENDING' | 'VERIFIED' | 'MORE_INFO' | 'REJECTED' | 'SUSPENDED'

export function FamilyHeadVerificationPage() {
  const [familyHeads, setFamilyHeads] = useState<FamilyHeadDto[]>([])
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading')
  const [message, setMessage] = useState('')
  const [search, setSearch] = useState('')
  const [activeFilter, setActiveFilter] = useState<FilterStatus>('ALL')

  const load = useCallback(async () => {
    setStatus('loading')
    try {
      const response = await apiClient.get<PagedResult<FamilyHeadDto>>('/admin/family-heads', {
        params: { page: 1, pageSize: 100 },
      })
      setFamilyHeads(response.data.items)
      setStatus('ready')
    } catch {
      setStatus('error')
    }
  }, [])

  useEffect(() => {
    void load()
  }, [load])

  async function decide(userId: string, action: 'verify' | 'request-info' | 'reject' | 'suspend') {
    const reason = window.prompt('Audit reason (no clinical content):')
    if (reason === null) return
    try {
      await apiClient.post(`/admin/family-heads/${userId}/${action}`, { reason })
      setMessage('Family head verification status updated and audited.')
      await load()
    } catch {
      setMessage('Verification status could not be updated.')
    }
  }

  const filteredHeads = useMemo(() => {
    return familyHeads.filter((head) => {
      const matchesSearch =
        search.trim() === '' ||
        head.displayName.toLowerCase().includes(search.toLowerCase()) ||
        head.email.toLowerCase().includes(search.toLowerCase()) ||
        head.familyName.toLowerCase().includes(search.toLowerCase())

      if (!matchesSearch) return false

      const s = head.verificationStatus?.toUpperCase() ?? 'PENDING'
      switch (activeFilter) {
        case 'PENDING':
          return s === 'PENDING'
        case 'VERIFIED':
          return s === 'VERIFIED'
        case 'MORE_INFO':
          return s === 'MOREINFORMATIONREQUIRED' || s === 'MORE_INFORMATION_REQUIRED'
        case 'REJECTED':
          return s === 'REJECTED'
        case 'SUSPENDED':
          return s === 'SUSPENDED'
        default:
          return true
      }
    })
  }, [familyHeads, search, activeFilter])

  const pendingCount = familyHeads.filter((h) => (h.verificationStatus?.toUpperCase() ?? 'PENDING') === 'PENDING').length
  const verifiedCount = familyHeads.filter((h) => h.verificationStatus?.toUpperCase() === 'VERIFIED').length

  return (
    <div className="page-stack">
      <header className="page-header">
        <div>
          <p className="eyebrow">Clinic administration</p>
          <h1>Family head verification</h1>
          <p>Manual administrative verification of family heads and workspaces; no external registration API is claimed.</p>
        </div>
      </header>

      {message && <p role="status" className="status-banner">{message}</p>}

      <section className="panel">
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
          <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
            <button
              type="button"
              className={`button button--sm ${activeFilter === 'ALL' ? 'button--primary' : 'button--secondary'}`}
              onClick={() => setActiveFilter('ALL')}
            >
              All ({familyHeads.length})
            </button>
            <button
              type="button"
              className={`button button--sm ${activeFilter === 'PENDING' ? 'button--primary' : 'button--secondary'}`}
              onClick={() => setActiveFilter('PENDING')}
            >
              Pending ({pendingCount})
            </button>
            <button
              type="button"
              className={`button button--sm ${activeFilter === 'VERIFIED' ? 'button--primary' : 'button--secondary'}`}
              onClick={() => setActiveFilter('VERIFIED')}
            >
              Verified ({verifiedCount})
            </button>
            <button
              type="button"
              className={`button button--sm ${activeFilter === 'MORE_INFO' ? 'button--primary' : 'button--secondary'}`}
              onClick={() => setActiveFilter('MORE_INFO')}
            >
              More info
            </button>
            <button
              type="button"
              className={`button button--sm ${activeFilter === 'SUSPENDED' ? 'button--primary' : 'button--secondary'}`}
              onClick={() => setActiveFilter('SUSPENDED')}
            >
              Suspended
            </button>
            <button
              type="button"
              className={`button button--sm ${activeFilter === 'REJECTED' ? 'button--primary' : 'button--secondary'}`}
              onClick={() => setActiveFilter('REJECTED')}
            >
              Rejected
            </button>
          </div>

          <div style={{ minWidth: '220px' }}>
            <input
              type="search"
              placeholder="Search family head or email…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              style={{ width: '100%', padding: '6px 12px', fontSize: '0.85rem' }}
            />
          </div>
        </div>

        {status === 'loading' ? (
          <LoadingState label="Loading family heads queue" />
        ) : status === 'error' ? (
          <ErrorState message="Family heads queue could not be loaded." onRetry={() => void load()} />
        ) : filteredHeads.length === 0 ? (
          <EmptyState
            title={search || activeFilter !== 'ALL' ? 'No matching family heads' : 'No family heads registered'}
            message={search || activeFilter !== 'ALL' ? 'Try changing your search query or status filter.' : 'New family head registrations appear here for manual review.'}
          />
        ) : (
          <div className="table-scroll">
            <table>
              <thead>
                <tr>
                  <th>Family head</th>
                  <th>Email</th>
                  <th>Workspace</th>
                  <th>Members</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredHeads.map((head) => {
                  const s = head.verificationStatus?.toUpperCase()
                  const isVerified = s === 'VERIFIED'
                  const isSuspendedOrRejected = s === 'SUSPENDED' || s === 'REJECTED'

                  return (
                    <tr key={head.userId}>
                      <td>
                        <strong>{head.displayName}</strong>
                      </td>
                      <td>{head.email}</td>
                      <td>
                        {head.familyName === 'Pending Setup' ? (
                          <span className="muted" style={{ fontStyle: 'italic' }}>Pending workspace</span>
                        ) : (
                          head.familyName
                        )}
                      </td>
                      <td>{head.memberCount}</td>
                      <td>
                        <StatusBadge status={head.verificationStatus} />
                      </td>
                      <td>
                        <div className="table-actions">
                          {!isVerified && (
                            <button
                              className="button button--primary button--sm"
                              onClick={() => void decide(head.userId, 'verify')}
                              title="Verify this family head"
                            >
                              Verify
                            </button>
                          )}
                          {!isSuspendedOrRejected && (
                            <button
                              className="button button--secondary button--sm"
                              onClick={() => void decide(head.userId, 'request-info')}
                              title="Request additional information"
                            >
                              Request info
                            </button>
                          )}
                          {!isSuspendedOrRejected && (
                            <button
                              className="button button--danger button--sm"
                              onClick={() => void decide(head.userId, 'reject')}
                              title="Reject registration"
                            >
                              Reject
                            </button>
                          )}
                          {!isSuspendedOrRejected ? (
                            <button
                              className="button button--secondary button--sm"
                              onClick={() => void decide(head.userId, 'suspend')}
                              title="Suspend account access"
                            >
                              Suspend
                            </button>
                          ) : (
                            <button
                              className="button button--primary button--sm"
                              onClick={() => void decide(head.userId, 'verify')}
                              title="Reactivate and verify account"
                            >
                              Reactivate
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  )
}
