// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// Appointment details: side drawer on desktop, bottom sheet on phones. Only the actions the status allows
// are offered, and nothing is shown as done until the backend has answered.
import { useEffect, useRef, useState, type KeyboardEvent } from 'react'
import { Link } from 'react-router-dom'

import { doctorWorkspaceApi, threePortalApi, type AppointmentDto } from '../../../services/apiClient'
import { extractErrorMessage } from '../../family/threePortalUtils'
import { StatusChip } from './CalendarViews'
import { allowedActions, canReschedule, endsAt, formatLongDay, formatTime, initials, toLocalInputValue, type AppointmentAction } from './calendarUtils'

type Step = AppointmentAction | 'reschedule' | null

const primaryLabel: Record<AppointmentAction, string> = {
  confirm: 'Confirm appointment',
  complete: 'Complete visit',
  'no-show': 'Mark no-show',
  cancel: 'Cancel appointment',
}

const confirmCopy: Record<Exclude<AppointmentAction, 'confirm'>, { question: string; yes: string }> = {
  complete: { question: 'Mark this visit as completed? This cannot be undone.', yes: 'Yes, complete visit' },
  'no-show': { question: 'Mark this visit as a no-show? Access granted for the visit is withdrawn.', yes: 'Yes, mark no-show' },
  cancel: { question: 'Cancel this appointment? The family will see it as cancelled.', yes: 'Yes, cancel appointment' },
}

const doneMessage: Record<AppointmentAction, string> = {
  confirm: 'confirmed',
  complete: 'marked as completed',
  'no-show': 'marked as a no-show',
  cancel: 'cancelled',
}

const focusable = 'button:not([disabled]), a[href], input:not([disabled]), textarea:not([disabled])'

export function AppointmentDrawer({ appointment, onClose, onUpdated }: {
  appointment: AppointmentDto
  onClose: () => void
  onUpdated: (appointment: AppointmentDto, message: string) => void
}) {
  const [step, setStep] = useState<Step>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [note, setNote] = useState('')
  const [newTime, setNewTime] = useState('')
  const panelRef = useRef<HTMLDivElement>(null)
  const closeRef = useRef<HTMLButtonElement>(null)

  useEffect(() => {
    closeRef.current?.focus()
  }, [])

  // On the document, so Escape still closes the drawer after a click on its non-focusable text.
  useEffect(() => {
    const onEscape = (event: globalThis.KeyboardEvent) => {
      if (event.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', onEscape)
    return () => document.removeEventListener('keydown', onEscape)
  }, [onClose])

  const start = new Date(appointment.startsAt)
  const actions = allowedActions[appointment.status] ?? []
  const primary = actions.find((action) => action === 'confirm' || action === 'complete')
  const reschedulable = canReschedule(appointment.status)

  const reset = () => {
    setStep(null)
    setError('')
    setNote('')
    setNewTime('')
  }

  const run = async (action: AppointmentAction) => {
    if (busy) return
    setBusy(true)
    setError('')
    try {
      const { data } = await threePortalApi.setAppointmentStatus(appointment.id, action, note.trim() || undefined)
      reset()
      onUpdated(data, `${appointment.memberDisplayName}'s appointment ${doneMessage[action]}.`)
    } catch (err) {
      setError(extractErrorMessage(err, 'The appointment was not changed. Try again.'))
    } finally {
      setBusy(false)
    }
  }

  const reschedule = async () => {
    if (busy || !newTime) return
    const target = new Date(newTime)
    if (Number.isNaN(target.getTime()) || target.getTime() <= Date.now()) {
      setError('Pick a date and time in the future.')
      return
    }
    setBusy(true)
    setError('')
    try {
      const { data } = await doctorWorkspaceApi.reschedule(appointment.id, target.toISOString(), note.trim() || undefined)
      reset()
      onUpdated(data, `${appointment.memberDisplayName}'s appointment moved. The family has been notified.`)
    } catch (err) {
      setError(extractErrorMessage(err, 'The appointment was not moved. Try again.'))
    } finally {
      setBusy(false)
    }
  }

  const onKeyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key !== 'Tab') return
    const items = panelRef.current?.querySelectorAll<HTMLElement>(focusable)
    if (!items || items.length === 0) return
    const first = items[0]
    const last = items[items.length - 1]
    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault()
      last.focus()
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault()
      first.focus()
    }
  }

  return (
    <div className="dcal-overlay" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}>
      <div ref={panelRef} className="dcal-drawer" role="dialog" aria-modal="true" aria-labelledby="dcal-drawer-title" onKeyDown={onKeyDown}>
        <header className="dcal-drawer-head">
          <h2 id="dcal-drawer-title">Appointment details</h2>
          <button ref={closeRef} type="button" className="dcal-icon-btn" aria-label="Close appointment details" onClick={onClose}>×</button>
        </header>

        <div className="dcal-drawer-body">
          <div className="dcal-patient">
            <span className="dcal-avatar" aria-hidden="true">{initials(appointment.memberDisplayName)}</span>
            <div className="dcal-patient-text">
              <strong>{appointment.memberDisplayName}</strong>
              <span>{appointment.familyName}</span>
            </div>
            <StatusChip status={appointment.status} />
          </div>

          <dl className="dcal-details">
            <div><dt>Date</dt><dd>{formatLongDay(start)}</dd></div>
            <div><dt>Time</dt><dd>{formatTime(start)} – {formatTime(endsAt(appointment))} ({appointment.durationMinutes} min)</dd></div>
            <div><dt>Doctor</dt><dd>{appointment.doctor.displayName}</dd></div>
            <div><dt>Reference</dt><dd className="dcal-ref">{appointment.id.slice(0, 8)}</dd></div>
          </dl>

          <section className="dcal-reason" aria-label="Reason for visit">
            <h3>Reason for visit</h3>
            <p>{appointment.reason}</p>
          </section>

          {appointment.doctorNote && (
            <section className="dcal-reason" aria-label="Your note">
              <h3>Your note</h3>
              <p>{appointment.doctorNote}</p>
            </section>
          )}

          <p className="dcal-access-note">
            <Link to={`/members/${appointment.memberId}`}>Open member workspace</Link>
            <span>Clinical records open only while a visit or case grant and the member's consent allow it.</span>
          </p>
        </div>

        <footer className="dcal-drawer-foot">
          {error && <p className="dcal-error" role="alert">{error}</p>}

          {step === null && actions.length === 0 && !reschedulable && (
            <p className="dcal-readonly">This appointment is closed. No further changes are available.</p>
          )}

          {step === null && (actions.length > 0 || reschedulable) && (
            <>
              <div className="dcal-actions">
                {primary && (
                  <button type="button" className="button button--primary" disabled={busy} onClick={() => (primary === 'confirm' ? void run('confirm') : setStep(primary))}>
                    {busy ? 'Saving…' : primaryLabel[primary]}
                  </button>
                )}
                {reschedulable && (
                  <button type="button" className="button button--secondary" disabled={busy} onClick={() => { setError(''); setNewTime(toLocalInputValue(start)); setStep('reschedule') }}>
                    Reschedule
                  </button>
                )}
              </div>
              <div className="dcal-text-actions">
                {actions.includes('no-show') && (
                  <button type="button" className="dcal-link dcal-link--warning" disabled={busy} onClick={() => { setError(''); setStep('no-show') }}>Mark no-show</button>
                )}
                {actions.includes('cancel') && (
                  <button type="button" className="dcal-link dcal-link--danger" disabled={busy} onClick={() => { setError(''); setStep('cancel') }}>Cancel appointment</button>
                )}
              </div>
            </>
          )}

          {step !== null && step !== 'reschedule' && step !== 'confirm' && (
            <div className="dcal-confirm" role="group" aria-label={primaryLabel[step]}>
              <p>{confirmCopy[step].question}</p>
              {step === 'cancel' && (
                <label className="dcal-field">
                  <span>Note for your records (optional)</span>
                  <textarea value={note} maxLength={500} rows={2} onChange={(event) => setNote(event.target.value)} />
                </label>
              )}
              <div className="dcal-actions">
                <button type="button" className="button button--secondary" disabled={busy} onClick={reset}>Go back</button>
                <button type="button" className={`button ${step === 'complete' ? 'button--primary' : 'button--danger'}`} disabled={busy} onClick={() => void run(step)}>
                  {busy ? 'Saving…' : confirmCopy[step].yes}
                </button>
              </div>
            </div>
          )}

          {step === 'reschedule' && (
            <div className="dcal-confirm" role="group" aria-label="Reschedule appointment">
              <label className="dcal-field">
                <span>New date and time</span>
                <input type="datetime-local" value={newTime} min={toLocalInputValue(new Date())} onChange={(event) => setNewTime(event.target.value)} />
              </label>
              <p className="dcal-hint">The time is checked against your working hours, blocked time and other appointments when you save.</p>
              <div className="dcal-actions">
                <button type="button" className="button button--secondary" disabled={busy} onClick={reset}>Go back</button>
                <button type="button" className="button button--primary" disabled={busy || !newTime} onClick={() => void reschedule()}>
                  {busy ? 'Saving…' : 'Move appointment'}
                </button>
              </div>
            </div>
          )}
        </footer>
      </div>
    </div>
  )
}
