// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using Microsoft.AspNetCore.Mvc;

namespace FamilyVeda.Api.Middleware;

/// <summary>
/// Request and response hardening found necessary by the OWASP ZAP API scan of 2026-10-05:
/// every response tells the browser not to sniff the content type, and a query string that
/// carries a NUL character is rejected as a client error before it can reach PostgreSQL,
/// which cannot store that character in text and would otherwise surface as a 500.
/// </summary>
public sealed class RequestHardeningMiddleware(RequestDelegate next)
{
    public async Task InvokeAsync(HttpContext context)
    {
        context.Response.Headers.XContentTypeOptions = "nosniff";

        var query = context.Request.QueryString.Value;
        if (!string.IsNullOrEmpty(query)
            && (query.Contains("%00", StringComparison.Ordinal) || query.Contains('\0')))
        {
            var problem = new ProblemDetails
            {
                Status = StatusCodes.Status400BadRequest,
                Title = "Validation failed",
                Detail = "The query string contains a character that is not allowed.",
                Instance = context.Request.Path
            };
            problem.Extensions["traceId"] = context.TraceIdentifier;
            context.Response.StatusCode = StatusCodes.Status400BadRequest;
            await context.Response.WriteAsJsonAsync(problem, options: null, contentType: "application/problem+json");
            return;
        }

        await next(context);
    }
}
