// Owner: S2 · Health Records & Extraction — Fernando K.R.N (IT24101875)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using System.Diagnostics;
using FamilyVeda.Application.Common;
using FamilyVeda.Application.Records;
using Microsoft.Extensions.Configuration;

namespace FamilyVeda.Infrastructure.Records;

public sealed class TesseractOcrService(IConfiguration configuration) : IOcrService
{
    private readonly SemaphoreSlim _processSlots = new(Math.Clamp(configuration.GetValue("Ocr:MaxConcurrentProcesses", 2), 1, 4));

    public async Task<string> ExtractTextAsync(string filePath, CancellationToken cancellationToken)
    {
        await _processSlots.WaitAsync(cancellationToken);
        try
        {
            var startInfo = new ProcessStartInfo
            {
                FileName = "tesseract",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };
            startInfo.ArgumentList.Add(filePath);
            startInfo.ArgumentList.Add("stdout");
            startInfo.ArgumentList.Add("-l");
            startInfo.ArgumentList.Add("eng");
            var dataPath = configuration["Ocr:TesseractDataPath"];
            if (!string.IsNullOrWhiteSpace(dataPath))
            {
                startInfo.ArgumentList.Add("--tessdata-dir");
                startInfo.ArgumentList.Add(dataPath);
            }
            using var process = Process.Start(startInfo) ?? throw new ProcessingException("OCR engine could not be started. Use manual entry instead.");
            using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            timeout.CancelAfter(TimeSpan.FromSeconds(configuration.GetValue("Ocr:TimeoutSeconds", 30)));
            string output;
            try
            {
                var outputTask = process.StandardOutput.ReadToEndAsync(timeout.Token);
                var errorTask = process.StandardError.ReadToEndAsync(timeout.Token);
                await process.WaitForExitAsync(timeout.Token);
                output = await outputTask;
                await errorTask;
            }
            catch (OperationCanceledException)
            {
                if (!process.HasExited)
                {
                    process.Kill(entireProcessTree: true);
                    await process.WaitForExitAsync(CancellationToken.None);
                }
                if (cancellationToken.IsCancellationRequested) throw;
                throw new ProcessingException("OCR timed out. Use manual entry instead.");
            }
            if (process.ExitCode != 0 || string.IsNullOrWhiteSpace(output))
                throw new ProcessingException("OCR could not read this report. Use manual entry instead.");
            if (output.Length > configuration.GetValue("Ocr:MaxOutputCharacters", 250_000))
                throw new ProcessingException("OCR output exceeded safe limits. Use manual entry instead.");
            return output;
        }
        finally
        {
            _processSlots.Release();
        }
    }
}
