// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using FamilyVeda.Application.Common;
using FamilyVeda.Application.Families;
using FamilyVeda.Domain.Common;
using FamilyVeda.Domain.Identity;
using FamilyVeda.Infrastructure.Families;
using FamilyVeda.Infrastructure.Persistence;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;

namespace FamilyVeda.UnitTests;

public sealed class FamilyServicePrivacyTests
{
    [Fact]
    public async Task InvitedAdult_CanJoinOnlyWithMatchingAccountEmail_AndOneTimeToken()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
        await using var db = new AppDbContext(options);
        var headUser = User("synthetic-invite-head@example.invalid");
        var adultUser = User("synthetic-invited-adult@example.invalid");
        var family = new Family { Name = "Synthetic Invitation Family", CreatedByUser = headUser };
        db.AddRange(headUser, adultUser, family);
        await db.SaveChangesAsync();
        var headService = new FamilyService(db, new StubCurrentUser(headUser.Id));
        var invitation = await headService.CreateInvitationAsync(family.Id,
            new CreateFamilyInvitationRequest(adultUser.Email), CancellationToken.None);
        var adultService = new FamilyService(db, new StubCurrentUser(adultUser.Id));

        var joined = await adultService.AcceptInvitationAsync(
            new AcceptFamilyInvitationRequest(invitation.Token, new DateOnly(1990, 1, 1)), CancellationToken.None);
        var replay = () => adultService.AcceptInvitationAsync(
            new AcceptFamilyInvitationRequest(invitation.Token, new DateOnly(1990, 1, 1)), CancellationToken.None);

        joined.Role.Should().Be(FamilyRole.AdultMember);
        joined.FamilyId.Should().Be(family.Id);
        (await db.Consents.CountAsync(x => x.MemberId == joined.Id)).Should().Be(Enum.GetValues<ConsentCategory>().Length);
        await replay.Should().ThrowAsync<ConflictException>();
        (await db.AuditLogs.CountAsync(x => x.EventType == "FAMILY_INVITATION_ACCEPTED")).Should().Be(1);
    }

    [Fact]
    public async Task FamilyHead_CannotCreateAnUnlinkedAdultProfile()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
        await using var db = new AppDbContext(options);
        var headUser = User("synthetic-head-create@example.invalid");
        var family = new Family { Name = "Synthetic Family", CreatedByUser = headUser };
        db.AddRange(headUser, family);
        await db.SaveChangesAsync();
        var service = new FamilyService(db, new StubCurrentUser(headUser.Id));

        var addAdult = () => service.AddMemberAsync(
            family.Id,
            new CreateMemberRequest("Synthetic Adult", new DateOnly(1990, 1, 1), FamilyRole.AdultMember, null),
            CancellationToken.None);

        await addAdult.Should().ThrowAsync<FamilyVeda.Application.Common.ValidationException>();
        (await db.Members.CountAsync()).Should().Be(0);
    }

    [Fact]
    public async Task FamilyHead_CannotListUpdateOrDeleteAnotherAdult()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
        await using var db = new AppDbContext(options);
        var headUser = User("synthetic-head@example.invalid");
        var adultUser = User("synthetic-adult@example.invalid");
        var family = new Family { Name = "Synthetic Family", CreatedByUser = headUser };
        var head = Member(family, headUser, "Synthetic Head", new DateOnly(1980, 1, 1), FamilyRole.Head);
        var adult = Member(family, adultUser, "Synthetic Adult", new DateOnly(1990, 1, 1), FamilyRole.AdultMember);
        var minor = Member(family, null, "Synthetic Minor", DateOnly.FromDateTime(DateTime.UtcNow).AddYears(-10), FamilyRole.MinorMember);
        db.AddRange(headUser, adultUser, family, head, adult, minor);
        await db.SaveChangesAsync();
        var service = new FamilyService(db, new StubCurrentUser(headUser.Id));

        var visible = await service.GetMineAsync(CancellationToken.None);
        var update = () => service.UpdateMemberAsync(adult.Id,
            new UpdateMemberRequest("Changed", DateOnly.FromDateTime(DateTime.UtcNow).AddYears(-10), FamilyRole.MinorMember),
            CancellationToken.None);
        var delete = () => service.DeleteMemberAsync(adult.Id, CancellationToken.None);

        visible!.Members.Select(x => x.Id).Should().BeEquivalentTo([head.Id, minor.Id]);
        await update.Should().ThrowAsync<NotFoundException>();
        await delete.Should().ThrowAsync<NotFoundException>();
    }

    [Fact]
    public async Task UpdateConsent_WhenStateChanges_WritesConsentAudit()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
        await using var db = new AppDbContext(options);
        var user = User("synthetic-consent-update@example.invalid");
        var family = new Family { Name = "Synthetic Consent Family", CreatedByUser = user };
        var member = Member(family, user, "Synthetic Adult", new DateOnly(1990, 1, 1), FamilyRole.Head);
        var consent = new Consent { Member = member, Category = ConsentCategory.Conditions, Status = ConsentStatus.NotSet };
        db.AddRange(user, family, member, consent);
        await db.SaveChangesAsync();
        var service = new FamilyService(db, new StubCurrentUser(user.Id));

        await service.UpdateConsentAsync(member.Id, ConsentCategory.Conditions, new UpdateConsentRequest(ConsentStatus.Granted), CancellationToken.None);

        var audit = await db.AuditLogs.SingleAsync();
        audit.EventType.Should().Be("CONSENT_UPDATED");
        audit.ActorUserId.Should().Be(user.Id);
        audit.SubjectMemberId.Should().Be(member.Id);
        audit.ResourceType.Should().Be("Consent");
        audit.ResourceId.Should().Be(consent.Id);
        audit.Outcome.Should().Be("SUCCESS");
    }

    [Fact]
    public async Task ReaffirmConsents_WhenAdultReaffirms_WritesOneAuditPerConsent()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
        await using var db = new AppDbContext(options);
        var user = User("synthetic-consent-reaffirm@example.invalid");
        var family = new Family { Name = "Synthetic Reaffirmation Family", CreatedByUser = user };
        var member = Member(family, user, "Synthetic Adult", new DateOnly(1990, 1, 1), FamilyRole.Head);
        var conditions = new Consent { Member = member, Category = ConsentCategory.Conditions, Status = ConsentStatus.PendingReaffirmation, GrantedByGuardian = true };
        var vitals = new Consent { Member = member, Category = ConsentCategory.VitalsSummary, Status = ConsentStatus.PendingReaffirmation, GrantedByGuardian = true };
        db.AddRange(user, family, member, conditions, vitals);
        await db.SaveChangesAsync();
        var service = new FamilyService(db, new StubCurrentUser(user.Id));

        await service.ReaffirmConsentsAsync(member.Id, CancellationToken.None);

        var audits = await db.AuditLogs.OrderBy(x => x.ResourceId).ToListAsync();
        audits.Should().HaveCount(2);
        audits.Should().OnlyContain(x =>
            x.EventType == "CONSENT_REAFFIRMED" &&
            x.ActorUserId == user.Id &&
            x.SubjectMemberId == member.Id &&
            x.ResourceType == "Consent" &&
            x.Outcome == "SUCCESS");
        audits.Select(x => x.ResourceId).Should().BeEquivalentTo([conditions.Id, vitals.Id]);
    }

    [Fact]
    public async Task GetConsents_WhenGuardianConsentCrossesAdultBoundary_WritesTransitionAudit()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
        await using var db = new AppDbContext(options);
        var user = User("synthetic-age-transition@example.invalid");
        var family = new Family { Name = "Synthetic Age Transition Family", CreatedByUser = user };
        var member = Member(family, user, "Synthetic Adult", DateOnly.FromDateTime(DateTime.UtcNow).AddYears(-18), FamilyRole.Head);
        var consent = new Consent
        {
            Member = member,
            Category = ConsentCategory.HereditaryFlags,
            Status = ConsentStatus.Granted,
            GrantedByGuardian = true,
            GrantedByUserId = user.Id,
            GrantedAt = DateTimeOffset.UtcNow.AddYears(-1)
        };
        db.AddRange(user, family, member, consent);
        await db.SaveChangesAsync();
        var service = new FamilyService(db, new StubCurrentUser(user.Id));

        await service.GetConsentsAsync(member.Id, CancellationToken.None);

        (await db.Consents.SingleAsync(x => x.Id == consent.Id)).Status.Should().Be(ConsentStatus.PendingReaffirmation);
        var audit = await db.AuditLogs.SingleAsync();
        audit.EventType.Should().Be("CONSENT_REAFFIRMATION_REQUIRED");
        audit.ActorUserId.Should().Be(user.Id);
        audit.SubjectMemberId.Should().Be(member.Id);
        audit.ResourceType.Should().Be("Consent");
        audit.ResourceId.Should().Be(consent.Id);
        audit.Outcome.Should().Be("SUCCESS");
    }

    private static UserAccount User(string email) => new()
    {
        Email = email,
        PasswordHash = "synthetic",
        DisplayName = "Synthetic User",
        UserType = UserType.FamilyUser
    };

    private static Member Member(Family family, UserAccount? user, string name, DateOnly dateOfBirth, FamilyRole role) => new()
    {
        Family = family,
        User = user,
        DisplayName = name,
        DateOfBirth = dateOfBirth,
        Role = role
    };

    private sealed class StubCurrentUser(Guid userId) : ICurrentUser
    {
        public bool IsAuthenticated => true;
        public Guid UserId => userId;
        public UserType UserType => UserType.FamilyUser;
    }
}
