// Owner: S3 · Triage & Agent Orchestration — Karunathilaka K.D.J.C (IT24100551)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using FamilyVeda.Application.Agents;
using Microsoft.Extensions.Options;

namespace FamilyVeda.Infrastructure.Agents;

/// <summary>
/// Hosted inference settings. Provider "ollama" keeps the local OllamaClient;
/// "openai-compatible" (e.g. Groq) uses <see cref="ChatCompletionsLlmClient"/>.
/// The API key is read from server configuration only and never logged.
/// </summary>
public sealed class LlmOptions
{
    public const string SectionName = "Llm";
    public const string OpenAiCompatible = "openai-compatible";
    public string Provider { get; init; } = "ollama";
    public string BaseUrl { get; init; } = "https://api.groq.com/openai/v1";
    public string Model { get; init; } = "llama-3.1-8b-instant";
    public string ApiKey { get; init; } = "";
    public int TimeoutSeconds { get; init; } = 30;
}

public sealed class ChatCompletionsLlmClient(HttpClient httpClient, IOptions<LlmOptions> options) : IOllamaClient
{
    private readonly LlmOptions _options = options.Value;
    private static readonly JsonSerializerOptions RequestJson = new(JsonSerializerDefaults.Web);
    private static readonly JsonSerializerOptions OutputJson = new(JsonSerializerDefaults.Web)
    {
        PropertyNameCaseInsensitive = true,
        UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow
    };

    public async Task<OllamaResult<T>> GenerateStructuredAsync<T>(string systemPrompt, object input, CancellationToken cancellationToken) where T : class
    {
        Exception? lastError = null;
        for (var attempt = 0; attempt < 2; attempt++)
        {
            try
            {
                using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
                timeout.CancelAfter(TimeSpan.FromSeconds(_options.TimeoutSeconds));
                using var request = new HttpRequestMessage(HttpMethod.Post, "chat/completions")
                {
                    Content = JsonContent.Create(new
                    {
                        model = _options.Model,
                        temperature = 0,
                        response_format = new { type = "json_object" },
                        messages = new object[]
                        {
                            new { role = "system", content = systemPrompt + "\nRespond with a single JSON object only." },
                            new { role = "user", content = JsonSerializer.Serialize(input, RequestJson) }
                        }
                    }, options: RequestJson)
                };
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _options.ApiKey);

                using var response = await httpClient.SendAsync(request, timeout.Token);
                response.EnsureSuccessStatusCode();
                var envelope = await response.Content.ReadFromJsonAsync<ChatEnvelope>(RequestJson, timeout.Token)
                    ?? throw new JsonException("LLM returned an empty response.");
                var content = envelope.Choices?.FirstOrDefault()?.Message?.Content
                    ?? throw new JsonException("LLM response had no message content.");
                var parsed = JsonSerializer.Deserialize<T>(content, OutputJson)
                    ?? throw new JsonException("LLM structured output was null.");
                AgentOutputValidator.Validate(parsed);
                return new OllamaResult<T>(parsed, envelope.Model ?? _options.Model,
                    envelope.Usage?.PromptTokens, envelope.Usage?.CompletionTokens);
            }
            catch (Exception exception) when (exception is HttpRequestException or JsonException or TaskCanceledException)
            {
                lastError = exception;
            }
        }

        throw new InvalidOperationException("Hosted LLM failed after one retry.", lastError);
    }

    private sealed record ChatEnvelope(string? Model, IReadOnlyList<ChatChoice>? Choices, ChatUsage? Usage);
    private sealed record ChatChoice(ChatMessage? Message);
    private sealed record ChatMessage(string? Content);
    private sealed record ChatUsage(
        [property: JsonPropertyName("prompt_tokens")] int? PromptTokens,
        [property: JsonPropertyName("completion_tokens")] int? CompletionTokens);
}
