// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import '@testing-library/jest-dom/vitest'

import { configureStore } from '@reduxjs/toolkit'
import { fireEvent, render, screen } from '@testing-library/react'
import { Provider } from 'react-redux'
import { MemoryRouter } from 'react-router-dom'
import { describe, expect, it, vi, beforeEach } from 'vitest'

import authReducer from '../../store/slices/authSlice'
import { AuthPage } from './AuthPage'

// Mock binary assets
vi.mock('../../assets/logo.png',     () => ({ default: 'logo.png' }))
vi.mock('../../assets/Loging.webp',  () => ({ default: 'loging.webp' }))
vi.mock('../../assets/Register.webp',() => ({ default: 'register.webp' }))
vi.mock('../../styles/auth-shell.css', () => ({}))

function renderLogin() {
  const store = configureStore({ reducer: { auth: authReducer } })
  return render(
    <Provider store={store}>
      <MemoryRouter initialEntries={['/login']}>
        <AuthPage />
      </MemoryRouter>
    </Provider>,
  )
}

function renderRegister() {
  const store = configureStore({ reducer: { auth: authReducer } })
  return render(
    <Provider store={store}>
      <MemoryRouter initialEntries={['/register']}>
        <AuthPage />
      </MemoryRouter>
    </Provider>,
  )
}

describe('AuthPage — Premium Redesign', () => {
  beforeEach(() => { vi.clearAllMocks() })

  // ── Login page ─────────────────────────────────────────────────────────────

  it('renders login form with correct heading and inputs', () => {
    renderLogin()
    expect(screen.getByRole('heading', { level: 1, name: /welcome back/i })).toBeInTheDocument()
    expect(screen.getByText(/sign in to continue to familyveda/i)).toBeInTheDocument()
    expect(screen.getByLabelText(/email address/i)).toBeInTheDocument()
    expect(screen.getByLabelText(/^password/i)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /^sign in$/i })).toBeInTheDocument()
  })

  it('renders Remember me checkbox', () => {
    renderLogin()
    expect(screen.getByLabelText(/remember me/i)).toBeInTheDocument()
  })

  it('renders Forgot password link', () => {
    renderLogin()
    expect(screen.getByRole('link', { name: /forgot password/i })).toBeInTheDocument()
  })

  it('renders Create an account switch button', () => {
    renderLogin()
    expect(screen.getByRole('button', { name: /create an account/i })).toBeInTheDocument()
  })

  it('does NOT contain demo credentials, role selectors, or demo text', () => {
    renderLogin()
    expect(screen.queryByText(/quick fill demo role/i)).not.toBeInTheDocument()
    expect(screen.queryByText(/select a demo role to test/i)).not.toBeInTheDocument()
    expect(screen.queryByText(/view demo credentials/i)).not.toBeInTheDocument()
    expect(screen.queryByText(/choose a demo role/i)).not.toBeInTheDocument()
    expect(screen.queryByText(/demo uses synthetic identities only/i)).not.toBeInTheDocument()
    expect(screen.queryByText(/clinical portal access/i)).not.toBeInTheDocument()
    expect(screen.queryByText(/let's get started/i)).not.toBeInTheDocument()
  })

  it('shows email validation error for invalid email on login', async () => {
    renderLogin()
    fireEvent.change(screen.getByLabelText(/email address/i), { target: { value: 'not-an-email' } })
    fireEvent.click(screen.getByRole('button', { name: /^sign in$/i }))
    expect(await screen.findByText(/enter a valid email address/i)).toBeInTheDocument()
  })

  it('shows password required error when password is empty', async () => {
    renderLogin()
    fireEvent.change(screen.getByLabelText(/email address/i), { target: { value: 'user@test.com' } })
    fireEvent.click(screen.getByRole('button', { name: /^sign in$/i }))
    expect(await screen.findByText(/enter your password/i)).toBeInTheDocument()
  })

  it('toggles password visibility on login', () => {
    renderLogin()
    const pwInput = screen.getByLabelText(/^password/i)
    expect(pwInput).toHaveAttribute('type', 'password')
    fireEvent.click(screen.getByRole('button', { name: /show password/i }))
    expect(pwInput).toHaveAttribute('type', 'text')
  })

  // ── Register page ──────────────────────────────────────────────────────────

  it('renders register form with role selector cards', () => {
    renderRegister()
    expect(screen.getByRole('heading', { level: 1, name: /create your familyveda account/i })).toBeInTheDocument()
    expect(screen.getByRole('radio', { name: /family head/i })).toBeInTheDocument()
    expect(screen.getByRole('radio', { name: /adult member/i })).toBeInTheDocument()
    expect(screen.getByRole('radio', { name: /doctor/i })).toBeInTheDocument()
  })

  it('shows name and email fields on register', () => {
    renderRegister()
    expect(screen.getByLabelText(/full name/i)).toBeInTheDocument()
    expect(screen.getByLabelText(/email address/i)).toBeInTheDocument()
  })

  it('shows Create Account button when Family Head selected', () => {
    renderRegister()
    expect(screen.getByRole('button', { name: /create account/i })).toBeInTheDocument()
  })

  it('shows doctor registration redirect button when Doctor role selected', () => {
    renderRegister()
    fireEvent.click(screen.getByRole('radio', { name: /doctor/i }))
    expect(screen.getByRole('button', { name: /continue to doctor registration/i })).toBeInTheDocument()
  })

  it('hides password field when Doctor role selected (redirects instead)', () => {
    renderRegister()
    fireEvent.click(screen.getByRole('radio', { name: /doctor/i }))
    // Password field not shown since doctor goes to dedicated page
    expect(screen.queryByLabelText(/^password/i)).not.toBeInTheDocument()
  })

  it('renders Sign in switch button on register page', () => {
    renderRegister()
    expect(screen.getByRole('button', { name: /^sign in$/i })).toBeInTheDocument()
  })

  // ── Accessible landmarks ───────────────────────────────────────────────────

  it('login page has accessible main landmark', () => {
    renderLogin()
    expect(screen.getByRole('main', { name: /sign in/i })).toBeInTheDocument()
  })

  it('register page has accessible main landmark', () => {
    renderRegister()
    expect(screen.getByRole('main', { name: /create account/i })).toBeInTheDocument()
  })
})
