// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import { useState } from 'react'
import type { FormEvent } from 'react'
import { Link, Navigate, useNavigate } from 'react-router-dom'

import { apiClient } from '../../services/apiClient'
import { useAppDispatch, useAppSelector } from '../../store/hooks'
import { registerDoctorUser } from '../../store/slices/authSlice'
import logoUrl from '../../assets/logo.png'

export function DoctorRegisterPage() {
  const dispatch = useAppDispatch(); const navigate = useNavigate()
  const { isAuthenticated, user, status, error: authError } = useAppSelector((state) => state.auth)
  const [error, setError] = useState('')
  if (isAuthenticated) return <Navigate to={user?.role === 'DOCTOR' ? '/doctor-status' : '/dashboard'} replace />

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    const registration = { displayName: String(form.get('displayName') ?? '').trim(), email: String(form.get('email') ?? '').trim(), password: String(form.get('password') ?? '') }
    if (!registration.displayName || !registration.email.includes('@') || registration.password.length < 12) { setError('Enter a valid name, email, and password of at least 12 characters.'); return }
    const result = await dispatch(registerDoctorUser(registration)); if (!registerDoctorUser.fulfilled.match(result)) return
    try { await apiClient.post('/doctors/register', { registrationNumber: String(form.get('registrationNumber') ?? '').trim(), specialty: String(form.get('specialty') ?? '').trim() || null }) }
    catch { setError('Account created, but the synthetic doctor profile needs attention. Continue to status to resume.') }
    navigate('/doctor-status', { replace: true })
  }

  return <main className="login-page"><section className="login-intro"><span className="brand-mark brand-mark--large"><img src={logoUrl} alt="" width={128} height={128} /></span><p className="eyebrow">Synthetic clinician enrolment</p><h1>Register for manual verification.</h1><p>Clinical access remains blocked until an administrator verifies the profile. Never enter a real registration number.</p></section>
    <section className="login-card"><h2>Create doctor account</h2><form onSubmit={submit} noValidate>
      <label className="field"><span>Display name</span><input name="displayName" required maxLength={120} /></label>
      <label className="field"><span>Email</span><input name="email" type="email" required /></label>
      <label className="field"><span>Password</span><input name="password" type="password" minLength={12} required /></label>
      <label className="field"><span>Synthetic registration identifier</span><input name="registrationNumber" minLength={4} maxLength={30} required /></label>
      <label className="field"><span>Specialty (optional)</span><input name="specialty" maxLength={120} /></label>
      {(error || authError) && <p className="form-error" role="alert">{error || authError}</p>}
      <button className="button button--primary" type="submit" disabled={status === 'loading'}>{status === 'loading' ? 'Creating account…' : 'Submit for verification'}</button>
    </form><p className="privacy-note"><Link to="/login">Return to sign in</Link></p></section>
  </main>
}
