// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { z } from 'zod'

import { useAppDispatch, useAppSelector } from '../../store/hooks'
import { registerFamilyUser } from '../../store/slices/authSlice'
import logoUrl from '../../assets/logo.png'

const registrationSchema = z.object({
  displayName: z.string().trim().min(1, 'Enter your display name.').max(120),
  email: z.string().email('Enter a valid email address.'),
  nic: z.string().trim().min(4, 'Enter a synthetic NIC number (at least 4 characters).').max(30),
  address: z.string().trim().min(3, 'Enter your residential address.').max(250),
  password: z.string().min(12, 'Use at least 12 characters.').max(128),
})

export function RegisterPage() {
  const dispatch = useAppDispatch()
  const navigate = useNavigate()
  const { isAuthenticated, user, status, error: authError } = useAppSelector((state) => state.auth)
  const [displayName, setDisplayName] = useState('')
  const [email, setEmail] = useState('')
  const [nic, setNic] = useState('')
  const [address, setAddress] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [theme, setTheme] = useState<'light' | 'dark'>(() => {
    try {
      return (globalThis.localStorage?.getItem('fv-theme') as 'light' | 'dark') || 'light'
    } catch {
      return 'light'
    }
  })

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme)
  }, [theme])

  const setAppTheme = (nextTheme: 'light' | 'dark') => {
    setTheme(nextTheme)
    document.documentElement.setAttribute('data-theme', nextTheme)
    try {
      globalThis.localStorage?.setItem('fv-theme', nextTheme)
    } catch {
      // persistence is a convenience; ignore a blocked or unavailable store
    }
  }

  if (isAuthenticated) return <Navigate to={user?.role === 'ONBOARDING' ? '/onboarding' : '/dashboard'} replace />

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const parsed = registrationSchema.safeParse({ displayName, email, nic, address, password })
    if (!parsed.success) {
      setError(parsed.error.issues[0]?.message ?? 'Check the form.')
      return
    }
    setError('')
    const result = await dispatch(registerFamilyUser(parsed.data))
    if (registerFamilyUser.fulfilled.match(result)) navigate('/onboarding', { replace: true })
  }

  return (
    <main className="login-page">
      {/* Top right clean theme toggle */}
      <div className="login-topbar">
        <div className="theme-toggle-group" role="group" aria-label="Theme mode switcher">
          <button
            type="button"
            className={`theme-toggle-btn ${theme === 'light' ? 'active' : ''}`}
            onClick={() => setAppTheme('light')}
          >
            <span aria-hidden="true">☀️</span> Light
          </button>
          <button
            type="button"
            className={`theme-toggle-btn ${theme === 'dark' ? 'active' : ''}`}
            onClick={() => setAppTheme('dark')}
          >
            <span aria-hidden="true">🌙</span> Dark
          </button>
        </div>
      </div>

      {/* Central Registration Stage with interactive floating animated wings */}
      <div className="login-stage">
        {/* Left floating live indicators */}
        <aside className="login-wing login-wing--left" aria-hidden="true">
          <div className="live-floating-card live-floating-card--1">
            <span className="live-icon-badge">👨‍👩‍👧</span>
            <div>
              <strong>Family Circles</strong>
              <small><span className="pulse-dot" /> Multi-member care</small>
            </div>
          </div>
          <div className="live-floating-card live-floating-card--2">
            <span className="live-icon-badge">🧬</span>
            <div>
              <strong>Hereditary Tree</strong>
              <small>Familial risk mapping</small>
            </div>
          </div>
          <div className="live-floating-card live-floating-card--3">
            <span className="live-icon-badge">🛡️</span>
            <div>
              <strong>Granular Consent</strong>
              <small>Full data control</small>
            </div>
          </div>
        </aside>

        {/* Clean centered registration card */}
        <div className="simple-login-card">
          <div className="simple-login-brand">
            <img src={logoUrl} alt="Family Veda" width={56} height={56} />
            <h1>Family Veda</h1>
            <p>Family workspace</p>
          </div>

          <p className="eyebrow">Family registration</p>
          <h2 id="register-heading">Create account</h2>
          <p className="muted">Set up the account first, then create the family and your linked head profile.</p>

          <form onSubmit={submit} noValidate>
            <label className="field">
              <span>Display name</span>
              <input
                value={displayName}
                autoComplete="name"
                placeholder="e.g. Sahan Bandara"
                onChange={(event) => setDisplayName(event.target.value)}
                required
              />
            </label>
            <label className="field">
              <span>Email address</span>
              <input
                type="email"
                value={email}
                autoComplete="email"
                placeholder="name@example.invalid"
                onChange={(event) => setEmail(event.target.value)}
                required
              />
            </label>
            <label className="field">
              <span>Synthetic NIC</span>
              <input
                value={nic}
                placeholder="e.g. 200012345678 or 991234567V"
                onChange={(event) => setNic(event.target.value)}
                required
              />
            </label>
            <label className="field">
              <span>Residential address</span>
              <input
                value={address}
                placeholder="e.g. 124 Temple Road, Colombo"
                onChange={(event) => setAddress(event.target.value)}
                required
              />
            </label>
            <label className="field">
              <span>Password</span>
              <input
                type="password"
                value={password}
                autoComplete="new-password"
                placeholder="At least 12 characters"
                onChange={(event) => setPassword(event.target.value)}
                required
              />
            </label>
            {(error || authError) && <p className="form-error" role="alert">{error || authError}</p>}
            <button type="submit" disabled={status === 'loading'} className="button button--primary button--full">
              {status === 'loading' ? 'Creating account…' : 'Create account'}
            </button>
          </form>

          <p className="privacy-note">Registering a synthetic clinician? <Link to="/register/doctor">Doctor registration</Link>.</p>
          <p className="privacy-note">Already registered? <Link to="/login">Sign in</Link>. Synthetic identities only.</p>
        </div>

        {/* Right floating live indicators */}
        <aside className="login-wing login-wing--right" aria-hidden="true">
          <div className="live-floating-card live-floating-card--4">
            <span className="live-icon-badge">⚡</span>
            <div>
              <strong>AI Triage Support</strong>
              <small>Verified by doctors</small>
            </div>
          </div>
          <div className="live-floating-card live-floating-card--5">
            <span className="live-icon-badge">📋</span>
            <div>
              <strong>Lab OCR Extraction</strong>
              <small>Instant digitization</small>
            </div>
          </div>
          <div className="live-floating-card live-floating-card--6">
            <span className="live-icon-badge">🔒</span>
            <div>
              <strong>Privacy First</strong>
              <small>SLMC verified clinicians</small>
            </div>
          </div>
        </aside>
      </div>
    </main>
  )
}
