// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import { useCallback, useEffect, useState } from 'react'

import { EmptyState, ErrorState, LoadingState } from '../../components/shared/ViewState'
import { threePortalApi, type NotificationDto } from '../../services/apiClient'
import { formatDateTime } from '../family/threePortalShared'

export function NotificationsPage() {
  const [notifications, setNotifications] = useState<NotificationDto[]>([])
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading')

  const load = useCallback(async () => {
    setStatus('loading')
    try {
      const { data } = await threePortalApi.getNotifications()
      setNotifications(data)
      setStatus('ready')
    } catch {
      setStatus('error')
    }
  }, [])

  useEffect(() => {
    void load()
  }, [load])

  async function markRead(notification: NotificationDto) {
    if (notification.readAt) return
    setNotifications((prev) => prev.map((item) => (item.id === notification.id ? { ...item, readAt: new Date().toISOString() } : item)))
    try {
      await threePortalApi.markNotificationRead(notification.id)
    } catch {
      await load()
    }
  }

  if (status === 'loading') return <LoadingState label="Loading notifications" />
  if (status === 'error') return <ErrorState message="Notifications could not be loaded." onRetry={() => void load()} />

  return (
    <div className="page-stack">
      <header className="page-header">
        <div>
          <p className="eyebrow">Updates</p>
          <h1>Notifications</h1>
        </div>
      </header>

      <section className="panel">
        {notifications.length === 0 ? (
          <EmptyState title="No notifications" message="You're all caught up." />
        ) : (
          <ul className="activity-list">
            {notifications.map((notification) => (
              <li key={notification.id} className={notification.readAt ? '' : 'activity-list-item--unread'}>
                <div>
                  <strong>{notification.title}</strong>
                  <p>{notification.body}</p>
                  <small>{formatDateTime(notification.createdAt)}</small>
                </div>
                {!notification.readAt && (
                  <button className="button button--secondary" type="button" onClick={() => void markRead(notification)}>
                    Mark read
                  </button>
                )}
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  )
}
