// Owner: S2 · Health Records & Extraction — Fernando K.R.N (IT24101875)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using FamilyVeda.Infrastructure.Records;
using FluentAssertions;
using System.Globalization;

namespace FamilyVeda.UnitTests;

public sealed class LabExtractionParserTests
{
    [Theory]
    [InlineData("on 06/23/2025 at: 2 PM.")]
    [InlineData("Follow up: 2 PM")]
    public void ParseValues_DoesNotTreatAppointmentTimesAsLabResults(string text)
    {
        LabExtractionService.ParseValues(text).Should().BeEmpty();
    }

    [Fact]
    public void ParseValues_ReadsDemoLabColonPipeFormat()
    {
        LabExtractionService.ParseValues("Synthetic demo lab\nGlucose: 92 mg/dL | 70-99").Should().ContainSingle()
            .Which.Should().Be(new LabExtractionService.ParsedLabValue("Glucose", 92m, "mg/dL", 70m, 99m));
    }

    private const string TableHeader = "Test\nResult\nPrevious Result\nDate\nUnits\nRef Interval";

    [Fact]
    public void ParseValues_ExtractsStructuredRows_AndIgnoresFreeText()
    {
        const string text = "Synthetic report only\nHaemoglobin | 12.4 g/dL | 11.0-15.0\nignore this sentence";

        var values = LabExtractionService.ParseValues(text);

        values.Should().ContainSingle().Which.Should().Be(
            new LabExtractionService.ParsedLabValue("Haemoglobin", 12.4m, "g/dL", 11.0m, 15.0m));
    }

    [Fact]
    public void ParseFlags_AcceptsOnlyExplicitBoundedMarker()
    {
        const string text = "Possible trait in prose\nHEREDITARY_FLAG: SYNTH-CARRIER | Explicit synthetic marker | 0.72";

        var flags = LabExtractionService.ParseFlags(text);

        flags.Should().ContainSingle().Which.Should().Be(
            new LabExtractionService.ParsedFlag("SYNTH-CARRIER", "Explicit synthetic marker", 0.72m));
    }

    [Theory]
    [InlineData("SYNTHETIC_ClinOCR_tables_t11_s2.expected.txt", 142, 7.9)]
    [InlineData("SYNTHETIC_ClinOCR_tables_t11_s3.expected.txt", 88, 5.2)]
    public void ParseValues_ExtractsRecognizedClinOcrTablesOnly(string fixture, decimal glucose, decimal hba1c)
    {
        var repositoryRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../../../"));
        var text = File.ReadAllText(Path.Combine(repositoryRoot, "docs", "evidence", "medical-report-test-data", fixture));

        var values = LabExtractionService.ParseValues(text);

        values.Should().HaveCount(18);
        values.Should().Contain(x => x.Analyte == "Glucose" && x.Value == glucose && x.Low == 70m && x.High == 99m);
        values.Should().Contain(x => x.Analyte == "Hemoglobin A1c" && x.Value == hba1c && x.Low == null && x.High == null);
        values.Should().Contain(x => x.Analyte == "eGFR" && x.Unit == "mL/min/1.73m2" && x.Low == null && x.High == null);
    }

    [Fact]
    public void ParseValues_TableRows_UseCurrentValueAndRejectMalformedFields()
    {
        var text = $"{TableHeader}\nGlucose\n142 H\n126\n03/01/2026\nmg/dL\n70-99\nBad current\none\n126\n03/01/2026\nmg/dL\n70-99\nBad previous\n142\none\n03/01/2026\nmg/dL\n70-99\nBad date\n142\n126\n2026-03-01\nmg/dL\n70-99\nBad unit\n142\n126\n03/01/2026\nmg dL\n70-99\nBad range\n142\n126\n03/01/2026\nmg/dL\n70-\nOverflow\n999999999999999999999999999999\n126\n03/01/2026\nmg/dL\n70-99";

        var values = LabExtractionService.ParseValues(text);

        values.Should().ContainSingle().Which.Should().Be(new LabExtractionService.ParsedLabValue("Glucose", 142m, "mg/dL", 70m, 99m));
    }

    [Fact]
    public void ParseValues_DoesNotParseTableRowsWithoutRecognizedHeader()
    {
        const string text = "Glucose\n142 H\n126\n03/01/2026\nmg/dL\n70-99\nMedication\nAspirin";

        LabExtractionService.ParseValues(text).Should().BeEmpty();
    }

    [Fact]
    public void ParseValues_UsesInvariantCultureForClinOcrNumbers()
    {
        var original = CultureInfo.CurrentCulture;
        try
        {
            CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("fr-FR");
            var values = LabExtractionService.ParseValues($"{TableHeader}\nCreatinine\n0.70\n0.68\n01/15/2026\nmg/dL\n0.57-1.00");
            values.Should().ContainSingle().Which.Should().Be(new LabExtractionService.ParsedLabValue("Creatinine", 0.70m, "mg/dL", 0.57m, 1.00m));
        }
        finally
        {
            CultureInfo.CurrentCulture = original;
        }
    }

    [Fact]
    public void ParseValues_ExtractsRowPerLineTableAsProducedByRealOcr()
    {
        // Verbatim shape of Tesseract output for SYNTHETIC_ClinOCR_tables_t11_s2.jpg: flag glued to the value, wrapped header.
        const string text = "Comp. Metabolic Panel\nTest Result Previous Date Units Ref\nResult Interval\nGlucose 142H 126 03/01/2026 mg/dL 70-99\nBUN 22 19 03/01/2026 mg/dL 7-25\neGFR 61 65 03/01/2026 mL/min/1.73m2 >=60\nCarbon Dioxide, Total 23 24 03/01/2026 mEq/L 21-32\nHemoglobin A1c\nTest Result Previous Date Units Ref Interval\nResult\nHemoglobin A1c 7.9H 7.5 03/01/2026 % <5.7\n";

        var values = LabExtractionService.ParseValues(text);

        values.Select(x => (x.Analyte, x.Value, x.Unit, x.Low, x.High)).Should().Equal(
            ("Glucose", 142m, "mg/dL", 70m, 99m),
            ("BUN", 22m, "mg/dL", 7m, 25m),
            ("eGFR", 61m, "mL/min/1.73m2", (decimal?)null, (decimal?)null),
            ("Carbon Dioxide, Total", 23m, "mEq/L", 21m, 32m),
            ("Hemoglobin A1c", 7.9m, "%", (decimal?)null, (decimal?)null));
    }

    [Fact]
    public void ParseValues_IgnoresRowPerLineRowsWithoutHeaderOrWithMalformedFields()
    {
        LabExtractionService.ParseValues("Glucose 142H 126 03/01/2026 mg/dL 70-99\n").Should().BeEmpty();
        LabExtractionService.ParseValues("Test Result Previous Date Units Ref\nGlucose 142H 126 13/45/2026 mg/dL 70-99\nBUN 22 03/01/2026 mg/dL 7-25\nPotassium 3.8 4.0 03/01/2026 mEq/L about normal\n").Should().BeEmpty();
    }

    [Fact]
    public void ParseValues_ExtractsReferenceRangeTableAsProducedByRealOcr()
    {
        // Verbatim shape of Tesseract output for SYNTHETIC_morzel_lab_page1_clean.png: noisy header, stray cell borders, trailing flag glyph.
        const string text = "CBC panel - Blood by Automated count 11/25/2020 - Final\nTest” 7 rr RESULT rr UNIT REFERENCE RANGE FLAG\n\n| Leukocytes [#/volume] in Blood by Automated count 7.6059 10*3/uL Not supplied _—\nHemoglobin [Mass/volume] in Blood 14.425 g/dL Not supplied _—\n| Hematocrit [Volume Fraction] of Blood by Automated count 47.698 % Not supplied _—\nDiastolic Blood Pressure 91 mm[Hg] Not supplied _—\nGlucose 5.4 mmol/L 3.9 - 5.6\n";

        var values = LabExtractionService.ParseValues(text);

        values.Select(x => (x.Analyte, x.Value, x.Unit, x.Low, x.High)).Should().Equal(
            ("Leukocytes [#/volume] in Blood by Automated count", 7.6059m, "10*3/uL", (decimal?)null, (decimal?)null),
            ("Hemoglobin [Mass/volume] in Blood", 14.425m, "g/dL", (decimal?)null, (decimal?)null),
            ("Hematocrit [Volume Fraction] of Blood by Automated count", 47.698m, "%", (decimal?)null, (decimal?)null),
            ("Diastolic Blood Pressure", 91m, "mm[Hg]", (decimal?)null, (decimal?)null),
            ("Glucose", 5.4m, "mmol/L", 3.9m, 5.6m));
    }

    [Fact]
    public void ParseValues_ReferenceRangeTable_IgnoresQuestionnaireRowsAndRowsWithoutHeader()
    {
        LabExtractionService.ParseValues("Hemoglobin [Mass/volume] in Blood 14.425 g/dL Not supplied _—\n").Should().BeEmpty();
        // Survey answers and questionnaire scores share the table but are not laboratory measurements.
        LabExtractionService.ParseValues("TEST RESULT UNIT REFERENCE RANGE FLAG\nWhat was your best estimate of the total income of all 147460 la Not supplied _—\nHow many people are living or staying at this address [#] 3 {#} Not supplied _—\nTotal score [AUDIT-C] 1 {score} Not supplied _—\nHemoglobin 14.4 g/dL about normal\n").Should().BeEmpty();
    }

    [Fact]
    public void ParseValues_ExtractsColumnAlignedRows_FromPdfTextLayer()
    {
        // Synthetic report in the column-aligned shape `pdftotext -layout` produces for local laboratory formats.
        const string text = "SYNTHETIC LABORATORY — FULL BLOOD COUNT\nPatient Name      Synthetic Member\nAge               45     Years\nTest                         Result        Units          Reference Range\nHaemoglobin                  10.2   L      g/dL           11.5 - 15.5\nWhite Cell Count             7,850         /cumm          4,000 - 11,000\nPlatelet Count               250000        /cumm          150000 - 450000\nFasting Blood Sugar          1O8    H      mg/dL          70 - 100\nTSH                          2,35          mIU/L          < 4.5\n";

        var values = LabExtractionService.ParseValues(text);

        values.Select(x => (x.Analyte, x.Value, x.Unit, x.Low, x.High)).Should().Equal(
            ("Haemoglobin", 10.2m, "g/dL", 11.5m, 15.5m),
            ("White Cell Count", 7850m, "/cumm", 4000m, 11000m),
            ("Platelet Count", 250000m, "/cumm", 150000m, 450000m),
            ("Fasting Blood Sugar", 108m, "mg/dL", 70m, 100m),
            ("TSH", 2.35m, "mIU/L", (decimal?)null, (decimal?)null));
    }

    [Theory]
    [InlineData("Age               45     Years")]
    [InlineData("Page              1      of")]
    [InlineData("Reported on 03/01/2026   10   AM")]
    [InlineData("Glucose  5.4  mmol/L  9.0 - 3.0")]
    public void ParseValues_ColumnAlignedRows_RejectHeadersAndInvertedRanges(string line)
    {
        LabExtractionService.ParseValues(line).Should().BeEmpty();
    }

    [Theory]
    [InlineData("Hb  1O.5  g/dL", "Hb  10.5  g/dL")]
    [InlineData("WBC  4,500  /cumm", "WBC  4500  /cumm")]
    [InlineData("Hb  12,4  g/dL", "Hb  12.4  g/dL")]
    [InlineData("CO2  24  mmol/L", "CO2  24  mmol/L")]
    public void CleanOcrDigits_FixesConfusionsOnlyInsideNumbers(string input, string expected)
    {
        LabExtractionService.CleanOcrDigits(input).Should().Be(expected);
    }
}
