// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// [S4] Three-portal family features per docs/Three_Portal_Feature_Spec.md.
// New API surface only — deliberately kept out of patient_api.dart (S3-owned).
import 'package:family_veda/models/appointment.dart';
import 'package:family_veda/models/doctor_summary.dart';
import 'package:family_veda/models/family_dashboard.dart';
import 'package:family_veda/models/incoming_invitation.dart';
import 'package:family_veda/models/join_request.dart';
import 'package:family_veda/services/api/api_client.dart';

abstract interface class FamilyPortalApi {
  Future<FamilyDashboard> getFamilyDashboard();

  Future<List<Appointment>> getMyAppointments();
  Future<Appointment> bookAppointment({
    required String memberId,
    required DateTime startsAt,
    int durationMinutes = 30,
    required String reason,
  });
  Future<void> cancelAppointment(String id);

  Future<JoinRequest> joinFamilyByCode({
    required String familyCode,
    required String relationshipType,
    String? message,
  });
  Future<List<JoinRequest>> getPendingJoinRequests(String familyId);
  Future<void> acceptJoinRequest(String id);
  Future<void> declineJoinRequest(String id);

  Future<List<IncomingInvitation>> getIncomingInvitations();
  Future<void> approveInvitation(String id);
  Future<void> rejectInvitation(String id);

  Future<DoctorSummary?> getFamilyDoctor(String familyId);
  Future<List<DoctorSummary>> searchDoctorDirectory({
    String? search,
    String? district,
  });
  Future<void> requestFamilyDoctor({
    required String familyId,
    required String doctorId,
    String? message,
  });

  Future<void> markNotificationRead(String id);
}

class DioFamilyPortalApi implements FamilyPortalApi {
  const DioFamilyPortalApi(this._client);

  final ApiClient _client;

  @override
  Future<FamilyDashboard> getFamilyDashboard() async {
    final response = await _client.dio.get<Map<String, dynamic>>(
      '/dashboard/family',
    );
    final data = response.data;
    if (data == null) throw const FormatException('Empty dashboard response');
    return FamilyDashboard.fromJson(data);
  }

  @override
  Future<List<Appointment>> getMyAppointments() async {
    final response = await _client.dio.get<dynamic>('/appointments/mine');
    return _listFrom(response.data)
        .map(Appointment.fromJson)
        .toList(growable: false);
  }

  @override
  Future<Appointment> bookAppointment({
    required String memberId,
    required DateTime startsAt,
    int durationMinutes = 30,
    required String reason,
  }) async {
    final response = await _client.dio.post<Map<String, dynamic>>(
      '/appointments',
      data: {
        'memberId': memberId,
        'startsAt': startsAt.toUtc().toIso8601String(),
        'durationMinutes': durationMinutes,
        'reason': reason.trim(),
      },
    );
    final data = response.data;
    if (data == null) throw const FormatException('Empty appointment response');
    return Appointment.fromJson(data);
  }

  @override
  Future<void> cancelAppointment(String id) async {
    await _client.dio.post<void>('/appointments/$id/cancel');
  }

  @override
  Future<JoinRequest> joinFamilyByCode({
    required String familyCode,
    required String relationshipType,
    String? message,
  }) async {
    final response = await _client.dio.post<Map<String, dynamic>>(
      '/families/join-requests',
      data: {
        'familyCode': familyCode.trim().toUpperCase(),
        'relationshipType': relationshipType,
        if (message != null && message.trim().isNotEmpty)
          'message': message.trim(),
      },
    );
    final data = response.data;
    if (data == null) throw const FormatException('Empty join request response');
    return JoinRequest.fromJson(data);
  }

  @override
  Future<List<JoinRequest>> getPendingJoinRequests(String familyId) async {
    final response = await _client.dio.get<dynamic>(
      '/families/$familyId/join-requests',
      queryParameters: {'status': 'Pending'},
    );
    return _listFrom(response.data)
        .map(JoinRequest.fromJson)
        .toList(growable: false);
  }

  @override
  Future<void> acceptJoinRequest(String id) async {
    await _client.dio.post<void>('/families/join-requests/$id/accept');
  }

  @override
  Future<void> declineJoinRequest(String id) async {
    await _client.dio.post<void>('/families/join-requests/$id/decline');
  }

  @override
  Future<List<IncomingInvitation>> getIncomingInvitations() async {
    final response = await _client.dio.get<dynamic>('/invitations/incoming');
    return _listFrom(response.data)
        .map(IncomingInvitation.fromJson)
        .toList(growable: false);
  }

  @override
  Future<void> approveInvitation(String id) async {
    await _client.dio.post<void>('/invitations/$id/approve');
  }

  @override
  Future<void> rejectInvitation(String id) async {
    await _client.dio.post<void>('/invitations/$id/reject');
  }

  @override
  Future<DoctorSummary?> getFamilyDoctor(String familyId) async {
    final response = await _client.dio.get<Map<String, dynamic>>(
      '/families/$familyId/doctor',
    );
    final data = response.data;
    return data == null ? null : DoctorSummary.fromJson(data);
  }

  @override
  Future<List<DoctorSummary>> searchDoctorDirectory({
    String? search,
    String? district,
  }) async {
    final response = await _client.dio.get<dynamic>(
      '/doctors/directory',
      queryParameters: {
        if (search != null && search.trim().isNotEmpty) 'search': search.trim(),
        if (district != null && district.trim().isNotEmpty) 'district': district.trim(),
      },
    );
    return _listFrom(response.data)
        .map(DoctorSummary.fromJson)
        .toList(growable: false);
  }

  @override
  Future<void> requestFamilyDoctor({
    required String familyId,
    required String doctorId,
    String? message,
  }) async {
    await _client.dio.post<void>(
      '/families/$familyId/doctor-requests',
      data: {
        'doctorId': doctorId,
        if (message != null && message.trim().isNotEmpty)
          'message': message.trim(),
      },
    );
  }

  @override
  Future<void> markNotificationRead(String id) async {
    await _client.dio.post<void>('/notifications/$id/read');
  }
}

List<Map<String, dynamic>> _listFrom(dynamic value) {
  final raw = value is Map<String, dynamic>
      ? (value['items'] ?? value['data'] ?? const <dynamic>[])
      : value;
  if (raw is! List) throw const FormatException('Expected a list response');
  return raw.cast<Map<String, dynamic>>();
}
