// Owner: S2 · Health Records & Extraction — Fernando K.R.N (IT24101875)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using System.Threading.Channels;
using FamilyVeda.Application.Records;

namespace FamilyVeda.Infrastructure.Records;

// Unbounded so the extract request never waits on the queue; depth is limited by the "Ocr" rate limiter and one report = one entry.
public sealed class LabExtractionQueue : ILabExtractionQueue
{
    private readonly Channel<Guid> _queue = Channel.CreateUnbounded<Guid>(new UnboundedChannelOptions { SingleReader = true, SingleWriter = false });

    public ValueTask QueueAsync(Guid reportId, CancellationToken cancellationToken) => _queue.Writer.WriteAsync(reportId, cancellationToken);
    public ValueTask<Guid> DequeueAsync(CancellationToken cancellationToken) => _queue.Reader.ReadAsync(cancellationToken);
}
