// Owner: S2 · Health Records & Extraction — Fernando K.R.N (IT24101875)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using System.Diagnostics;
using FamilyVeda.Application.Common;
using FamilyVeda.Application.Records;
using Microsoft.Extensions.Configuration;

namespace FamilyVeda.Infrastructure.Records;

public sealed partial class TesseractOcrService(IConfiguration configuration) : IOcrService
{
    private readonly SemaphoreSlim _processSlots = new(Math.Clamp(configuration.GetValue("Ocr:MaxConcurrentProcesses", 2), 1, 4));

    public async Task<string> ExtractTextAsync(string filePath, CancellationToken cancellationToken)
    {
        await _processSlots.WaitAsync(cancellationToken);
        try
        {
            if (Path.GetExtension(filePath).Equals(".pdf", StringComparison.OrdinalIgnoreCase))
                return await ExtractPdfTextAsync(filePath, cancellationToken);

            var text = LimitText(await RunTesseractAsync(filePath, pageSegmentationMode: null, cancellationToken));
            if (HasStructuredValues(text)) return text!;

            // Photographed or scanned pages are often tilted, which breaks row detection: straighten and retry.
            var deskewedPath = await TryDeskewAsync(filePath, cancellationToken);
            if (deskewedPath is not null)
            {
                try
                {
                    foreach (var mode in DeskewedPageSegmentationModes)
                    {
                        var deskewedText = LimitText(await RunTesseractAsync(deskewedPath, mode, cancellationToken));
                        if (HasStructuredValues(deskewedText)) return deskewedText!;
                    }
                }
                finally
                {
                    File.Delete(deskewedPath);
                }
            }

            return text ?? throw new ProcessingException("OCR could not read this report. Use manual entry instead.");
        }
        finally
        {
            _processSlots.Release();
        }
    }

    // null = Tesseract default (automatic layout); "6" = single uniform block, which keeps table rows on one line.
    private static readonly string?[] DeskewedPageSegmentationModes = [null, "6"];

    private static bool HasStructuredValues(string? text) => text is not null && LabExtractionService.ParseValues(text).Count > 0;

    // Longer reports are rejected rather than partially read, so no result is silently missing.
    private int MaxPages => Math.Clamp(configuration.GetValue("Ocr:MaxPages", 4), 1, 20);

    private int MaxCharacters => Math.Clamp(configuration.GetValue("Ocr:MaxOutputCharacters", 60_000), 1_000, 250_000);

    private string? LimitText(string? text) => text is not null && text.Length > MaxCharacters
        ? throw new ProcessingException("This report contains too much text to read automatically. Use manual entry instead.")
        : text;

    private async Task<string?> RunTesseractAsync(string filePath, string? pageSegmentationMode, CancellationToken cancellationToken)
    {
        var startInfo = NewProcess("tesseract");
        startInfo.ArgumentList.Add(filePath);
        startInfo.ArgumentList.Add("stdout");
        startInfo.ArgumentList.Add("-l");
        startInfo.ArgumentList.Add("eng");
        var dataPath = configuration["Ocr:TesseractDataPath"];
        if (!string.IsNullOrWhiteSpace(dataPath))
        {
            startInfo.ArgumentList.Add("--tessdata-dir");
            startInfo.ArgumentList.Add(dataPath);
        }
        if (pageSegmentationMode is not null)
        {
            startInfo.ArgumentList.Add("--psm");
            startInfo.ArgumentList.Add(pageSegmentationMode);
        }
        using var process = Process.Start(startInfo) ?? throw new ProcessingException("OCR engine could not be started. Use manual entry instead.");
        var (exitCode, output) = await WaitForOutputAsync(process, cancellationToken);
        if (exitCode != 0 || string.IsNullOrWhiteSpace(output)) return null;
        return output;
    }

    private async Task<string?> TryDeskewAsync(string filePath, CancellationToken cancellationToken)
    {
        var command = configuration["Ocr:DeskewCommand"];
        // An explicit coder prefix stops ImageMagick from choosing a decoder based on file content.
        var coder = Path.GetExtension(filePath).ToLowerInvariant() switch
        {
            ".png" => "png",
            ".jpg" or ".jpeg" => "jpeg",
            _ => null
        };
        if (string.IsNullOrWhiteSpace(command) || coder is null) return null;

        var outputPath = Path.Combine(Path.GetTempPath(), $"fv-ocr-deskew-{Guid.NewGuid():N}.png");
        var startInfo = NewProcess(command);
        foreach (var argument in new[] { $"{coder}:{filePath}", "-background", "white", "-deskew", "40%", "+repage", $"png:{outputPath}" })
            startInfo.ArgumentList.Add(argument);
        try
        {
            using var process = Process.Start(startInfo);
            if (process is null) return null;
            var (exitCode, _) = await WaitForOutputAsync(process, cancellationToken);
            if (exitCode == 0 && File.Exists(outputPath)) return outputPath;
        }
        catch (System.ComponentModel.Win32Exception)
        {
            // Deskew tool is not installed: straightening is optional, the first OCR pass still stands.
        }
        File.Delete(outputPath);
        return null;
    }

    // A digital PDF already carries exact text: read it directly and only OCR scanned pages.
    private async Task<string> ExtractPdfTextAsync(string filePath, CancellationToken cancellationToken)
    {
        var pageCount = await CountPdfPagesAsync(filePath, cancellationToken);
        if (pageCount > MaxPages)
            throw new ProcessingException($"This report has {pageCount} pages. Reports longer than {MaxPages} pages cannot be read automatically. Upload only the result pages or use manual entry.");

        var embeddedText = LimitText(await ReadPdfTextLayerAsync(filePath, pageCount, cancellationToken));
        if (HasStructuredValues(embeddedText)) return embeddedText!;
        return await OcrPdfPagesAsync(filePath, pageCount, cancellationToken);
    }

    private async Task<int> CountPdfPagesAsync(string filePath, CancellationToken cancellationToken)
    {
        var startInfo = NewProcess(configuration["Ocr:PdfInfoCommand"] is { Length: > 0 } command ? command : "pdfinfo");
        startInfo.ArgumentList.Add(filePath);
        try
        {
            using var process = Process.Start(startInfo) ?? throw new ProcessingException("PDF reports cannot be read here. Use manual entry instead.");
            var (exitCode, output) = await WaitForOutputAsync(process, cancellationToken);
            var pages = PdfPageCount().Match(output);
            if (exitCode != 0 || !pages.Success || !int.TryParse(pages.Groups["pages"].Value, System.Globalization.NumberStyles.None, System.Globalization.CultureInfo.InvariantCulture, out var count) || count < 1)
                throw new ProcessingException("OCR could not read this report. Use manual entry instead.");
            return count;
        }
        catch (System.ComponentModel.Win32Exception)
        {
            throw new ProcessingException("PDF reports cannot be read here. Use manual entry instead.");
        }
    }

    private async Task<string?> ReadPdfTextLayerAsync(string filePath, int pageCount, CancellationToken cancellationToken)
    {
        var startInfo = NewProcess(configuration["Ocr:PdfTextCommand"] is { Length: > 0 } command ? command : "pdftotext");
        foreach (var argument in new[] { "-layout", "-enc", "UTF-8", "-f", "1", "-l", pageCount.ToString(System.Globalization.CultureInfo.InvariantCulture), filePath, "-" })
            startInfo.ArgumentList.Add(argument);
        try
        {
            using var process = Process.Start(startInfo);
            if (process is null) return null;
            var (exitCode, output) = await WaitForOutputAsync(process, cancellationToken);
            return exitCode == 0 && !string.IsNullOrWhiteSpace(output) ? output : null;
        }
        catch (System.ComponentModel.Win32Exception)
        {
            // Text-layer reader is not installed: fall back to rendering the pages for OCR.
            return null;
        }
    }

    // Tesseract cannot read PDF: rasterise each page and OCR the page images.
    private async Task<string> OcrPdfPagesAsync(string filePath, int pageCount, CancellationToken cancellationToken)
    {
        var command = configuration["Ocr:PdfRenderCommand"];
        if (string.IsNullOrWhiteSpace(command)) throw new ProcessingException("PDF reports cannot be read here. Use manual entry instead.");

        var pageDirectory = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), $"fv-ocr-pdf-{Guid.NewGuid():N}"));
        try
        {
            var startInfo = NewProcess(command);
            var lastPage = pageCount.ToString(System.Globalization.CultureInfo.InvariantCulture);
            foreach (var argument in new[] { "-png", "-r", "200", "-f", "1", "-l", lastPage, filePath, Path.Combine(pageDirectory.FullName, "page") })
                startInfo.ArgumentList.Add(argument);
            try
            {
                using var process = Process.Start(startInfo) ?? throw new ProcessingException("PDF reports cannot be read here. Use manual entry instead.");
                var (exitCode, _) = await WaitForOutputAsync(process, cancellationToken);
                if (exitCode != 0) throw new ProcessingException("OCR could not read this report. Use manual entry instead.");
            }
            catch (System.ComponentModel.Win32Exception)
            {
                throw new ProcessingException("PDF reports cannot be read here. Use manual entry instead.");
            }

            var text = new System.Text.StringBuilder();
            foreach (var page in pageDirectory.GetFiles("page*.png").OrderBy(x => x.Name, StringComparer.Ordinal))
            {
                text.AppendLine(await RunTesseractAsync(page.FullName, pageSegmentationMode: null, cancellationToken));
                LimitText(text.ToString());
            }
            if (string.IsNullOrWhiteSpace(text.ToString())) throw new ProcessingException("OCR could not read this report. Use manual entry instead.");
            return text.ToString();
        }
        finally
        {
            pageDirectory.Delete(recursive: true);
        }
    }

    [System.Text.RegularExpressions.GeneratedRegex(@"^Pages:\s+(?<pages>\d{1,6})\s*$", System.Text.RegularExpressions.RegexOptions.Multiline | System.Text.RegularExpressions.RegexOptions.CultureInvariant)]
    private static partial System.Text.RegularExpressions.Regex PdfPageCount();

    private static ProcessStartInfo NewProcess(string fileName) => new()
    {
        FileName = fileName,
        RedirectStandardOutput = true,
        RedirectStandardError = true,
        UseShellExecute = false,
        CreateNoWindow = true
    };

    private async Task<(int ExitCode, string Output)> WaitForOutputAsync(Process process, CancellationToken cancellationToken)
    {
        using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        timeout.CancelAfter(TimeSpan.FromSeconds(configuration.GetValue("Ocr:TimeoutSeconds", 30)));
        try
        {
            var outputTask = process.StandardOutput.ReadToEndAsync(timeout.Token);
            var errorTask = process.StandardError.ReadToEndAsync(timeout.Token);
            await process.WaitForExitAsync(timeout.Token);
            var output = await outputTask;
            await errorTask;
            return (process.ExitCode, output);
        }
        catch (OperationCanceledException)
        {
            if (!process.HasExited)
            {
                process.Kill(entireProcessTree: true);
                await process.WaitForExitAsync(CancellationToken.None);
            }
            if (cancellationToken.IsCancellationRequested) throw;
            throw new ProcessingException("OCR timed out. Use manual entry instead.");
        }
    }
}
