// Owner: S3 · Triage & Agent Orchestration — Karunathilaka K.D.J.C (IT24100551)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import { useEffect, useState } from 'react'
import { NavLink, Outlet } from 'react-router-dom'

import { useAppDispatch, useAppSelector } from '../../store/hooks'
import { signedOut } from '../../store/slices/authSlice'
import type { UserRole } from '../../store/slices/authSlice'
import { apiClient } from '../../services/apiClient'
import markUrl from '../../assets/logo-mark.png'
// ===== S4 Feature: notifications + three-portal nav (docs/Three_Portal_Feature_Spec.md) =====
import { NotificationBell } from '../shared/NotificationBell'
import { EmergencyHelp } from '../../pages/dashboard/dashboardParts'
import { HeadTransferBanner } from '../../pages/family/HeadTransferBanner'

type NavItem = {
  label: string
  path: string
  roles: UserRole[]
}

// Menus follow docs/Three_Portal_Implementation_Blueprint.md "FINAL NAVIGATION"; order is per role.
const navItems: NavItem[] = [
  { label: 'Doctor verification status', path: '/doctor-status', roles: ['DOCTOR'] },
  { label: 'Family head verification status', path: '/family-head-status', roles: ['FAMILY_HEAD', 'ONBOARDING'] },
  { label: 'Dashboard', path: '/dashboard', roles: ['DOCTOR', 'ADMIN', 'FAMILY_HEAD', 'MEMBER'] },
  // Family Head: Dashboard | My Family | Health Records | Symptoms & Triage | My Doctor | Appointments | Privacy & Access
  { label: 'My Family', path: '/family', roles: ['FAMILY_HEAD'] },
  { label: 'Health Records', path: '/records', roles: ['FAMILY_HEAD'] },
  { label: 'Symptoms & Triage', path: '/triage', roles: ['FAMILY_HEAD'] },
  { label: 'My Doctor', path: '/my-doctor', roles: ['FAMILY_HEAD'] },
  { label: 'Appointments', path: '/appointments', roles: ['FAMILY_HEAD'] },
  { label: 'Privacy & Access', path: '/privacy', roles: ['FAMILY_HEAD'] },
  // Adult Member: Dashboard | My Health | Appointments | Symptoms & Triage | My Family | My Doctor | Privacy
  { label: 'My Health', path: '/records', roles: ['MEMBER'] },
  { label: 'Appointments', path: '/appointments', roles: ['MEMBER'] },
  { label: 'Symptoms & Triage', path: '/triage', roles: ['MEMBER'] },
  { label: 'My Family', path: '/my-family', roles: ['MEMBER'] },
  { label: 'My Doctor', path: '/my-doctor', roles: ['MEMBER'] },
  { label: 'Privacy', path: '/privacy', roles: ['MEMBER'] },
  // Doctor: Dashboard | Calendar | My Families | Triage Cases | Approvals | Profile & Availability
  // One Calendar (docs/Three_Dashboards_UX_Plan.md §1 problem 3); /doctor-calendar redirects here.
  { label: 'Calendar', path: '/calendar', roles: ['DOCTOR'] },
  { label: 'My Families', path: '/families', roles: ['DOCTOR'] },
  { label: 'Triage Cases', path: '/cases', roles: ['DOCTOR'] },
  { label: 'Approvals', path: '/approvals', roles: ['DOCTOR'] },
  { label: 'Profile & Availability', path: '/doctor-profile', roles: ['DOCTOR'] },
  // Clinic Admin: Dashboard | Doctor Verification | Users | Audit Log | Safety & System (UX plan §11)
  { label: 'Doctor Verification', path: '/doctor-verification', roles: ['ADMIN'] },
  { label: 'Users', path: '/users', roles: ['ADMIN'] },
  { label: 'Audit Log', path: '/audit', roles: ['ADMIN'] },
  { label: 'Safety & System', path: '/settings', roles: ['ADMIN'] },
]

const portalName: Record<UserRole, string> = {
  FAMILY_HEAD: 'Family Head Portal',
  MEMBER: 'Adult Member Portal',
  DOCTOR: 'Doctor Portal',
  ADMIN: 'Clinic Admin Portal',
  ONBOARDING: 'Getting started',
}

const roleLabel: Record<UserRole, string> = {
  FAMILY_HEAD: 'Family Head',
  MEMBER: 'Adult Member',
  DOCTOR: 'Doctor',
  ADMIN: 'Clinic Administrator',
  ONBOARDING: 'New account',
}

function initials(name: string | undefined): string {
  if (!name) return '—'
  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? '')
    .join('')
}

export function AppLayout() {
  const dispatch = useAppDispatch()
  const user = useAppSelector((state) => state.auth.user)
  const [theme, setTheme] = useState<'light' | 'dark'>(() => {
    // localStorage is absent under jsdom in the test environment, and can throw
    // when site data is blocked. Never let theme persistence break rendering.
    try {
      return (globalThis.localStorage?.getItem('fv-theme') as 'light' | 'dark') || 'light'
    } catch {
      return 'light'
    }
  })

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme)
  }, [theme])

  const toggleTheme = () => {
    const nextTheme = theme === 'light' ? 'dark' : 'light'
    setTheme(nextTheme)
    document.documentElement.setAttribute('data-theme', nextTheme)
    try {
      globalThis.localStorage?.setItem('fv-theme', nextTheme)
    } catch {
      // persistence is a convenience; ignore a blocked or unavailable store
    }
  }

  const isUnverifiedDoctor = user?.role === 'DOCTOR' && user?.verificationStatus !== 'VERIFIED'
  // Family heads are auto-approved (PR #73); this now only fires when an admin rejects or suspends one.
  const isUnverifiedFamilyHead =
    (user?.role === 'FAMILY_HEAD' || user?.role === 'ONBOARDING') && user?.familyHeadVerificationStatus !== 'VERIFIED'
  const showEmergencyHelp = user?.role === 'FAMILY_HEAD' || user?.role === 'MEMBER'

  const visibleItems = navItems.filter((item) => {
    if (!user || !item.roles.includes(user.role)) return false
    if (isUnverifiedDoctor) return item.path === '/doctor-status'
    if (isUnverifiedFamilyHead) return item.path === '/family-head-status'
    if (item.path === '/doctor-status' || item.path === '/family-head-status') return false
    return true
  })

  const brandDestination = isUnverifiedDoctor
    ? '/doctor-status'
    : isUnverifiedFamilyHead
      ? '/family-head-status'
      : user?.role === 'ONBOARDING'
        ? '/onboarding'
        : '/dashboard'

  async function signOut() {
    try { await apiClient.post('/auth/logout') }
    finally { dispatch(signedOut()) }
  }

  return (
    <div className="app-shell">
      <a className="skip-link" href="#main-content">Skip to main content</a>
      <header className="topbar">
        <NavLink className="brand" to={brandDestination} aria-label="Family Veda dashboard">
          <span className="brand-mark">
            <img src={markUrl} alt="" width={42} height={42} />
          </span>
          <span>
            <strong>Family Veda</strong>
            <small>{user ? portalName[user.role] : 'Clinical decision support'}</small>
          </span>
        </NavLink>
        <div className="session-summary">
          {user && <NotificationBell />}
          <button
            type="button"
            className="theme-toggle"
            onClick={toggleTheme}
            title={`Switch to ${theme === 'light' ? 'Dark' : 'Light'} theme`}
            aria-label={`Switch to ${theme === 'light' ? 'Dark' : 'Light'} theme`}
          >
            <span aria-hidden="true">{theme === 'light' ? '☀️' : '🌙'}</span>
            <span>{theme === 'light' ? 'Light' : 'Dark'}</span>
          </button>
          {user?.role === 'DOCTOR' && user?.verificationStatus === 'VERIFIED' && (
            <span className="status-badge status-badge--success" style={{ fontWeight: 700 }}>
              VERIFIED
            </span>
          )}
          <span>
            <strong>{user?.name}</strong>
            <small>{user ? roleLabel[user.role] : ''}</small>
          </span>
          <span className="avatar" aria-hidden="true">{initials(user?.name)}</span>
          <button type="button" className="button button--secondary" onClick={() => void signOut()}>
            Sign out
          </button>
        </div>
      </header>
      <nav className="primary-nav glass glass--thin" aria-label="Primary navigation">
        {visibleItems.map((item) => (
          <NavLink key={item.path} to={item.path} className={({ isActive }) => isActive ? 'active' : undefined}>
            {item.label}
          </NavLink>
        ))}
      </nav>
      <main id="main-content" className="main-content" tabIndex={-1}>
        {user?.role === 'MEMBER' && <HeadTransferBanner />}
        <Outlet />
      </main>
      {showEmergencyHelp && <EmergencyHelp />}
      <footer className="app-footer">
        Clinical decision-support system. Access is controlled and activity is audited.
      </footer>
    </div>
  )
}
