// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using System.Text.Json;
using FamilyVeda.Application.Common;
using FamilyVeda.Application.Triage;
using FamilyVeda.Domain.Clinical;
using FamilyVeda.Domain.Common;
using FamilyVeda.Domain.Identity;
using FamilyVeda.Domain.Triage;
using FamilyVeda.Infrastructure.Clinical;
using FamilyVeda.Infrastructure.Persistence;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace FamilyVeda.UnitTests;

public sealed class ClinicalCasePoolPrivacyTests
{
    [Fact]
    public async Task GetAvailableCases_BeforeGrant_ReturnsDeidentifiedItemsWithoutMemberId()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
        await using var db = new AppDbContext(options);
        var familyUser = new UserAccount { Email = "synthetic-pool-family@example.invalid", PasswordHash = "synthetic", DisplayName = "Synthetic Family User", UserType = UserType.FamilyUser };
        var doctorUser = new UserAccount { Email = "synthetic-pool-doctor@example.invalid", PasswordHash = "synthetic", DisplayName = "Synthetic Doctor", UserType = UserType.Doctor };
        var family = new Family { Name = "Synthetic Pool Family", CreatedByUser = familyUser };
        var member = new Member { Family = family, User = familyUser, DisplayName = "Synthetic Member", DateOfBirth = new DateOnly(1990, 1, 1), Role = FamilyRole.Head };
        var doctor = new Doctor { User = doctorUser, RegistrationNumberHash = "synthetic-hash", RegistrationNumberLastFour = "0001", VerificationStatus = VerificationStatus.Verified };
        var episode = new Episode { Member = member, SymptomsJson = "[\"synthetic_non_emergency_signal\"]", DurationDays = 1, Severity = 2 };
        var triageCase = new TriageCase { Member = member, Episode = episode, Status = TriageStatus.PendingDoctorReview, Priority = TriagePriority.Routine };
        db.AddRange(familyUser, doctorUser, family, member, doctor, episode, triageCase);
        await db.SaveChangesAsync();
        var service = new ClinicalService(
            db,
            new StubCurrentUser(doctorUser.Id),
            new StubNotifications(),
            new ConfigurationBuilder().AddInMemoryCollection().Build());

        var result = await service.GetAvailableCasesAsync(1, 20, CancellationToken.None);

        result.Items.Should().ContainSingle();
        using var json = JsonDocument.Parse(JsonSerializer.Serialize(result.Items.Single(), new JsonSerializerOptions(JsonSerializerDefaults.Web)));
        json.RootElement.TryGetProperty("memberId", out _).Should().BeFalse();
        json.RootElement.GetProperty("id").GetGuid().Should().Be(triageCase.Id);
    }

    private sealed class StubCurrentUser(Guid userId) : ICurrentUser
    {
        public bool IsAuthenticated => true;
        public Guid UserId => userId;
        public UserType UserType => UserType.Doctor;
    }

    private sealed class StubNotifications : INotificationService
    {
        public Task<NotificationSubscriptionDto> SubscribeAsync(NotificationSubscriptionRequest request, CancellationToken cancellationToken) => throw new NotSupportedException();
        public Task SendCaseStatusAsync(Guid caseId, TriageStatus status, CancellationToken cancellationToken) => Task.CompletedTask;
        public Task<PagedResult<NotificationDto>> GetInboxAsync(int page, int pageSize, CancellationToken cancellationToken) => throw new NotSupportedException();
    }
}
