// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using FamilyVeda.Application.Clinical;
using FamilyVeda.Application.Common;
using FamilyVeda.Application.Triage;
using FamilyVeda.Domain.Common;
using FamilyVeda.Domain.Identity;
using FamilyVeda.Domain.Triage;
using FamilyVeda.Infrastructure.Clinical;
using FamilyVeda.Infrastructure.Persistence;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace FamilyVeda.UnitTests;

public sealed class ClinicalEmergencyReferralTests
{
    [Fact]
    public async Task VerifiedDoctor_CanSeeAndAcknowledgeUnassignedEmergency_WithoutChangingPatientEmergencyStatus()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
        await using var db = new AppDbContext(options);
        var familyUser = User("synthetic-emergency-family@example.invalid", UserType.FamilyUser);
        var doctorUser = User("synthetic-emergency-clinician@example.invalid", UserType.Doctor);
        var family = new Family { Name = "Synthetic Emergency Family", CreatedByUser = familyUser };
        var member = new Member { Family = family, User = familyUser, DisplayName = "Synthetic Member", DateOfBirth = new DateOnly(1990, 1, 1), Role = FamilyRole.Head };
        var episode = new Episode { Member = member, SymptomsJson = "[\"difficulty breathing\"]", DurationDays = 0, Severity = 10 };
        var triageCase = new TriageCase { Member = member, Episode = episode, Status = TriageStatus.Escalated, Priority = TriagePriority.Emergency };
        db.AddRange(familyUser, doctorUser, family, member, episode, triageCase,
            new FamilyVeda.Domain.Clinical.Doctor { User = doctorUser, RegistrationNumberHash = "SYNTHETIC-HASH", RegistrationNumberLastFour = "0002", VerificationStatus = VerificationStatus.Verified });
        await db.SaveChangesAsync();
        var service = new ClinicalService(db, new StubCurrentUser(doctorUser.Id, UserType.Doctor), new StubNotifications(), new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string, string?> { ["Grants:ExpiryHours"] = "48" }).Build());

        var pool = await service.GetAvailableCasesAsync(1, 20, CancellationToken.None);
        await service.ClaimCaseAsync(triageCase.Id, CancellationToken.None);

        pool.Items.Should().ContainSingle(x => x.Id == triageCase.Id);
        triageCase.Status.Should().Be(TriageStatus.Escalated);
        (await db.CaseAccessGrants.CountAsync(x => x.TriageCaseId == triageCase.Id && x.RevokedAt == null)).Should().Be(1);
    }

    private static UserAccount User(string email, UserType type) => new() { Email = email, PasswordHash = "synthetic", DisplayName = "Synthetic User", UserType = type };

    private sealed class StubCurrentUser(Guid userId, UserType userType) : ICurrentUser
    {
        public bool IsAuthenticated => true;
        public Guid UserId => userId;
        public UserType UserType => userType;
    }

    private sealed class StubNotifications : INotificationService
    {
        public Task<NotificationSubscriptionDto> SubscribeAsync(NotificationSubscriptionRequest request, CancellationToken cancellationToken) => throw new NotSupportedException();
        public Task SendCaseStatusAsync(Guid caseId, TriageStatus status, CancellationToken cancellationToken) => Task.CompletedTask;
        public Task<PagedResult<NotificationDto>> GetInboxAsync(int page, int pageSize, CancellationToken cancellationToken) => throw new NotSupportedException();
    }
}
