// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// [S1] Family, Identity & Consent
using FamilyVeda.Domain.Common;
using FamilyVeda.Domain.Consent;

namespace FamilyVeda.UnitTests;

public sealed class ConsentStateMachineTests
{
    private static readonly DateTimeOffset Now = new(2026, 8, 4, 12, 0, 0, TimeSpan.Zero);

    [Fact]
    public void CanTransition_WhenGuardianConsentNeedsAdultReaffirmation_AllowsPendingState()
    {
        var canTransition = ConsentStateMachine.CanTransition(
            ConsentStatus.Granted,
            ConsentStatus.PendingReaffirmation);

        Assert.True(canTransition);
    }

    [Fact]
    public void CanTransition_WhenAdultPersonallyReaffirms_AllowsGrantedState()
    {
        var canTransition = ConsentStateMachine.CanTransition(
            ConsentStatus.PendingReaffirmation,
            ConsentStatus.Granted);

        Assert.True(canTransition);
    }

    [Fact]
    public void RequiresReaffirmation_WhenGuardianGrantedAndMemberTurnsEighteen_ReturnsTrue()
    {
        var dateOfBirth = new DateOnly(2008, 8, 4);

        var requiresReaffirmation = ConsentStateMachine.RequiresReaffirmation(
            dateOfBirth,
            guardianGranted: true,
            Now);

        Assert.True(requiresReaffirmation);
    }

    [Theory]
    [InlineData(2008, 8, 5, true)]
    [InlineData(2008, 8, 4, false)]
    public void RequiresReaffirmation_WhenMemberIsMinorOrConsentWasNotGuardianGranted_ReturnsFalse(
        int year,
        int month,
        int day,
        bool guardianGranted)
    {
        var dateOfBirth = new DateOnly(year, month, day);

        var requiresReaffirmation = ConsentStateMachine.RequiresReaffirmation(
            dateOfBirth,
            guardianGranted,
            Now);

        Assert.False(requiresReaffirmation);
    }
}
