// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using FamilyVeda.Application.Agents;
using FamilyVeda.Application.Records;
using FamilyVeda.Domain.Common;
using FamilyVeda.Domain.Identity;
using FamilyVeda.Domain.Records;
using FamilyVeda.Infrastructure.Agents;
using FamilyVeda.Infrastructure.Persistence;
using FamilyVeda.Infrastructure.Records;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace FamilyVeda.UnitTests;

public sealed class ToolDispatcherTests
{
    [Fact]
    public async Task DeniedTool_IsPersisted_AndThrowsHardError()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
        await using var db = new AppDbContext(options);
        var dispatcher = new ToolDispatcher(new ToolRegistry(), db, new StubOcr(), Options.Create(new StorageOptions()));
        var memberId = Guid.NewGuid(); var caseId = Guid.NewGuid();

        var action = () => dispatcher.InvokeAsync(AgentKind.Context, "read_raw_record", memberId, caseId, CancellationToken.None);

        await action.Should().ThrowAsync<ToolDeniedException>();
        var audit = await db.AuditLogs.SingleAsync();
        audit.EventType.Should().Be("TOOL_DENIED");
        audit.Outcome.Should().Be("DENIED");
        audit.SubjectMemberId.Should().Be(memberId);
    }

    [Fact]
    public async Task FamilialRisk_ReadsOnlyBiologicalRelativesWithCurrentConsent()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
        await using var db = new AppDbContext(options);
        var user = new UserAccount { Email = "synthetic-family@example.invalid", PasswordHash = "synthetic", DisplayName = "Synthetic User", UserType = UserType.FamilyUser };
        var family = new Family { Name = "Synthetic Family", CreatedByUser = user };
        var target = Member(family, "Target", new DateOnly(2000, 1, 1));
        var biological = Member(family, "Biological", new DateOnly(2000, 1, 1));
        var stepRelative = Member(family, "Step", new DateOnly(2000, 1, 1));
        var staleAdult = Member(family, "Stale", new DateOnly(1990, 1, 1));
        var unconfirmed = Member(family, "Unconfirmed", new DateOnly(2000, 1, 1));
        db.AddRange(user, family, target, biological, stepRelative, staleAdult, unconfirmed,
            new Relationship { Member = target, RelatedMember = biological, RelationshipType = "sibling", IsBiological = true },
            new Relationship { Member = target, RelatedMember = stepRelative, RelationshipType = "step sibling", IsBiological = false },
            new Relationship { Member = target, RelatedMember = staleAdult, RelationshipType = "sibling", IsBiological = true },
            new Relationship { Member = target, RelatedMember = unconfirmed, RelationshipType = "sibling", IsBiological = true });
        AddFlag(db, biological, "BIO", guardianGranted: false);
        AddFlag(db, stepRelative, "STEP", guardianGranted: false);
        AddFlag(db, staleAdult, "STALE", guardianGranted: true);
        AddFlag(db, unconfirmed, "UNCONFIRMED", guardianGranted: false, manuallyConfirmed: false);
        await db.SaveChangesAsync();
        var dispatcher = new ToolDispatcher(new ToolRegistry(), db, new StubOcr(), Options.Create(new StorageOptions()));

        var result = await dispatcher.InvokeAsync(AgentKind.FamilialRisk, "read_consented_hereditary_flags", target.Id, Guid.NewGuid(), CancellationToken.None);
        var json = System.Text.Json.JsonSerializer.Serialize(result);

        json.Should().Contain("BIO").And.NotContain("STEP").And.NotContain("STALE").And.NotContain("UNCONFIRMED");
        (await db.Consents.SingleAsync(x => x.MemberId == staleAdult.Id)).Status.Should().Be(ConsentStatus.PendingReaffirmation);
    }

    private static Member Member(Family family, string name, DateOnly dateOfBirth) => new()
    {
        Family = family,
        DisplayName = name,
        DateOfBirth = dateOfBirth,
        Role = FamilyRole.AdultMember
    };

    private static void AddFlag(AppDbContext db, Member member, string code, bool guardianGranted, bool manuallyConfirmed = true)
    {
        var record = new HealthRecord { Member = member, RecordType = RecordType.Condition, Title = "Synthetic finding", OccurredOn = new DateOnly(2026, 1, 1) };
        db.AddRange(
            record,
            new Domain.Identity.Consent
            {
                Member = member,
                Category = ConsentCategory.HereditaryFlags,
                Status = ConsentStatus.Granted,
                GrantedByGuardian = guardianGranted
            },
            new HereditaryFlag
            {
                Member = member,
                HealthRecord = record,
                ConditionCode = code,
                Finding = "Synthetic screening flag",
                Confidence = 0.9m,
                ManuallyConfirmed = manuallyConfirmed
            });
    }

    private sealed class StubOcr : IOcrService
    {
        public Task<string> ExtractTextAsync(string filePath, CancellationToken cancellationToken) => Task.FromResult(string.Empty);
    }
}
