// Owner: S3 · Triage & Agent Orchestration — Karunathilaka K.D.J.C (IT24100551)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using FamilyVeda.Api.Background;
using FamilyVeda.Domain.Common;
using FamilyVeda.Domain.Identity;
using FamilyVeda.Domain.Triage;
using FamilyVeda.Infrastructure.Persistence;
using FamilyVeda.Infrastructure.Triage;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;

namespace FamilyVeda.UnitTests;

public sealed class TriageWorkerRecoveryTests
{
    [Fact]
    public async Task Recovery_ReturnsMoreThanChannelCapacity_WithoutBlockingStartup()
    {
        var services = new ServiceCollection();
        var databaseName = Guid.NewGuid().ToString();
        services.AddDbContext<AppDbContext>(options => options.UseInMemoryDatabase(databaseName));
        using var provider = services.BuildServiceProvider();
        await using (var scope = provider.CreateAsyncScope())
        {
            var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();
            var user = new UserAccount { Email = "synthetic-recovery@example.invalid", PasswordHash = "synthetic", DisplayName = "Synthetic User", UserType = UserType.FamilyUser };
            var family = new Family { Name = "Synthetic Recovery Family", CreatedByUser = user };
            var member = new Member { Family = family, User = user, DisplayName = "Synthetic Member", DateOfBirth = new DateOnly(1990, 1, 1), Role = FamilyRole.Head };
            for (var index = 0; index < 101; index++)
            {
                var episode = new Episode { Member = member, SymptomsJson = "[]", DurationDays = 1, Severity = 1 };
                dbContext.TriageCases.Add(new TriageCase { Episode = episode, Member = member, Status = TriageStatus.Submitted });
            }
            await dbContext.SaveChangesAsync();
        }

        var worker = new TriageWorker(new TriageWorkQueue(), provider.GetRequiredService<IServiceScopeFactory>(), NullLogger<TriageWorker>.Instance);
        var recovered = await worker.RecoverInterruptedCasesAsync(CancellationToken.None).WaitAsync(TimeSpan.FromSeconds(2));

        recovered.Should().HaveCount(101);
        await using var verificationScope = provider.CreateAsyncScope();
        var statuses = await verificationScope.ServiceProvider.GetRequiredService<AppDbContext>().TriageCases.Select(x => x.Status).ToListAsync();
        statuses.Should().OnlyContain(status => status == TriageStatus.Planning);
    }
}
