// Owner: S3 · Triage & Agent Orchestration — Karunathilaka K.D.J.C (IT24100551)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
using FamilyVeda.Application.Triage;
using FamilyVeda.Domain.Common;
using FamilyVeda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace FamilyVeda.Infrastructure.Triage;

public sealed class CaseSlaProcessor(AppDbContext dbContext, INotificationService notifications, IConfiguration configuration) : ICaseSlaProcessor
{
    public Task<int> ProcessOverdueCasesAsync(CancellationToken cancellationToken) =>
        dbContext.Database.CreateExecutionStrategy().ExecuteAsync(() => ProcessOverdueCasesAsyncCore(cancellationToken));

    private async Task<int> ProcessOverdueCasesAsyncCore(CancellationToken cancellationToken)
    {
        var cutoff = DateTimeOffset.UtcNow.AddHours(-configuration.GetValue("Sla:DoctorResponseHours", 6));
        var overdue = await dbContext.TriageCases.Where(x =>
                (x.Status == TriageStatus.PendingDoctorReview || x.Status == TriageStatus.LowConfidence || x.Status == TriageStatus.Claimed) &&
                x.CreatedAt <= cutoff && x.FailureCode != "DOCTOR_RESPONSE_DELAY")
            .ToListAsync(cancellationToken);
        var count = 0;
        foreach (var triageCase in overdue)
        {
            await using (var gate = await CaseLifecycleLock.AcquireAsync(dbContext, triageCase.Id, cancellationToken))
            {
                await dbContext.Entry(triageCase).ReloadAsync(cancellationToken);
                if (triageCase.Status is not (TriageStatus.PendingDoctorReview or TriageStatus.LowConfidence or TriageStatus.Claimed) || triageCase.FailureCode == "DOCTOR_RESPONSE_DELAY") continue;
                triageCase.FailureCode = "DOCTOR_RESPONSE_DELAY";
                await dbContext.SaveChangesAsync(cancellationToken);
                await gate.CompleteAsync(cancellationToken);
                count++;
            }
            await notifications.SendCaseStatusAsync(triageCase.Id, triageCase.Status, cancellationToken);
        }
        return count;
    }
}
