// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import axios, { AxiosError, type InternalAxiosRequestConfig } from 'axios'

type Tokens = { accessToken: string; refreshToken: string }
let tokens: Tokens | null = null
let refreshPromise: Promise<Tokens> | null = null
const baseURL = import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:5000/api/v1'

export const apiClient = axios.create({ baseURL, timeout: 15_000 })

/**
 * The hosted API sleeps when idle and takes up to a minute to wake. Calling this as the app opens
 * starts the wake-up while the person is still signing in. It carries no credentials and its
 * result is ignored: a failure here changes nothing, the real requests report their own errors.
 */
export function warmUpApi() {
  void fetch(`${baseURL.replace(/\/api\/v1\/?$/, '')}/health`, { mode: 'no-cors', cache: 'no-store' }).catch(() => undefined)
}

// Only the refresh token is kept, and only for the life of the tab: a reload restores the session,
// closing the tab ends it. The access token never leaves memory.
const refreshTokenKey = 'familyveda.refreshToken'

function readStoredRefreshToken(): string | null {
  try {
    return sessionStorage.getItem(refreshTokenKey)
  } catch {
    return null
  }
}

function storeRefreshToken(refreshToken: string | null) {
  try {
    if (refreshToken) sessionStorage.setItem(refreshTokenKey, refreshToken)
    else sessionStorage.removeItem(refreshTokenKey)
  } catch {
    // Storage can be blocked (private mode, site data disabled); the session then lasts until reload.
  }
}

export function hasStoredSession() {
  return readStoredRefreshToken() !== null
}

export function setSessionTokens(next: Tokens | null) {
  tokens = next
  storeRefreshToken(next?.refreshToken ?? null)
}

apiClient.interceptors.request.use((config: InternalAxiosRequestConfig) => {
  if (tokens?.accessToken) config.headers.Authorization = `Bearer ${tokens.accessToken}`
  return config
})

apiClient.interceptors.response.use(undefined, async (error: AxiosError) => {
  const original = error.config as (InternalAxiosRequestConfig & { _retried?: boolean }) | undefined
  if (error.response?.status !== 401 || !original || original._retried || !tokens?.refreshToken) throw error

  original._retried = true
  refreshPromise ??= axios.post<AuthResponse>(`${baseURL}/auth/refresh`, { refreshToken: tokens.refreshToken })
    .then(({ data }) => {
      const next = { accessToken: data.accessToken, refreshToken: data.refreshToken }
      setSessionTokens(next)
      return next
    })
    .finally(() => { refreshPromise = null })

  try {
    const next = await refreshPromise
    original.headers.Authorization = `Bearer ${next.accessToken}`
    return apiClient(original)
  } catch {
    setSessionTokens(null)
    window.dispatchEvent(new Event('familyveda:session-expired'))
    throw error
  }
})

/**
 * Re-issues the session from the server (e.g. after the Family Head role changes hands), so the new
 * role reaches the UI without signing in again. Returns null when there is no session to refresh.
 */
export async function refreshSession(): Promise<AuthResponse | null> {
  if (!tokens?.refreshToken) return null
  const { data } = await axios.post<AuthResponse>(`${baseURL}/auth/refresh`, { refreshToken: tokens.refreshToken })
  setSessionTokens({ accessToken: data.accessToken, refreshToken: data.refreshToken })
  return data
}

/**
 * Re-issues the session after a page reload from the refresh token kept for this tab. Returns null
 * when there is nothing to restore or the server no longer accepts the token.
 */
export async function restoreStoredSession(): Promise<AuthResponse | null> {
  const refreshToken = readStoredRefreshToken()
  if (!refreshToken) return null
  try {
    // The hosted API can take up to a minute to wake, so this waits longer than a normal request.
    const { data } = await axios.post<AuthResponse>(`${baseURL}/auth/refresh`, { refreshToken }, { timeout: 70_000 })
    setSessionTokens({ accessToken: data.accessToken, refreshToken: data.refreshToken })
    return data
  } catch (error) {
    // A rejected token is discarded; a network failure keeps it so the next reload can try again.
    if (axios.isAxiosError(error) && error.response) setSessionTokens(null)
    return null
  }
}

export type AuthResponse = {
  userId: string
  displayName: string
  userType: 'FamilyUser' | 'Doctor' | 'Admin'
  familyRole?: 'Head' | 'AdultMember' | 'MinorMember' | null
  doctorVerificationStatus?: 'Pending' | 'Verified' | 'MoreInformationRequired' | 'Rejected' | 'Suspended' | null
  familyHeadVerificationStatus?: 'Pending' | 'Verified' | 'MoreInformationRequired' | 'Rejected' | 'Suspended' | null
  familyCode?: string | null
  accessToken: string
  refreshToken: string
  accessTokenExpiresAt: string
}

export type MemberDto = { id: string; familyId: string; displayName: string; dateOfBirth: string; role: string; isSelf?: boolean; sexForClinicalReference?: 'NotSpecified' | 'Male' | 'Female' }
export type FamilyDto = { id: string; name: string; members: MemberDto[]; familyCode?: string | null }
export type PagedResult<T> = { items: T[]; page: number; pageSize: number; totalCount: number; totalPages: number }
export type HealthRecordDto = { id: string; memberId: string; recordType: string; title: string; summary?: string; occurredOn: string; sharedWithFamilyHead?: boolean }
export type EpisodeDto = { id: string; memberId: string; symptoms: string[]; durationDays: number; severity: number; notes?: string; createdAt: string }
// caseNumber and the names are optional so an older API build still renders; names arrive only for cases the doctor holds a grant on.
export type TriageCaseDto = { id: string; episodeId: string; memberId: string; status: string; priority: string; createdAt: string; caseNumber?: number; memberDisplayName?: string | null; familyName?: string | null }
export type AvailableCaseDto = { id: string; priority: string; createdAt: string; status?: string; caseNumber?: number }
export type AuditDto = { id: string; eventType: string; resourceType: string; resourceId?: string; outcome: string; createdAt: string }
export type FamilyDashboardDto = { membersVisible: number; openCases: number; awaitingDoctorReview: number; approvedCases: number; recordsCount: number }
export type AgentTraceDto = { stepNumber: number; agent: string; status: string; toolsRequested: string[]; toolsAllowed: string[]; toolsDenied: string[]; confidence: number; latencyMilliseconds: number; outputSchemaValid: boolean }
export type ApprovalDto = { id: string; triageCaseId: string; doctorId: string; action: string; decidedAt: string }
export type CaseReviewDto = { id: string; memberId: string; status: string; priority: string; contextJson?: string; analysisJson?: string; familialRiskJson?: string; draftAdvisoryJson?: string; traces: AgentTraceDto[]; submittedEpisode?: { id: string; memberId: string; symptoms: string[]; durationDays: number; severity: number; notes?: string | null; createdAt: string } | null; caseNumber?: number; memberDisplayName?: string | null; familyName?: string | null }
export type ConsentDto = { id: string; memberId: string; category: string; status: string; grantedByGuardian: boolean }
export type RelationshipDto = { id: string; memberId: string; relatedMemberId: string; relationshipType: string; isBiological: boolean }
export type DoctorDto = { id: string; userId: string; registrationNumberLastFour: string; verificationStatus: string; specialty?: string; hospitalClinic?: string; phoneNumber?: string; displayName?: string; email?: string; registrationNumber?: string }
export type FamilyHeadDto = { id: string; userId: string; familyId: string; familyName: string; displayName: string; email: string; memberCount: number; verificationStatus: string; isActive: boolean; createdAt: string; nic?: string | null; address?: string | null; familyCode?: string | null }
export type AdminUserDto = { userId: string; email: string; displayName: string; userType: string; isActive: boolean; createdAt: string; status?: string; roleDetail?: string }
export type ResetPasswordResponse = { success: boolean; message: string; resetToken?: string | null }

export type LabRangeSummaryDto = { belowRange: number; withinRange: number; aboveRange: number; rangeUnavailable: number }
export type LabReportDto = { id: string; memberId: string; originalFileName: string; ocrStatus: string; collectedAt?: string; sharedWithFamilyHead?: boolean; hasOriginalFile?: boolean; rangeSummary?: LabRangeSummaryDto | null }
export type DeletedLabReportDto = { id: string; memberId: string; originalFileName: string; contentType: string; ocrStatus: string; collectedAt?: string | null; deletedAt: string; canDeletePermanently: boolean }
export type LabValueDto = { id: string; analyte: string; value: number; unit: string; referenceLow?: number | null; referenceHigh?: number | null; wasManuallyConfirmed: boolean; rangeStatus?: 'RangeUnavailable' | 'BelowRange' | 'WithinRange' | 'AboveRange' }
export type HereditaryFlagDto = { id: string; memberId: string; conditionCode: string; finding: string; confidence: number; manuallyConfirmed: boolean }
export type LabReportDetailDto = LabReportDto & { values: LabValueDto[]; flags: HereditaryFlagDto[] }
export type VitalDto = { id: string; memberId: string; vitalType: string; value: number; unit: string; measuredAt: string }
export type VitalTrendDto = { vitalType: string; points: Array<{ measuredAt: string; value: number; unit: string }> }
export type ApprovedGuidanceDto = { caseId: string; status: string; finalAdvisory: string; approvedAt: string; disclaimer: string }

// ===== S4 three-portal additions (docs/Three_Portal_Feature_Spec.md) =====
export type JoinRequestDto = {
  id: string
  familyId: string
  familyName: string
  requesterDisplayName: string
  requesterEmailMasked: string
  relationshipType: string
  message?: string | null
  status: 'Pending' | 'Accepted' | 'Declined' | 'Cancelled' | 'Expired'
  createdAt: string
  respondedAt?: string | null
}
export type DoctorSummaryDto = {
  id: string
  displayName: string
  specialty?: string | null
  clinic?: string | null
  district?: string | null
  city?: string | null
  languages?: string | null
}
export type DoctorRequestDto = {
  id: string
  familyId: string
  familyName: string
  memberCount: number
  doctor: DoctorSummaryDto
  message?: string | null
  status: 'Pending' | 'Accepted' | 'Declined' | 'Cancelled'
  createdAt: string
}
export type AppointmentDto = {
  id: string
  memberId: string
  memberDisplayName: string
  familyName: string
  doctor: DoctorSummaryDto
  startsAt: string
  durationMinutes: number
  reason: string
  status: 'Requested' | 'Confirmed' | 'Completed' | 'Cancelled' | 'NoShow'
  doctorNote?: string | null
  createdAt: string
}
export type NotificationDto = {
  id: string
  type: string
  title: string
  body: string
  linkPath?: string | null
  readAt?: string | null
  createdAt: string
}
export type FamilyDashboardSummaryDto = {
  role: string
  familyId: string
  familyName: string
  familyCode?: string | null
  memberCount: number
  minorCount: number
  pendingJoinRequests?: number
  nextAppointment?: AppointmentDto | null
  openCases: number
  approvedGuidanceCount: number
  familyDoctor?: DoctorSummaryDto | null
  unreadNotifications: number
  recentActivity: string[]
  // Mockup-aligned additions (2026-09-28); optional so older API builds still render.
  viewerDisplayName?: string
  members?: DashboardMemberDto[]
  activity?: DashboardActivityDto[]
  visibleReportCount?: number
  latestLab?: DashboardLabSummaryDto | null
  latestVital?: DashboardVitalDto | null
  upcomingAppointments?: number
}
export type DashboardMemberDto = { id: string; displayName: string; role: string; isSelf: boolean; isMinor: boolean; summary: string }
export type DashboardActivityDto = { title: string; subject?: string | null; occurredAt: string }
export type DashboardLabSummaryDto = {
  id: string
  memberDisplayName: string
  fileName: string
  collectedAt?: string | null
  belowRange: number
  withinRange: number
  aboveRange: number
  rangeUnavailable: number
  confirmed: boolean
}
export type DashboardVitalDto = { vitalType: string; value: number; unit: string; measuredAt: string }
export type DoctorFamilyRowDto = { familyId: string; familyName: string; memberCount: number; lastVisit?: string | null; nextAppointment?: string | null }
export type DoctorDashboardSummaryDto = {
  todayAppointments: AppointmentDto[]
  pendingApprovals: number
  openCases: number
  pendingFamilyRequests: number
  assignedFamilies: number
  unreadNotifications: number
  doctorDisplayName?: string
  specialty?: string | null
  verificationStatus?: string
  priorityOpenCases?: number
  families?: DoctorFamilyRowDto[]
  activity?: DashboardActivityDto[]
}

// ===== Family lifecycle (FH-2, DECISIONS 2026-09-29c) =====
/** Family-level roster: names and roles only, never another adult's DOB or health data. */
export type RosterMemberDto = { id: string; displayName: string; role: 'Head' | 'AdultMember' | 'MinorMember'; isMinor: boolean; isSelf: boolean; hasAccount: boolean }
export type FamilyInvitationSummaryDto = {
  id: string
  emailMasked?: string | null
  relationshipType?: string | null
  status: 'Pending' | 'Accepted' | 'Cancelled' | 'Expired'
  createdAt: string
  expiresAt: string
}
export type FamilyInvitationDto = { id: string; token: string; expiresAt: string }
export type MembershipChangeDto = { memberId: string; familyId: string; familyName: string; familyCode?: string | null }
export type HeadTransferDto = {
  id: string
  familyId: string
  familyName: string
  fromMemberId: string
  fromDisplayName: string
  toMemberId: string
  toDisplayName: string
  status: 'Pending' | 'Accepted' | 'Declined' | 'Cancelled'
  createdAt: string
  respondedAt?: string | null
}

/** An invitation sent to the signed-in user's own email; approved or rejected in-app without a token. */
export interface IncomingInvitationDto {
  id: string
  familyName: string
  invitedByName: string
  relationshipType?: string | null
  createdAt: string
  expiresAt: string
  canApprove: boolean
  blockedReason?: string | null
}

export const familyLifecycleApi = {
  getIncomingInvitations: () => apiClient.get<IncomingInvitationDto[]>('/invitations/incoming'),
  approveInvitation: (invitationId: string) => apiClient.post<MembershipChangeDto>(`/invitations/${invitationId}/approve`),
  rejectInvitation: (invitationId: string) => apiClient.post(`/invitations/${invitationId}/reject`),
  getRoster: (familyId: string) => apiClient.get<RosterMemberDto[]>(`/families/${familyId}/roster`),
  getInvitations: (familyId: string) => apiClient.get<FamilyInvitationSummaryDto[]>(`/families/${familyId}/invitations`),
  createInvitation: (familyId: string, body: { email: string; relationshipType?: string }) =>
    apiClient.post<FamilyInvitationDto>(`/families/${familyId}/invitations`, body),
  resendInvitation: (familyId: string, invitationId: string, email: string) =>
    apiClient.post<FamilyInvitationDto>(`/families/${familyId}/invitations/${invitationId}/resend`, { email }),
  cancelInvitation: (familyId: string, invitationId: string) =>
    apiClient.post(`/families/${familyId}/invitations/${invitationId}/cancel`),
  removeFromFamily: (memberId: string) => apiClient.post<MembershipChangeDto>(`/members/${memberId}/remove-from-family`),
  leaveFamily: (startOwnFamily: boolean) => apiClient.post<MembershipChangeDto>('/families/me/leave', { startOwnFamily }),
  renameFamily: (familyId: string, name: string) => apiClient.put<FamilyDto>(`/families/${familyId}`, { name }),
  // FH-3 Family Head transfer. GET endpoints answer 204 (empty body) when nothing is waiting.
  proposeHeadTransfer: (familyId: string, toMemberId: string) =>
    apiClient.post<HeadTransferDto>(`/families/${familyId}/head-transfers`, { toMemberId }),
  getPendingHeadTransfer: (familyId: string) => apiClient.get<HeadTransferDto | ''>(`/families/${familyId}/head-transfers/pending`),
  getIncomingHeadTransfer: () => apiClient.get<HeadTransferDto | ''>('/families/head-transfers/incoming'),
  acceptHeadTransfer: (id: string) => apiClient.post<HeadTransferDto>(`/families/head-transfers/${id}/accept`),
  declineHeadTransfer: (id: string) => apiClient.post<HeadTransferDto>(`/families/head-transfers/${id}/decline`),
  cancelHeadTransfer: (id: string) => apiClient.post<HeadTransferDto>(`/families/head-transfers/${id}/cancel`),
}

export const threePortalApi = {
  getFamilyDashboard: () => apiClient.get<FamilyDashboardSummaryDto>('/dashboard/family'),
  getDoctorDashboard: () => apiClient.get<DoctorDashboardSummaryDto>('/dashboard/doctor'),

  submitJoinRequest: (body: { familyCode: string; relationshipType: string; message?: string }) =>
    apiClient.post<JoinRequestDto>('/families/join-requests', body),
  getMyJoinRequests: () => apiClient.get<JoinRequestDto[]>('/families/join-requests/mine'),
  getFamilyJoinRequests: (familyId: string, status = 'Pending') =>
    apiClient.get<JoinRequestDto[]>(`/families/${familyId}/join-requests`, { params: { status } }),
  acceptJoinRequest: (id: string) => apiClient.post(`/families/join-requests/${id}/accept`),
  declineJoinRequest: (id: string) => apiClient.post(`/families/join-requests/${id}/decline`),

  getDoctorDirectory: (params?: { search?: string; district?: string }) =>
    apiClient.get<DoctorSummaryDto[]>('/doctors/directory', { params }),
  getFamilyDoctor: (familyId: string) => apiClient.get<DoctorSummaryDto | null>(`/families/${familyId}/doctor`),
  requestFamilyDoctor: (familyId: string, body: { doctorId: string; message?: string }) =>
    apiClient.post<DoctorRequestDto>(`/families/${familyId}/doctor-requests`, body),
  getPendingFamilyDoctorRequest: (familyId: string) =>
    apiClient.get<DoctorRequestDto | null>(`/families/${familyId}/doctor-requests/pending`),
  cancelFamilyDoctorRequest: (familyId: string, id: string) =>
    apiClient.post<DoctorRequestDto>(`/families/${familyId}/doctor-requests/${id}/cancel`),
  getMyFamilyDoctorRequests: () => apiClient.get<DoctorRequestDto[]>('/doctors/me/family-requests'),
  acceptFamilyDoctorRequest: (id: string) => apiClient.post(`/doctors/me/family-requests/${id}/accept`),
  declineFamilyDoctorRequest: (id: string) => apiClient.post(`/doctors/me/family-requests/${id}/decline`),

  bookAppointment: (body: { memberId: string; startsAt: string; durationMinutes?: number; reason: string }) =>
    apiClient.post<AppointmentDto>('/appointments', body),
  getMyAppointments: () => apiClient.get<AppointmentDto[]>('/appointments/mine'),
  cancelAppointment: (id: string) => apiClient.post(`/appointments/${id}/cancel`),
  getDoctorAppointments: (params?: { from?: string; to?: string }) =>
    apiClient.get<AppointmentDto[]>('/doctors/me/appointments', { params }),
  setAppointmentStatus: (id: string, action: 'confirm' | 'complete' | 'no-show' | 'cancel', note?: string) =>
    apiClient.post<AppointmentDto>(`/doctors/me/appointments/${id}/${action}`, { note }),

  getNotifications: (unreadOnly?: boolean) =>
    apiClient.get<NotificationDto[]>('/notifications', { 
      params: { 
        ...(unreadOnly ? { unreadOnly: true } : {}),
        // Cache-buster to prevent stale bell counts
        _t: Date.now()
      } 
    }),
  markNotificationRead: (id: string) => apiClient.post(`/notifications/${id}/read`),
}

// ===== Doctor workspace (DECISIONS 2026-09-29h) =====
export type WeekDay = 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday'
export type AvailabilityWindowDto = { dayOfWeek: WeekDay; startTime: string; endTime: string }
export type BlockedTimeDto = { id: string; startsAt: string; endsAt: string; reason?: string | null }
export type DoctorScheduleDto = { slotMinutes: number; windows: AvailabilityWindowDto[]; blocked: BlockedTimeDto[] }
export type DoctorSlotsDto = { date: string; availabilityConfigured: boolean; slotMinutes: number; slots: string[] }
export type DoctorPracticeProfileDto = {
  id: string; displayName: string; email?: string | null; registrationNumberLastFour: string; verificationStatus: string
  specialty?: string | null; clinic?: string | null; phoneNumber?: string | null; district?: string | null; city?: string | null
  languages?: string | null; consultationModes?: string | null; acceptingNewFamilies: boolean; slotMinutes: number
}
export type UpdatePracticeProfileRequest = Omit<DoctorPracticeProfileDto, 'id' | 'displayName' | 'email' | 'registrationNumberLastFour' | 'verificationStatus'>
export type DoctorRosterMemberDto = { id: string; displayName: string; role: string; clinicalAccess: boolean }
export type FamilyRosterForDoctorDto = { familyId: string; familyName: string; members: DoctorRosterMemberDto[] }
export type ClinicalNoteDto = { id: string; familyId: string; memberId?: string | null; appointmentId?: string | null; noteType: 'VisitNote' | 'FamilyNote' | 'FollowUp'; content: string; version: number; amendsNoteId?: string | null; createdAt: string }
export type WorkspaceLabValueDto = { analyte: string; value: number; unit: string; referenceLow?: number | null; referenceHigh?: number | null; rangeStatus: 'RangeUnavailable' | 'BelowRange' | 'WithinRange' | 'AboveRange'; confirmed: boolean }
export type RangeStatus = WorkspaceLabValueDto['rangeStatus']
export type VitalTrend = 'NotEnoughReadings' | 'Falling' | 'Stable' | 'Rising'
/** Range and trend are computed by the backend rule table; older API builds omit them. */
export type WorkspaceVitalDto = {
  vitalType: string; value: number; unit: string; measuredAt: string
  referenceLow?: number | null; referenceHigh?: number | null; rangeStatus?: RangeStatus; trend?: VitalTrend; rangeSource?: string | null
}
export type VitalReferenceDto = { vitalType: string; label: string; unit: string; low: number; high: number; ageBand: string; source: string }
export type MemberWorkspaceDto = {
  memberId: string; displayName: string; role: string; familyId: string; familyName: string
  clinicalAccess: boolean; accessBasis: string; accessExpiresAt?: string | null; consentedCategories: string[]
  records?: Array<{ id: string; recordType: string; title: string; summary?: string | null; occurredOn: string }> | null
  labReports?: Array<{ id: string; fileName: string; collectedAt?: string | null; hasOriginalFile?: boolean; values: WorkspaceLabValueDto[] }> | null
  vitals?: WorkspaceVitalDto[] | null
  hereditaryFlags?: Array<{ conditionCode: string; finding: string; confirmed: boolean }> | null
  visits: Array<{ appointmentId: string; startsAt: string; reason: string; status: AppointmentDto['status'] }>
  notes: ClinicalNoteDto[]
  ageYears?: number | null; sexForClinicalReference?: string | null; vitalReferences?: VitalReferenceDto[] | null
}

export const doctorWorkspaceApi = {
  getProfile: () => apiClient.get<DoctorPracticeProfileDto>('/doctors/me/profile'),
  updateProfile: (body: UpdatePracticeProfileRequest) => apiClient.put<DoctorPracticeProfileDto>('/doctors/me/profile', body),
  getSchedule: () => apiClient.get<DoctorScheduleDto>('/doctors/me/schedule'),
  replaceAvailability: (windows: AvailabilityWindowDto[]) => apiClient.put<DoctorScheduleDto>('/doctors/me/availability', { windows }),
  addBlockedTime: (body: { startsAt: string; endsAt: string; reason?: string }) => apiClient.post<BlockedTimeDto>('/doctors/me/blocked-time', body),
  removeBlockedTime: (id: string) => apiClient.delete(`/doctors/me/blocked-time/${id}`),
  reschedule: (appointmentId: string, startsAt: string, note?: string) =>
    apiClient.post<AppointmentDto>(`/doctors/me/appointments/${appointmentId}/reschedule`, { startsAt, note }),
  getFamilyRoster: (familyId: string) => apiClient.get<FamilyRosterForDoctorDto>(`/doctors/me/families/${familyId}`),
  getMemberWorkspace: (memberId: string) => apiClient.get<MemberWorkspaceDto>(`/doctors/me/members/${memberId}`),
  addNote: (memberId: string, body: { content: string; noteType: ClinicalNoteDto['noteType']; appointmentId?: string }) =>
    apiClient.post<ClinicalNoteDto>(`/doctors/me/members/${memberId}/notes`, body),
  amendNote: (noteId: string, content: string) => apiClient.post<ClinicalNoteDto>(`/doctors/me/notes/${noteId}/amend`, { content }),
  getFamilyDoctorSlots: (familyId: string, date: string) => apiClient.get<DoctorSlotsDto>(`/families/${familyId}/doctor/slots`, { params: { date } }),
}

/** The signed-in user's own profile (every portal). Family fields appear only for family users. */
export interface MyProfileDto {
  userId: string
  email: string
  displayName: string
  userType: 'FamilyUser' | 'Doctor' | 'Admin' | string
  createdAt: string
  familyRole?: string | null
  familyName?: string | null
  familyCode?: string | null
  dateOfBirth?: string | null
  sexForClinicalReference?: string | null
}

export const profileApi = {
  getMine: () => apiClient.get<MyProfileDto>('/profile/me'),
  updateMine: (displayName: string) => apiClient.put<MyProfileDto>('/profile/me', { displayName }),
  changePassword: (currentPassword: string, newPassword: string) =>
    apiClient.post('/auth/change-password', { currentPassword, newPassword }),
}
