// Owner: S1 · Family, Identity & Consent — Samaranayaka S.G.V.S (IT23544154)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import axios, { AxiosError, type InternalAxiosRequestConfig } from 'axios'

type Tokens = { accessToken: string; refreshToken: string }
let tokens: Tokens | null = null
let refreshPromise: Promise<Tokens> | null = null
const baseURL = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:5000/api/v1'

export const apiClient = axios.create({ baseURL, timeout: 15_000 })

export function setSessionTokens(next: Tokens | null) {
  tokens = next
}

apiClient.interceptors.request.use((config: InternalAxiosRequestConfig) => {
  if (tokens?.accessToken) config.headers.Authorization = `Bearer ${tokens.accessToken}`
  return config
})

apiClient.interceptors.response.use(undefined, async (error: AxiosError) => {
  const original = error.config as (InternalAxiosRequestConfig & { _retried?: boolean }) | undefined
  if (error.response?.status !== 401 || !original || original._retried || !tokens?.refreshToken) throw error

  original._retried = true
  refreshPromise ??= axios.post<AuthResponse>(`${baseURL}/auth/refresh`, { refreshToken: tokens.refreshToken })
    .then(({ data }) => {
      const next = { accessToken: data.accessToken, refreshToken: data.refreshToken }
      setSessionTokens(next)
      return next
    })
    .finally(() => { refreshPromise = null })

  try {
    const next = await refreshPromise
    original.headers.Authorization = `Bearer ${next.accessToken}`
    return apiClient(original)
  } catch {
    setSessionTokens(null)
    window.dispatchEvent(new Event('familyveda:session-expired'))
    throw error
  }
})

export type AuthResponse = {
  userId: string
  displayName: string
  userType: 'FamilyUser' | 'Doctor' | 'Admin'
  familyRole?: 'Head' | 'AdultMember' | 'MinorMember' | null
  doctorVerificationStatus?: 'Pending' | 'Verified' | 'MoreInformationRequired' | 'Rejected' | 'Suspended' | null
  familyHeadVerificationStatus?: 'Pending' | 'Verified' | 'MoreInformationRequired' | 'Rejected' | 'Suspended' | null
  familyCode?: string | null
  accessToken: string
  refreshToken: string
  accessTokenExpiresAt: string
}

export type MemberDto = { id: string; familyId: string; displayName: string; dateOfBirth: string; role: string; isSelf?: boolean }
export type FamilyDto = { id: string; name: string; members: MemberDto[] }
export type PagedResult<T> = { items: T[]; page: number; pageSize: number; totalCount: number; totalPages: number }
export type HealthRecordDto = { id: string; memberId: string; recordType: string; title: string; summary?: string; occurredOn: string }
export type EpisodeDto = { id: string; memberId: string; symptoms: string[]; durationDays: number; severity: number; notes?: string; createdAt: string }
export type TriageCaseDto = { id: string; episodeId: string; memberId: string; status: string; priority: string; createdAt: string }
export type AvailableCaseDto = { id: string; priority: string; createdAt: string }
export type AuditDto = { id: string; eventType: string; resourceType: string; resourceId?: string; outcome: string; createdAt: string }
export type FamilyDashboardDto = { membersVisible: number; openCases: number; awaitingDoctorReview: number; approvedCases: number; recordsCount: number }
export type AgentTraceDto = { stepNumber: number; agent: string; status: string; toolsRequested: string[]; toolsAllowed: string[]; toolsDenied: string[]; confidence: number; latencyMilliseconds: number; outputSchemaValid: boolean }
export type ApprovalDto = { id: string; triageCaseId: string; doctorId: string; action: string; decidedAt: string }
export type CaseReviewDto = { id: string; memberId: string; status: string; priority: string; contextJson?: string; analysisJson?: string; familialRiskJson?: string; draftAdvisoryJson?: string; traces: AgentTraceDto[] }
export type ConsentDto = { id: string; memberId: string; category: string; status: string; grantedByGuardian: boolean }
export type RelationshipDto = { id: string; memberId: string; relatedMemberId: string; relationshipType: string; isBiological: boolean }
export type DoctorDto = { id: string; userId: string; registrationNumberLastFour: string; verificationStatus: string; specialty?: string; hospitalClinic?: string; phoneNumber?: string; displayName?: string; email?: string; registrationNumber?: string }
export type FamilyHeadDto = { id: string; userId: string; familyId: string; familyName: string; displayName: string; email: string; memberCount: number; verificationStatus: string; isActive: boolean; createdAt: string; nic?: string | null; address?: string | null; familyCode?: string | null }
export type AdminUserDto = { userId: string; email: string; displayName: string; userType: string; isActive: boolean; createdAt: string; status?: string; roleDetail?: string }
export type ResetPasswordResponse = { success: boolean; message: string; resetToken?: string | null }

export type LabReportDto = { id: string; memberId: string; originalFileName: string; ocrStatus: string; collectedAt?: string }
export type LabValueDto = { id: string; analyte: string; value: number; unit: string; referenceLow?: number | null; referenceHigh?: number | null; wasManuallyConfirmed: boolean; rangeStatus?: 'RangeUnavailable' | 'BelowRange' | 'WithinRange' | 'AboveRange' }
export type HereditaryFlagDto = { id: string; memberId: string; conditionCode: string; finding: string; confidence: number; manuallyConfirmed: boolean }
export type LabReportDetailDto = LabReportDto & { values: LabValueDto[]; flags: HereditaryFlagDto[] }
export type VitalDto = { id: string; memberId: string; vitalType: string; value: number; unit: string; measuredAt: string }
export type VitalTrendDto = { vitalType: string; points: Array<{ measuredAt: string; value: number; unit: string }> }
export type ApprovedGuidanceDto = { caseId: string; status: string; finalAdvisory: string; approvedAt: string; disclaimer: string }

// ===== S4 three-portal additions (docs/Three_Portal_Feature_Spec.md) =====
export type JoinRequestDto = {
  id: string
  familyId: string
  familyName: string
  requesterDisplayName: string
  requesterEmailMasked: string
  relationshipType: string
  message?: string | null
  status: 'Pending' | 'Accepted' | 'Declined' | 'Cancelled'
  createdAt: string
  respondedAt?: string | null
}
export type DoctorSummaryDto = {
  id: string
  displayName: string
  specialty?: string | null
  clinic?: string | null
  district?: string | null
  city?: string | null
  languages?: string | null
}
export type DoctorRequestDto = {
  id: string
  familyId: string
  familyName: string
  memberCount: number
  doctor: DoctorSummaryDto
  message?: string | null
  status: 'Pending' | 'Accepted' | 'Declined' | 'Cancelled'
  createdAt: string
}
export type AppointmentDto = {
  id: string
  memberId: string
  memberDisplayName: string
  familyName: string
  doctor: DoctorSummaryDto
  startsAt: string
  durationMinutes: number
  reason: string
  status: 'Requested' | 'Confirmed' | 'Completed' | 'Cancelled' | 'NoShow'
  doctorNote?: string | null
  createdAt: string
}
export type NotificationDto = {
  id: string
  type: string
  title: string
  body: string
  linkPath?: string | null
  readAt?: string | null
  createdAt: string
}
export type FamilyDashboardSummaryDto = {
  role: string
  familyId: string
  familyName: string
  familyCode?: string | null
  memberCount: number
  minorCount: number
  pendingJoinRequests?: number
  nextAppointment?: AppointmentDto | null
  openCases: number
  approvedGuidanceCount: number
  familyDoctor?: DoctorSummaryDto | null
  unreadNotifications: number
  recentActivity: string[]
  // Mockup-aligned additions (2026-09-28); optional so older API builds still render.
  viewerDisplayName?: string
  members?: DashboardMemberDto[]
  activity?: DashboardActivityDto[]
  visibleReportCount?: number
  latestLab?: DashboardLabSummaryDto | null
  latestVital?: DashboardVitalDto | null
  upcomingAppointments?: number
}
export type DashboardMemberDto = { id: string; displayName: string; role: string; isSelf: boolean; isMinor: boolean; summary: string }
export type DashboardActivityDto = { title: string; subject?: string | null; occurredAt: string }
export type DashboardLabSummaryDto = {
  id: string
  memberDisplayName: string
  fileName: string
  collectedAt?: string | null
  belowRange: number
  withinRange: number
  aboveRange: number
  rangeUnavailable: number
  confirmed: boolean
}
export type DashboardVitalDto = { vitalType: string; value: number; unit: string; measuredAt: string }
export type DoctorFamilyRowDto = { familyId: string; familyName: string; memberCount: number; lastVisit?: string | null; nextAppointment?: string | null }
export type DoctorDashboardSummaryDto = {
  todayAppointments: AppointmentDto[]
  pendingApprovals: number
  openCases: number
  pendingFamilyRequests: number
  assignedFamilies: number
  unreadNotifications: number
  doctorDisplayName?: string
  specialty?: string | null
  verificationStatus?: string
  priorityOpenCases?: number
  families?: DoctorFamilyRowDto[]
  activity?: DashboardActivityDto[]
}

export const threePortalApi = {
  getFamilyDashboard: () => apiClient.get<FamilyDashboardSummaryDto>('/dashboard/family'),
  getDoctorDashboard: () => apiClient.get<DoctorDashboardSummaryDto>('/dashboard/doctor'),

  submitJoinRequest: (body: { familyCode: string; relationshipType: string; message?: string }) =>
    apiClient.post<JoinRequestDto>('/families/join-requests', body),
  getMyJoinRequests: () => apiClient.get<JoinRequestDto[]>('/families/join-requests/mine'),
  getFamilyJoinRequests: (familyId: string, status = 'Pending') =>
    apiClient.get<JoinRequestDto[]>(`/families/${familyId}/join-requests`, { params: { status } }),
  acceptJoinRequest: (id: string) => apiClient.post(`/families/join-requests/${id}/accept`),
  declineJoinRequest: (id: string) => apiClient.post(`/families/join-requests/${id}/decline`),

  getDoctorDirectory: (params?: { search?: string; district?: string }) =>
    apiClient.get<DoctorSummaryDto[]>('/doctors/directory', { params }),
  getFamilyDoctor: (familyId: string) => apiClient.get<DoctorSummaryDto | null>(`/families/${familyId}/doctor`),
  requestFamilyDoctor: (familyId: string, body: { doctorId: string; message?: string }) =>
    apiClient.post<DoctorRequestDto>(`/families/${familyId}/doctor-requests`, body),
  getMyFamilyDoctorRequests: () => apiClient.get<DoctorRequestDto[]>('/doctors/me/family-requests'),
  acceptFamilyDoctorRequest: (id: string) => apiClient.post(`/doctors/me/family-requests/${id}/accept`),
  declineFamilyDoctorRequest: (id: string) => apiClient.post(`/doctors/me/family-requests/${id}/decline`),

  bookAppointment: (body: { memberId: string; startsAt: string; durationMinutes?: number; reason: string }) =>
    apiClient.post<AppointmentDto>('/appointments', body),
  getMyAppointments: () => apiClient.get<AppointmentDto[]>('/appointments/mine'),
  cancelAppointment: (id: string) => apiClient.post(`/appointments/${id}/cancel`),
  getDoctorAppointments: (params?: { from?: string; to?: string }) =>
    apiClient.get<AppointmentDto[]>('/doctors/me/appointments', { params }),
  setAppointmentStatus: (id: string, action: 'confirm' | 'complete' | 'no-show' | 'cancel', note?: string) =>
    apiClient.post(`/doctors/me/appointments/${id}/${action}`, { note }),

  getNotifications: (unreadOnly?: boolean) =>
    apiClient.get<NotificationDto[]>('/notifications', { params: unreadOnly ? { unreadOnly: true } : undefined }),
  markNotificationRead: (id: string) => apiClient.post(`/notifications/${id}/read`),
}
