// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// Appointments: list mine, book (self, or minors when Head), cancel.
import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react'

import { EmptyState, ErrorState, LoadingState } from '../../components/shared/ViewState'
import { useAppSelector } from '../../store/hooks'
import {
  apiClient,
  doctorWorkspaceApi,
  threePortalApi,
  type AppointmentDto,
  type DoctorSlotsDto,
  type DoctorSummaryDto,
  type FamilyDto,
  type MemberDto,
} from '../../services/apiClient'
import { FriendlyStatusBadge } from './threePortalShared'
import { extractErrorMessage, formatDateTime } from './threePortalUtils'
import { PageHero } from '../dashboard/dashboardParts'
import { todayLocalDate } from '../records/recordSummaryMeta'

function isMinor(member: MemberDto): boolean {
  const dob = new Date(member.dateOfBirth)
  if (Number.isNaN(dob.getTime())) return false
  const cutoff = new Date()
  cutoff.setUTCFullYear(cutoff.getUTCFullYear() - 18)
  return dob > cutoff
}

export function AppointmentsPage() {
  const user = useAppSelector((state) => state.auth.user)
  const isHead = user?.role === 'FAMILY_HEAD'

  const [appointments, setAppointments] = useState<AppointmentDto[]>([])
  const [members, setMembers] = useState<MemberDto[]>([])
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading')
  const [message, setMessage] = useState('')
  const [submitting, setSubmitting] = useState(false)

  // Server marks the caller's own member row with isSelf; it still rejects (404) booking for anyone else.
  const bookableMembers = useMemo(
    () => members.filter((member) => member.isSelf || (isHead && isMinor(member))),
    [members, isHead],
  )

  const [familyId, setFamilyId] = useState('')
  const [familyDoctor, setFamilyDoctor] = useState<DoctorSummaryDto | null>(null)
  const [selectedDate, setSelectedDate] = useState('')
  const [attachmentName, setAttachmentName] = useState('')
  const [slots, setSlots] = useState<DoctorSlotsDto | null>(null)
  const [slotMessage, setSlotMessage] = useState('')

  // Free slots come from the doctor's weekly hours (DECISIONS 2026-09-29h). No hours set → free time entry.
  async function loadSlots(date: string) {
    setSlots(null); setSlotMessage('')
    if (!date || !familyId) return
    try {
      setSlots((await doctorWorkspaceApi.getFamilyDoctorSlots(familyId, date)).data)
    } catch (error) {
      setSlotMessage(extractErrorMessage(error, 'Free times could not be loaded. You can still request a time.'))
    }
  }

  const load = useCallback(async () => {
    setStatus('loading')
    try {
      const [{ data: appts }, { data: family }] = await Promise.all([
        threePortalApi.getMyAppointments(),
        apiClient.get<FamilyDto>('/families/me'),
      ])
      setAppointments(appts)
      setMembers(family.members)
      setFamilyId(family.id)

      // Bookings always go to the family's assigned doctor (the server decides), so this is display only.
      try {
        const { data: doctor } = await apiClient.get<DoctorSummaryDto | null>(`/families/${family.id}/doctor`)
        setFamilyDoctor(doctor?.id ? doctor : null)
      } catch {
        setFamilyDoctor(null)
      }

      setStatus('ready')
    } catch {
      setStatus('error')
    }
  }, [])

  useEffect(() => {
    void load()
  }, [load])

  async function book(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const formElement = event.currentTarget
    const form = new FormData(formElement)
    const memberId = String(form.get('memberId') || '')
    const date = String(form.get('date') || '')
    const time = String(form.get('time') || '')
    const slot = String(form.get('slot') || '')
    const reason = String(form.get('reason') || '').trim()
    const attachment = (formElement.elements.namedItem('attachment') as HTMLInputElement | null)?.files?.[0]
    if (!memberId || !date || !(time || slot) || !reason) {
      setMessage('Please fill in all appointment details.')
      return
    }

    const startsAt = slot || new Date(`${date}T${time}:00`).toISOString()
    setSubmitting(true)
    setMessage('')
    try {
      await threePortalApi.bookAppointment({
        memberId,
        startsAt,
        reason,
        durationMinutes: slots?.availabilityConfigured ? slots.slotMinutes : 30,
      })
      // Upload only after the booking exists, and say so plainly if the file did not go through.
      let attachmentNote = ''
      if (attachment instanceof File && attachment.size > 0) {
        const uploadForm = new FormData()
        uploadForm.append('file', attachment)
        uploadForm.append('collectedAt', new Date().toISOString())
        try {
          await apiClient.post(`/members/${memberId}/lab-reports`, uploadForm, {
            headers: { 'Content-Type': 'multipart/form-data' },
          })
          attachmentNote = ` "${attachment.name}" was saved to the member's lab reports.`
        } catch {
          attachmentNote = ` "${attachment.name}" could not be uploaded — add it from Health records (PNG, JPEG or PDF, up to 10 MB).`
        }
      }
      formElement.reset()
      setAttachmentName('')
      setSelectedDate('')
      setSlots(null)
      setMessage(`Appointment requested. You will be notified once the doctor confirms it.${attachmentNote}`)
      await load()
    } catch (error) {
      setMessage(extractErrorMessage(error, 'Appointment could not be booked.'))
    } finally {
      setSubmitting(false)
    }
  }

  async function cancel(appointment: AppointmentDto) {
    if (!window.confirm('Cancel this appointment?')) return
    try {
      await threePortalApi.cancelAppointment(appointment.id)
      setMessage('Appointment cancelled.')
      await load()
    } catch (error) {
      setMessage(extractErrorMessage(error, 'Appointment could not be cancelled.'))
    }
  }

  if (status === 'loading') return <LoadingState label="Loading appointments" />
  if (status === 'error') return <ErrorState message="Appointments could not be loaded." onRetry={() => void load()} />

  return (
    <div className="page-stack">
      <PageHero
        eyebrow="Appointments"
        title="Appointments"
        purpose={isHead
          ? "Appointments for you and your minors. Adults' private appointments are not shown here."
          : 'Your own appointments. They are private from the Family Head.'}
      />

      {message && <p role="status" className="status-banner">{message}</p>}

      <section className="panel">
        <h2>Book an appointment</h2>
        <form className="form-grid" onSubmit={(event) => void book(event)}>
          <label>
            Member
            <select name="memberId" required defaultValue="">
              <option value="" disabled>Select member</option>
              {bookableMembers.map((member) => (
                <option key={member.id} value={member.id}>{member.displayName}</option>
              ))}
            </select>
          </label>
          <div>
            <span>Doctor</span>
            {familyDoctor ? (
              <p>
                <strong>{familyDoctor.displayName}</strong>
                {familyDoctor.specialty ? ` (${familyDoctor.specialty})` : ''}
                <small className="muted"> — your family doctor. Appointments are booked with them.</small>
              </p>
            ) : (
              <p className="muted">No family doctor is assigned yet. Choose one under My Doctor before booking.</p>
            )}
          </div>
          <label>
            Date
            <input
              name="date"
              type="date"
              required
              min={todayLocalDate()}
              value={selectedDate}
              onChange={(event) => {
                setSelectedDate(event.target.value)
                void loadSlots(event.target.value)
              }}
            />
          </label>
          {slots?.availabilityConfigured ? (
            <label>
              Free time
              {slots.slots.length === 0 ? <span className="muted">No free times on this day. Try another date.</span> : (
                <select name="slot" required defaultValue="">
                  <option value="" disabled>Select a free time</option>
                  {slots.slots.map((slot) => <option key={slot} value={slot}>{new Date(slot).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</option>)}
                </select>
              )}
            </label>
          ) : (
            <label>
              Time
              <input name="time" type="time" required />
              {slots && <small className="muted">Your doctor has not set weekly hours yet, so request any time and they will confirm it.</small>}
            </label>
          )}
          {slotMessage && <p className="muted">{slotMessage}</p>}
          <label>
            Reason
            <input name="reason" required maxLength={200} placeholder="e.g. Follow-up consultation" />
          </label>
          <div>
            <span>Attachment (optional)</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginTop: '6px' }}>
              <input
                type="file"
                name="attachment"
                id="appointment-attachment"
                accept=".pdf,image/png,image/jpeg"
                className="sr-only"
                onChange={(e) => {
                  const f = e.target.files?.[0]
                  setAttachmentName(f ? f.name : '')
                }}
              />
              <label
                htmlFor="appointment-attachment"
                className="button button--secondary"
                style={{ cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: '8px' }}
              >
                <span>📎</span>
                <span>{attachmentName ? 'Change report' : 'Upload medical report / referral'}</span>
              </label>
              {attachmentName && (
                <span style={{ fontSize: '13px', color: 'var(--muted, #666)' }}>
                  {attachmentName}
                </span>
              )}
            </div>
          </div>
          <button className="button button--primary" type="submit" disabled={submitting}>
            {submitting ? 'Booking…' : 'Book appointment'}
          </button>
        </form>
      </section>

      <section className="panel">
        <h2>My appointments</h2>
        {appointments.length === 0 ? (
          <EmptyState title="No appointments yet" message="Book an appointment above." />
        ) : (
          <div className="table-scroll">
            <table>
              <thead>
                <tr>
                  <th>Member</th>
                  <th>Doctor</th>
                  <th>When</th>
                  <th>Reason</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {appointments.map((appointment) => (
                  <tr key={appointment.id}>
                    <td>{appointment.memberDisplayName}</td>
                    <td>{appointment.doctor?.displayName ?? '—'}</td>
                    <td>{formatDateTime(appointment.startsAt)}</td>
                    <td>{appointment.reason}</td>
                    <td><FriendlyStatusBadge status={appointment.status} /></td>
                    <td>
                      {(appointment.status === 'Requested' || appointment.status === 'Confirmed') && (
                        <button className="button button--danger" type="button" onClick={() => void cancel(appointment)}>
                          Cancel
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  )
}
