// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import '@testing-library/jest-dom/vitest'

import { configureStore } from '@reduxjs/toolkit'
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { Provider } from 'react-redux'
import { MemoryRouter } from 'react-router-dom'
import { describe, expect, it, vi } from 'vitest'

const mocks = vi.hoisted(() => ({
  get: vi.fn(),
  post: vi.fn(),
  getMyAppointments: vi.fn(),
  bookAppointment: vi.fn(),
  getFamilyDoctorSlots: vi.fn(),
}))
vi.mock('../../services/apiClient', () => ({
  apiClient: { get: mocks.get, post: mocks.post },
  threePortalApi: { getMyAppointments: mocks.getMyAppointments, bookAppointment: mocks.bookAppointment },
  doctorWorkspaceApi: { getFamilyDoctorSlots: mocks.getFamilyDoctorSlots },
}))

import authReducer, { signedIn } from '../../store/slices/authSlice'
import { AppointmentsPage } from './AppointmentsPage'

const adultDob = new Date()
adultDob.setUTCFullYear(adultDob.getUTCFullYear() - 30)
const minorDob = new Date()
minorDob.setUTCFullYear(minorDob.getUTCFullYear() - 10)

const family = {
  id: 'family-1',
  name: 'Silva Family',
  members: [
    { id: 'self-1', familyId: 'family-1', displayName: 'Me', dateOfBirth: adultDob.toISOString(), role: 'AdultMember', isSelf: true },
    { id: 'sibling-1', familyId: 'family-1', displayName: 'My Sibling', dateOfBirth: adultDob.toISOString(), role: 'AdultMember' },
    { id: 'minor-1', familyId: 'family-1', displayName: 'Young Kid', dateOfBirth: minorDob.toISOString(), role: 'MinorMember' },
  ],
}

function renderAsAdult() {
  mocks.get.mockImplementation((url: string) =>
    Promise.resolve(
      url === '/families/family-1/doctor'
        ? { data: { id: 'doc-1', displayName: 'Dr. Perera', specialty: 'Family Medicine' } }
        : { data: family },
    ),
  )
  mocks.getMyAppointments.mockResolvedValue({ data: [] })

  const store = configureStore({ reducer: { auth: authReducer } })
  store.dispatch(signedIn({
    id: 'self-1',
    name: 'Me',
    role: 'MEMBER',
  } as never))

  return render(
    <Provider store={store}>
      <MemoryRouter>
        <AppointmentsPage />
      </MemoryRouter>
    </Provider>,
  )
}

describe('AppointmentsPage booking form', () => {
  it('limits an adult member to booking for self only', async () => {
    renderAsAdult()

    await waitFor(() => expect(screen.getByText('Book an appointment')).toBeInTheDocument())

    const select = screen.getByLabelText('Member') as HTMLSelectElement
    const options = within(select).getAllByRole('option').map((option) => option.textContent)

    expect(options).toContain('Me')
    expect(options).not.toContain('My Sibling')
    expect(options).not.toContain('Young Kid')
  })

  it('shows success after a booking response', async () => {
    renderAsAdult()
    mocks.bookAppointment.mockResolvedValue({ data: { id: 'appointment-1' } })

    await waitFor(() => expect(screen.getByText('Book an appointment')).toBeInTheDocument())
    fireEvent.change(screen.getByLabelText('Member'), { target: { value: 'self-1' } })
    fireEvent.change(screen.getByLabelText('Date'), { target: { value: '2027-01-01' } })
    fireEvent.change(screen.getByLabelText('Time'), { target: { value: '10:00' } })
    fireEvent.change(screen.getByLabelText('Reason'), { target: { value: 'Synthetic follow-up' } })
    fireEvent.submit(screen.getByRole('button', { name: 'Book appointment' }).closest('form')!)

    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Appointment requested.'))
  })

  it('shows the assigned family doctor without offering a choice the server would ignore', async () => {
    renderAsAdult()

    await waitFor(() => expect(screen.getByText('Dr. Perera')).toBeInTheDocument())
    expect(screen.queryByRole('combobox', { name: 'Doctor' })).not.toBeInTheDocument()
    expect(mocks.get).not.toHaveBeenCalledWith('/doctors/directory')
    expect(screen.getByText('Attachment (optional)')).toBeInTheDocument()
    expect(screen.getByText('Upload medical report / referral')).toBeInTheDocument()
  })

  it('books first, then reports an attachment that failed to upload instead of hiding it', async () => {
    renderAsAdult()
    mocks.bookAppointment.mockResolvedValue({ data: { id: 'appointment-1' } })
    mocks.post.mockRejectedValue(new Error('upload failed'))

    await waitFor(() => expect(screen.getByText('Book an appointment')).toBeInTheDocument())
    fireEvent.change(screen.getByLabelText('Member'), { target: { value: 'self-1' } })
    fireEvent.change(screen.getByLabelText('Date'), { target: { value: '2027-01-01' } })
    fireEvent.change(screen.getByLabelText('Time'), { target: { value: '10:00' } })
    fireEvent.change(screen.getByLabelText('Reason'), { target: { value: 'Synthetic follow-up' } })
    const file = new File(['synthetic'], 'synthetic-referral.pdf', { type: 'application/pdf' })
    await userEvent.upload(document.getElementById('appointment-attachment') as HTMLInputElement, file)
    fireEvent.submit(screen.getByRole('button', { name: 'Book appointment' }).closest('form')!)

    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('could not be uploaded'))
    expect(mocks.bookAppointment).toHaveBeenCalledWith(expect.objectContaining({ reason: 'Synthetic follow-up' }))
    expect(mocks.post).toHaveBeenCalledWith('/members/self-1/lab-reports', expect.any(FormData), expect.anything())
  })

  it('offers only the doctor\'s free slots once weekly hours exist, and books the chosen slot', async () => {
    mocks.getFamilyDoctorSlots.mockResolvedValue({ data: { date: '2026-10-05', availabilityConfigured: true, slotMinutes: 20, slots: ['2026-10-05T03:30:00+00:00'] } })
    mocks.bookAppointment.mockResolvedValue({ data: {} })
    renderAsAdult()

    fireEvent.change(await screen.findByLabelText('Date'), { target: { value: '2026-10-05' } })
    const slotSelect = await screen.findByLabelText('Free time')
    expect(mocks.getFamilyDoctorSlots).toHaveBeenCalledWith('family-1', '2026-10-05')
    expect(screen.queryByLabelText('Time')).not.toBeInTheDocument()

    fireEvent.change(screen.getByLabelText('Member'), { target: { value: 'self-1' } })
    fireEvent.change(slotSelect, { target: { value: '2026-10-05T03:30:00+00:00' } })
    fireEvent.change(screen.getByLabelText('Reason'), { target: { value: 'Synthetic follow-up' } })
    fireEvent.submit(screen.getByRole('button', { name: 'Book appointment' }).closest('form')!)

    await waitFor(() => expect(mocks.bookAppointment).toHaveBeenCalledWith({
      memberId: 'self-1', startsAt: '2026-10-05T03:30:00+00:00', reason: 'Synthetic follow-up', durationMinutes: 20,
    }))
  })
})
