// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
// Shared display components for the three-portal features (docs/Three_Portal_Feature_Spec.md).
// No AI in these features — pure CRUD + deterministic rules.
import { friendlyStatusLabel, toneByFriendlyStatus } from './threePortalUtils'

export { friendlyStatusLabel, formatDateTime, formatDay, extractErrorMessage } from './threePortalUtils'

export function FriendlyStatusBadge({ status }: { status: string }) {
  const tone = toneByFriendlyStatus[status] ?? 'muted'
  return <span className={`status-badge status-badge--${tone}`}>{friendlyStatusLabel(status)}</span>
}
